import { CognitiveChallenge } from "./types";

export const CREATIVITY_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "cre-01",
    title: "The Desert Water Cooler",
    category: "Creativity",
    subcategory: "Alternative Object Uses",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 20,
    cognitiveSkill: "Divergent Functional Flexibility",
    instruction: "Choose the most inventive and effective solution using everyday materials.",
    question: "You have 2 clay pots, sand, and water under extreme heat. How do you keep food cold without electricity?",
    options: [
      {
        id: "o1",
        label: "Place the smaller pot inside the larger one, fill the gap with wet sand (Zeer evaporative pot).",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Bury both pots directly under dry hot sand in direct sunlight.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Wrap the pots with dry newspaper and seal them airtight.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Evaporative cooling (Zeer pot) leverages latent heat of vaporization—divergent thinking connects physics to low-tech materials.",
    xpReward: 55,
    coinReward: 15,
  },
  {
    id: "cre-02",
    title: "The Candle-Wall Problem (Duncker)",
    category: "Creativity",
    subcategory: "Functional Fixedness Overcoming",
    difficulty: "advanced",
    type: "decision_room",
    estimatedTimeSec: 25,
    cognitiveSkill: "Overcoming Functional Fixedness",
    instruction: "You have a candle, a box of thumbtacks, and a book of matches. How do you attach the lit candle to a cork wall without wax dripping on the table?",
    question: "What is the most creative and structurally sound solution?",
    options: [
      {
        id: "o1",
        label: "Empty the thumbtack box, tack the empty box to the wall, and place the candle inside it.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Melt the side of the candle and push it directly against the wall.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Pin the wick directly with three tacks into the cork board.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Duncker's classic Candle Problem demonstrates overcoming functional fixedness—viewing the box as a platform rather than just a container.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "cre-03",
    title: "Remote Association: Triad Link",
    category: "Creativity",
    subcategory: "Remote Associates",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 18,
    cognitiveSkill: "Convergent Semantic Association",
    instruction: "Find the single word that connects all three words.",
    question: "What word links: SOUR  •  TART  •  DROP ?",
    options: [
      { id: "o1", label: "LEMON", isCorrect: true },
      { id: "o2", label: "WATER", isCorrect: false },
      { id: "o3", label: "CANDY", isCorrect: false },
      { id: "o4", label: "APPLE", isCorrect: false },
    ],
    educationalWhy: "Remote Associates Test (RAT) measures convergent creative synthesis across distant semantic nodes.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "cre-04",
    title: "The 9-Dot Puzzle Outside The Box",
    category: "Creativity",
    subcategory: "Lateral Boundary Inversion",
    difficulty: "advanced",
    type: "decision_room",
    estimatedTimeSec: 20,
    cognitiveSkill: "Cognitive Boundary Dissolution",
    instruction: "How do you connect a 3x3 grid of 9 dots with only 4 straight continuous lines without lifting your pen?",
    question: "What constraint must you eliminate to solve the puzzle?",
    options: [
      {
        id: "o1",
        label: "Extend lines beyond the imaginary perimeter square enclosing the dots.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Draw circular curved arcs between the outer corners.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Only connect the 4 outer corner dots and skip the center.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Origin of 'thinking outside the box'—our brains project non-existent boundary constraints that restrict creative discovery.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "cre-05",
    title: "Reverse Brainstorming: Innovation by Inversion",
    category: "Creativity",
    subcategory: "Inversion Thinking",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 20,
    cognitiveSkill: "Inversive Ideation",
    instruction: "To create the best customer onboarding app, ask: 'How could we make the onboarding experience as confusing as possible?'",
    question: "How does reverse brainstorming unlock breakthrough design ideas?",
    options: [
      {
        id: "o1",
        label: "It pinpoints hidden friction points and failure modes that traditional brainstorming overlooks.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "It lowers the standards of the product so less effort is needed.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "It replaces all user testing with theoretical guesses.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Charlie Munger's inversion technique ('Invert, always invert') systematically removes blockers to reveal optimal solutions.",
    xpReward: 55,
    coinReward: 15,
  },
];
