import { CognitiveChallenge } from "./types";

export const EQ_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "eq-01",
    title: "The Defensive Colleague Scenario",
    category: "Emotional Intelligence",
    subcategory: "Conflict Resolution",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 22,
    cognitiveSkill: "Empathic De-escalation",
    instruction: "A team member reacts defensively during a code/design review: 'You are just finding faults with my work!'",
    question: "What is the most emotionally intelligent response?",
    options: [
      {
        id: "o1",
        label: "'I value the effort you put in. My goal is just to help our project succeed together. Which part feels unfair?'",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "'If you can't take constructive feedback, you shouldn't be on this project.'",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Stay silent and report them immediately to upper management.",
        isCorrect: false,
      },
      {
        id: "o4",
        label: "'Calm down, you are overreacting.'",
        isCorrect: false,
      },
    ],
    educationalWhy: "Validating intent and inviting dialogue reduces amygdala threat response and builds psychological safety.",
    xpReward: 55,
    coinReward: 15,
  },
  {
    id: "eq-02",
    title: "Executive Tense Board Meeting",
    category: "Emotional Intelligence",
    subcategory: "Self-Regulation Under Pressure",
    difficulty: "advanced",
    type: "decision_room",
    estimatedTimeSec: 25,
    cognitiveSkill: "Cognitive Reappraisal",
    instruction: "During a major presentation, a stakeholder interrupts harshly, challenging your data validity.",
    question: "How do you respond with peak emotional self-control?",
    options: [
      {
        id: "o1",
        label: "Pause for 2 seconds, acknowledge their concern calmly, and walk through the exact methodology step-by-step.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Interrupt them back to defend your authority.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Rush through the rest of the presentation to finish quickly.",
        isCorrect: false,
      },
    ],
    educationalWhy: "A 2-second tactical pause activates the ventromedial prefrontal cortex, preventing impulsive reactivity.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "eq-03",
    title: "Burnout Recognition in Team Member",
    category: "Emotional Intelligence",
    subcategory: "Social Awareness & Empathy",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 22,
    cognitiveSkill: "Empathic Proactivity",
    instruction: "A usually energetic colleague is suddenly quiet, missing deadlines, and replying with 1-word emails.",
    question: "What is the most supportive and effective leadership action?",
    options: [
      {
        id: "o1",
        label: "Schedule a private 1-on-1: 'I noticed you seem carrying a heavy load lately. How are you doing, and how can I support you?'",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Assign them more work so they don't have time to feel tired.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Send a public email reminding the team about missing deadlines.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Empathic inquiry creates an environment where team members can communicate boundaries before complete exhaustion.",
    xpReward: 55,
    coinReward: 15,
  },
  {
    id: "eq-04",
    title: "Active Listening vs Premature Fixing",
    category: "Emotional Intelligence",
    subcategory: "Perspective Taking",
    difficulty: "beginner",
    type: "decision_room",
    estimatedTimeSec: 18,
    cognitiveSkill: "Active Empathetic Listening",
    instruction: "A friend shares: 'I had the most exhausting day at work, everything went wrong.'",
    question: "What is the best initial conversational response?",
    options: [
      {
        id: "o1",
        label: "'That sounds really draining. Do you want to vent and talk through it, or do you want to brainstorm solutions?'",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "'You should just quit and find a new job tomorrow.'",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "'Well, my day was much worse than yours, let me tell you.'",
        isCorrect: false,
      },
    ],
    educationalWhy: "Asking whether someone needs emotional holding vs problem solving respects their immediate cognitive state.",
    xpReward: 45,
    coinReward: 10,
  },
];
