import { CognitiveChallenge } from "./types";

export const EXECUTIVE_DECISION_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "exec-01",
    title: "The Sunk Cost Dilemma",
    category: "Executive Decisions",
    subcategory: "Resource Allocation",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 25,
    cognitiveSkill: "Rational Asset Allocation",
    instruction: "Analyze this executive scenario and pick the most rational choice.",
    question: "Your team spent $45,000 developing Feature A, but user demand just shifted 100% to Feature B. Should you finish Feature A to 'not waste money'?",
    options: [
      {
        id: "o1",
        label: "Pivot immediately to Feature B. Sunk costs cannot be recovered; only future returns matter.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Complete Feature A first so that the initial $45,000 engineering investment is not written off.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Split engineering budget 50/50 between both features indefinitely to mitigate political fallout.",
        isCorrect: false,
      },
      {
        id: "o4",
        label: "Double the marketing budget for Feature A to artificially stimulate demand before pivoting.",
        isCorrect: false,
      },
    ],
    educationalWhy: "The Sunk Cost Fallacy tricks our brains into throwing good resources after bad. Rational decision-makers only weigh future expected value.",
    xpReward: 55,
    coinReward: 15,
  },
  {
    id: "exec-02",
    title: "Crisis Triage Prioritization",
    category: "Executive Decisions",
    subcategory: "Incident Management",
    difficulty: "advanced",
    type: "decision_room",
    estimatedTimeSec: 25,
    cognitiveSkill: "Systemic Root-Cause Prioritization",
    instruction: "Make a high-stakes operational decision under time pressure.",
    question: "Your database latency spikes to 95% causing payment timeouts, while marketing is about to blast 50,000 push notifications. What must happen first?",
    options: [
      {
        id: "o1",
        label: "Immediately pause the push notification blast, scale database replicas, and verify payment gateways.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "Allow the notification blast to proceed as planned to observe if the cluster recovers under traffic.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Shut down the entire web platform completely for 24 hours without customer communication.",
        isCorrect: false,
      },
      {
        id: "o4",
        label: "Ignore database metrics and focus on drafting promotional email copy for the next campaign.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Incident triage requires throttling incoming traffic surges to protect core transactional integrity.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "exec-03",
    title: "Opportunity Cost Evaluation",
    category: "Executive Decisions",
    subcategory: "Strategic Tradeoffs",
    difficulty: "intermediate",
    type: "decision_room",
    estimatedTimeSec: 20,
    cognitiveSkill: "Opportunity Cost Calculation",
    instruction: "You have 1 senior engineer for 2 weeks.",
    question: "Project Alpha brings $10k recurring revenue. Project Beta saves $3k one-time cost. What is the true opportunity cost of choosing Project Beta?",
    options: [
      {
        id: "o1",
        label: "Foregoing $10,000 monthly recurring revenue from Project Alpha for a small one-time savings.",
        isCorrect: true,
      },
      {
        id: "o2",
        label: "The $3,000 one-time operational savings achieved by completing Project Beta on schedule.",
        isCorrect: false,
      },
      {
        id: "o3",
        label: "Zero opportunity cost because the engineer remains fully utilized and productive throughout.",
        isCorrect: false,
      },
      {
        id: "o4",
        label: "The baseline salary and compensation paid to the senior engineer over the two-week period.",
        isCorrect: false,
      },
    ],
    educationalWhy: "Opportunity cost is the highest-value alternative foregone when making a decision.",
    xpReward: 55,
    coinReward: 15,
  },
];
