import { CognitiveChallenge } from "./types";

export const FOCUS_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "foc-01",
    title: "Focus Fire Conjunction Rule",
    category: "Focus & Attention",
    subcategory: "Selective Attention",
    difficulty: "beginner",
    type: "focus_fire",
    estimatedTimeSec: 15,
    cognitiveSkill: "Conjunction Search & Feature Binding",
    instruction: "Apply the logical rule strictly without getting distracted.",
    question: "Rule: Target must be BOTH 🔵 (Blue) AND have 4 sides (Square). Which item qualifies?",
    options: [
      { id: "o1", label: "🟦 Blue Square", isCorrect: true },
      { id: "o2", label: "🔵 Blue Circle (Not 4 sides)", isCorrect: false },
      { id: "o3", label: "🔺 Red Triangle (Wrong color/sides)", isCorrect: false },
      { id: "o4", label: "🟩 Green Square (Wrong color)", isCorrect: false },
    ],
    educationalWhy: "Conjunction searches require dual-attribute feature binding in the parietal cortex, strengthening selective attention.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "foc-02",
    title: "Distractor Suppression Tally",
    category: "Focus & Attention",
    subcategory: "Sustained Attention",
    difficulty: "beginner",
    type: "focus_fire",
    estimatedTimeSec: 15,
    cognitiveSkill: "Distractor Suppression",
    instruction: "Count the target letter while ignoring all other letters.",
    question: "How many times does the letter 'E' appear in: EXCELLENCE ?",
    options: [
      { id: "o1", label: "4 times", isCorrect: true },
      { id: "o2", label: "3 times", isCorrect: false },
      { id: "o3", label: "5 times", isCorrect: false },
      { id: "o4", label: "2 times", isCorrect: false },
    ],
    educationalWhy: "Visual symbol tallying exercises sustained vigilance and working memory buffer updating.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "foc-03",
    title: "Selective Signal Extraction",
    category: "Focus & Attention",
    subcategory: "Divided Attention",
    difficulty: "intermediate",
    type: "focus_fire",
    estimatedTimeSec: 18,
    cognitiveSkill: "Signal-to-Noise Extraction",
    instruction: "Filter out non-actionable chatter to identify the sole authorized instruction.",
    question: "In a meeting: 4 people speak, but only Sarah has budget sign-off. Sarah says 'Approve 12 laptops'. What was officially approved?",
    options: [
      { id: "o1", label: "12 Laptops", isCorrect: true },
      { id: "o2", label: "20 Laptops", isCorrect: false },
      { id: "o3", label: "10 Tablets", isCorrect: false },
      { id: "o4", label: "Nothing", isCorrect: false },
    ],
    educationalWhy: "Source-monitoring suppression filters background distraction from authoritative signals.",
    xpReward: 50,
    coinReward: 12,
  },
];
