import { CognitiveChallenge } from "./types";

export const LOGIC_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "log-01",
    title: "Geometric Alternating Sequence",
    category: "Logic & Reasoning",
    subcategory: "Pattern Completion",
    difficulty: "beginner",
    type: "pattern_recognition",
    estimatedTimeSec: 15,
    cognitiveSkill: "Inductive Pattern Recognition",
    instruction: "Identify the alternating rule governing this pattern.",
    question: "Complete the sequence: ▲  ●  ▲  ●  ▲  ?",
    options: [
      { id: "o1", label: "● (Circle)", isCorrect: true },
      { id: "o2", label: "▲ (Triangle)", isCorrect: false },
      { id: "o3", label: "■ (Square)", isCorrect: false },
      { id: "o4", label: "◆ (Diamond)", isCorrect: false },
    ],
    educationalWhy: "Rule deduction from geometric sequences trains inductive logical reasoning.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "log-02",
    title: "Double-Step Exponential Progression",
    category: "Logic & Reasoning",
    subcategory: "Number Sequences",
    difficulty: "beginner",
    type: "pattern_recognition",
    estimatedTimeSec: 15,
    cognitiveSkill: "Arithmetic Progression",
    instruction: "Find the missing number in the increasing sequence.",
    question: "What number comes next: 2,  4,  8,  16,  32,  ?",
    options: [
      { id: "o1", label: "64", isCorrect: true },
      { id: "o2", label: "48", isCorrect: false },
      { id: "o3", label: "60", isCorrect: false },
      { id: "o4", label: "72", isCorrect: false },
    ],
    educationalWhy: "Geometric doubling sequences reinforce exponential pattern recognition.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "log-03",
    title: "Prime Sequence Matrix",
    category: "Logic & Reasoning",
    subcategory: "Number Theory",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 18,
    cognitiveSkill: "Prime Number Deduction",
    instruction: "Identify the mathematical rule governing the series.",
    question: "Which number completes the prime sequence: 3,  5,  7,  11,  13,  ?",
    options: [
      { id: "o1", label: "17", isCorrect: true },
      { id: "o2", label: "15", isCorrect: false },
      { id: "o3", label: "19", isCorrect: false },
      { id: "o4", label: "21", isCorrect: false },
    ],
    educationalWhy: "Prime detection tests mathematical pattern filtering and composite elimination.",
    xpReward: 50,
    coinReward: 15,
  },
  {
    id: "log-04",
    title: "Fibonacci Recursive Spiral",
    category: "Logic & Reasoning",
    subcategory: "Recursive Series",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 18,
    cognitiveSkill: "Recursive Synthesis",
    instruction: "Each term is the sum of the two preceding numbers.",
    question: "What is the next number: 1,  1,  2,  3,  5,  8,  ?",
    options: [
      { id: "o1", label: "13", isCorrect: true },
      { id: "o2", label: "11", isCorrect: false },
      { id: "o3", label: "15", isCorrect: false },
      { id: "o4", label: "14", isCorrect: false },
    ],
    educationalWhy: "Fibonacci sequences stimulate recursive problem solving in the dorsolateral prefrontal cortex.",
    xpReward: 50,
    coinReward: 15,
  },
  {
    id: "log-05",
    title: "Verbal Relational Analogy",
    category: "Logic & Reasoning",
    subcategory: "Analogical Reasoning",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 15,
    cognitiveSkill: "Relational Mapping",
    instruction: "Find the concept that mirrors the primary relationship.",
    question: "OXYGEN is to RESPIRATION as FUEL is to :",
    options: [
      { id: "o1", label: "COMBUSTION", isCorrect: true },
      { id: "o2", label: "EXHAUST", isCorrect: false },
      { id: "o3", label: "ACCELERATOR", isCorrect: false },
      { id: "o4", label: "PETROLEUM", isCorrect: false },
    ],
    educationalWhy: "Verbal analogical mapping exercises relational reasoning and conceptual abstraction.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "log-06",
    title: "Categorical Syllogism Deductive Proof",
    category: "Logic & Reasoning",
    subcategory: "Deductive Logic",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 20,
    cognitiveSkill: "Formal Deductive Logic",
    instruction: "Evaluate the formal premises and determine the only valid deduction.",
    question: "Premise 1: All planets orbit a star. Premise 2: Kepler-22b is a planet. Conclusion:",
    options: [
      { id: "o1", label: "Kepler-22b orbits a star.", isCorrect: true },
      { id: "o2", label: "Kepler-22b is a star.", isCorrect: false },
      { id: "o3", label: "All stars are planets.", isCorrect: false },
      { id: "o4", label: "Kepler-22b does not orbit anything.", isCorrect: false },
    ],
    educationalWhy: "Formal syllogistic reasoning enforces strict adherence to valid deduction rules.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "log-07",
    title: "Odd One Out: Planetary Physics",
    category: "Logic & Reasoning",
    subcategory: "Classification & Anomaly",
    difficulty: "beginner",
    type: "pattern_recognition",
    estimatedTimeSec: 15,
    cognitiveSkill: "Taxonomic Classification",
    instruction: "Which item does NOT belong to the group?",
    question: "Identify the outlier: Mercury,  Venus,  Jupiter,  Pluto,  Mars",
    options: [
      { id: "o1", label: "Jupiter (Gas Giant; all others are rocky/dwarf bodies)", isCorrect: true },
      { id: "o2", label: "Mercury", isCorrect: false },
      { id: "o3", label: "Venus", isCorrect: false },
      { id: "o4", label: "Mars", isCorrect: false },
    ],
    educationalWhy: "Category boundary testing trains granular cognitive taxonomy.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "log-08",
    title: "Alternating Difference Arithmetic",
    category: "Logic & Reasoning",
    subcategory: "Variable Operations",
    difficulty: "advanced",
    type: "pattern_recognition",
    estimatedTimeSec: 20,
    cognitiveSkill: "Multi-Rule Series Deduction",
    instruction: "Identify the dual-operation sequence: (+3, -1, +3, -1...)",
    question: "What comes next: 10,  13,  12,  15,  14,  17,  ?",
    options: [
      { id: "o1", label: "16", isCorrect: true },
      { id: "o2", label: "20", isCorrect: false },
      { id: "o3", label: "18", isCorrect: false },
      { id: "o4", label: "19", isCorrect: false },
    ],
    educationalWhy: "Alternating dual-rule tracking exercises working memory updating under cognitive load.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "log-09",
    title: "The Truth-Teller Island Riddle",
    category: "Logic & Reasoning",
    subcategory: "Conditional Logic",
    difficulty: "expert",
    type: "pattern_recognition",
    estimatedTimeSec: 25,
    cognitiveSkill: "Boolean Logical Inversion",
    instruction: "A knight always tells the truth; a knave always lies.",
    question: "Person A says: 'Both of us are knaves.' What is Person A?",
    options: [
      { id: "o1", label: "A is a Knave (and the other person is a Knight)", isCorrect: true },
      { id: "o2", label: "A is a Knight", isCorrect: false },
      { id: "o3", label: "Both are Knights", isCorrect: false },
      { id: "o4", label: "Impossible to determine", isCorrect: false },
    ],
    educationalWhy: "Self-referential paradox resolution trains recursive truth-table evaluation.",
    xpReward: 70,
    coinReward: 20,
  },
  {
    id: "log-10",
    title: "Square Number Progression",
    category: "Logic & Reasoning",
    subcategory: "Quadratic Progression",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 15,
    cognitiveSkill: "Quadratic Sequence Recognition",
    instruction: "Identify the sequence of perfect squares: 1², 2², 3², 4²...",
    question: "What number comes next: 1,  4,  9,  16,  25,  ?",
    options: [
      { id: "o1", label: "36 (6²)", isCorrect: true },
      { id: "o2", label: "30", isCorrect: false },
      { id: "o3", label: "49", isCorrect: false },
      { id: "o4", label: "32", isCorrect: false },
    ],
    educationalWhy: "Recognizing exponential power series improves numeric intuition.",
    xpReward: 50,
    coinReward: 12,
  },
];
