import { CognitiveChallenge } from "./types";

export const MEMORY_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "mem-01",
    title: "Expedition Gear Visual Grid",
    category: "Memory",
    subcategory: "Visual Working Memory",
    difficulty: "beginner",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Iconic Memory & Spatial Recall",
    instruction: "Study these 6 expedition items for 6 seconds. Remember what they are.",
    memorizeDurationSec: 6,
    memorizeItems: ["🎒 Backpack", "⚡ Lightning", "🎨 Palette", "🚀 Rocket", "💎 Diamond", "🧩 Puzzle"],
    question: "Which of these objects was NOT in the picture you just studied?",
    options: [
      { id: "o1", label: "🎸 Guitar", isCorrect: true },
      { id: "o2", label: "🚀 Rocket", isCorrect: false },
      { id: "o3", label: "💎 Diamond", isCorrect: false },
      { id: "o4", label: "🎒 Backpack", isCorrect: false },
    ],
    educationalWhy: "The guitar was not in the original grid. Your visual cortex rapidly stores spatial arrangements in working memory for up to 10 seconds.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "mem-02",
    title: "Nature Vault Recall",
    category: "Memory",
    subcategory: "Categorical Recall",
    difficulty: "beginner",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Semantic Clustering",
    instruction: "Memorize these 6 nature elements in 6 seconds.",
    memorizeDurationSec: 6,
    memorizeItems: ["🌲 Pine Tree", "🌊 Ocean Wave", "🏔️ Mountain", "🦊 Red Fox", "🍄 Wild Mushroom", "🦅 Golden Eagle"],
    question: "Which creature or element was NOT shown?",
    options: [
      { id: "o1", label: "🦁 Lion", isCorrect: true },
      { id: "o2", label: "🦊 Red Fox", isCorrect: false },
      { id: "o3", label: "🌲 Pine Tree", isCorrect: false },
      { id: "o4", label: "🦅 Golden Eagle", isCorrect: false },
    ],
    educationalWhy: "Categorical visual clustering helps memory recall by binding semantic tags to visual tokens in working memory.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "mem-03",
    title: "Galactic Cosmos Recall",
    category: "Memory",
    subcategory: "Spatial Token Recall",
    difficulty: "intermediate",
    type: "visual_memory",
    estimatedTimeSec: 18,
    cognitiveSkill: "Iconic Working Memory",
    instruction: "Memorize these 6 celestial tokens for 6 seconds.",
    memorizeDurationSec: 6,
    memorizeItems: ["🪐 Saturn", "☄️ Comet", "🛸 UFO", "🌕 Full Moon", "🔭 Telescope", "🛰️ Satellite"],
    question: "Which cosmic element was absent from the terminal?",
    options: [
      { id: "o1", label: "☀️ Sun", isCorrect: true },
      { id: "o2", label: "🪐 Saturn", isCorrect: false },
      { id: "o3", label: "☄️ Comet", isCorrect: false },
      { id: "o4", label: "🛸 UFO", isCorrect: false },
    ],
    educationalWhy: "Astronomical spatial mapping engages hippocampal place-cells for rapid position retrieval.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-04",
    title: "Dr. Marcus Expedition Story",
    category: "Memory",
    subcategory: "Episodic Story Memory",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 25,
    cognitiveSkill: "Narrative Binding & Detail Encoding",
    instruction: "Read and remember the details of this story for 10 seconds.",
    memorizeDurationSec: 10,
    memorizeStory: "Dr. Marcus left his office at 07:15 AM wearing a navy trench coat. He carried a silver briefcase containing 3 blue blueprints and boarded train #44 to Zurich.",
    question: "What color blueprints were inside Dr. Marcus's briefcase?",
    options: [
      { id: "o1", label: "Blue", isCorrect: true },
      { id: "o2", label: "Red", isCorrect: false },
      { id: "o3", label: "Green", isCorrect: false },
      { id: "o4", label: "Yellow", isCorrect: false },
    ],
    educationalWhy: "Episodic memory binds temporal anchors (7:15 AM), narrative agents, and attribute details in the hippocampus.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-05",
    title: "The Archaeologist's Vault",
    category: "Memory",
    subcategory: "Episodic Story Memory",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 25,
    cognitiveSkill: "Contextual Binding",
    instruction: "Memorize the artifacts cataloged during the dig.",
    memorizeDurationSec: 10,
    memorizeStory: "Elena uncovered 4 bronze coins, an obsidian dagger with a jade hilt, and an ancient scroll dated to 450 BCE in Chamber 7.",
    question: "What material was the hilt of the dagger made from?",
    options: [
      { id: "o1", label: "Jade", isCorrect: true },
      { id: "o2", label: "Gold", isCorrect: false },
      { id: "o3", label: "Ruby", isCorrect: false },
      { id: "o4", label: "Silver", isCorrect: false },
    ],
    educationalWhy: "Contextual feature binding tests precise episodic recall under time constraints.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-06",
    title: "Cyberpunk Terminal Recall",
    category: "Memory",
    subcategory: "Visual Working Memory",
    difficulty: "beginner",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Iconic Memory",
    instruction: "Memorize these 6 digital tokens for 6 seconds.",
    memorizeDurationSec: 6,
    memorizeItems: ["💻 Laptop", "🔐 Keypad", "🔋 Battery", "💾 Floppy Disk", "📡 Radar", "🕹️ Joystick"],
    question: "Which digital item was missing from the terminal?",
    options: [
      { id: "o1", label: "🎧 Headphones", isCorrect: true },
      { id: "o2", label: "💻 Laptop", isCorrect: false },
      { id: "o3", label: "🔋 Battery", isCorrect: false },
      { id: "o4", label: "💾 Floppy Disk", isCorrect: false },
    ],
    educationalWhy: "Feature-based visual grouping exercises working memory capacity limits.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "mem-07",
    title: "Flight Log 709",
    category: "Memory",
    subcategory: "Alphanumeric Recall",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Phonological Loop Encoding",
    instruction: "Read and remember the flight manifest for 10 seconds.",
    memorizeDurationSec: 10,
    memorizeStory: "Flight 709 departed Gate 14B carrying 184 passengers at 16:40. Captain Vance announced a flight altitude of 34,000 feet heading directly to Tokyo.",
    question: "Which Gate did Flight 709 depart from?",
    options: [
      { id: "o1", label: "Gate 14B", isCorrect: true },
      { id: "o2", label: "Gate 12A", isCorrect: false },
      { id: "o3", label: "Gate 8C", isCorrect: false },
      { id: "o4", label: "Gate 22D", isCorrect: false },
    ],
    educationalWhy: "Alpha-numeric tag retention tests short-term phonological loop encoding.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-08",
    title: "Chef's Secret Recipe",
    category: "Memory",
    subcategory: "Sequential Recall",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 25,
    cognitiveSkill: "Sequence Memory",
    instruction: "Remember the 4 secret ingredients in exact order.",
    memorizeDurationSec: 8,
    memorizeStory: "Chef Amara prepared the signature sauce using: 1. Smoked Paprika, 2. Truffle Oil, 3. Aged Garlic, and 4. Fresh Rosemary.",
    question: "What was the 3rd ingredient in Chef Amara's sauce?",
    options: [
      { id: "o1", label: "Aged Garlic", isCorrect: true },
      { id: "o2", label: "Truffle Oil", isCorrect: false },
      { id: "o3", label: "Smoked Paprika", isCorrect: false },
      { id: "o4", label: "Fresh Rosemary", isCorrect: false },
    ],
    educationalWhy: "Order-preserving ordinal working memory is crucial for step-by-step procedural execution.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-09",
    title: "Top-Right Spatial Quadrant",
    category: "Memory",
    subcategory: "Spatial Location Memory",
    difficulty: "intermediate",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Spatial Coordinate Memory",
    instruction: "Remember where each icon is positioned on the screen.",
    memorizeDurationSec: 6,
    memorizeItems: ["Top-Left: 🍎 Apple", "Top-Right: 🔑 Key", "Bottom-Left: 🚗 Car", "Bottom-Right: 👑 Crown"],
    question: "Which object was in the TOP-RIGHT corner?",
    options: [
      { id: "o1", label: "🔑 Key", isCorrect: true },
      { id: "o2", label: "🍎 Apple", isCorrect: false },
      { id: "o3", label: "👑 Crown", isCorrect: false },
      { id: "o4", label: "🚗 Car", isCorrect: false },
    ],
    educationalWhy: "Spatial coordinate binding uses the dorsal 'where' pathway in the parietal lobe.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-10",
    title: "Security Pin Matrix",
    category: "Memory",
    subcategory: "Numeric Chunking",
    difficulty: "advanced",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Working Memory Chunking",
    instruction: "Memorize the 6-digit security code in 5 seconds.",
    memorizeDurationSec: 5,
    memorizeStory: "Vault Passcode: 8 - 3 - 9 - 2 - 1 - 7",
    question: "What was the 4th digit of the passcode?",
    options: [
      { id: "o1", label: "2", isCorrect: true },
      { id: "o2", label: "9", isCorrect: false },
      { id: "o3", label: "3", isCorrect: false },
      { id: "o4", label: "1", isCorrect: false },
    ],
    educationalWhy: "Chunking numbers into paired triplets increases working memory bandwidth.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "mem-11",
    title: "Pharmacy Dispense Manifest",
    category: "Memory",
    subcategory: "Attribute Association",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 22,
    cognitiveSkill: "Associative Binding",
    instruction: "Remember which patient was prescribed which medicine.",
    memorizeDurationSec: 8,
    memorizeStory: "Patient Amina received Vitamin C (500mg), Patient Tunde received Zinc (50mg), and Patient Zainab received Magnesium (200mg).",
    question: "Which supplement was prescribed to Patient Tunde?",
    options: [
      { id: "o1", label: "Zinc (50mg)", isCorrect: true },
      { id: "o2", label: "Vitamin C (500mg)", isCorrect: false },
      { id: "o3", label: "Magnesium (200mg)", isCorrect: false },
      { id: "o4", label: "Iron (100mg)", isCorrect: false },
    ],
    educationalWhy: "Name-to-attribute associative pairing is a key marker of functional memory retention.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-12",
    title: "Vintage Car Colors",
    category: "Memory",
    subcategory: "Color-Object Pairing",
    difficulty: "beginner",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Feature Conjunction",
    instruction: "Memorize the colors of the vintage vehicles.",
    memorizeDurationSec: 6,
    memorizeItems: ["🔴 Red Sedan", "🟢 Green Convertible", "🔵 Blue Truck", "🟡 Yellow Taxi"],
    question: "What color was the Convertible?",
    options: [
      { id: "o1", label: "Green", isCorrect: true },
      { id: "o2", label: "Red", isCorrect: false },
      { id: "o3", label: "Blue", isCorrect: false },
      { id: "o4", label: "Yellow", isCorrect: false },
    ],
    educationalWhy: "Binding color attributes to semantic categories tests working memory fidelity.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "mem-13",
    title: "Conference Attendee Badges",
    category: "Memory",
    subcategory: "Name-Role Recall",
    difficulty: "advanced",
    type: "memory_recall",
    estimatedTimeSec: 25,
    cognitiveSkill: "Social Memory Encoding",
    instruction: "Memorize the titles of these 3 keynote speakers.",
    memorizeDurationSec: 8,
    memorizeStory: "Speaker Kwame: AI Architect from Accra; Speaker Mei: Neuroscientist from Taipei; Speaker Carlos: Roboticist from Santiago.",
    question: "What was Kwame's professional title?",
    options: [
      { id: "o1", label: "AI Architect", isCorrect: true },
      { id: "o2", label: "Neuroscientist", isCorrect: false },
      { id: "o3", label: "Roboticist", isCorrect: false },
      { id: "o4", label: "Quantum Physicist", isCorrect: false },
    ],
    educationalWhy: "Associating names, cities, and professional domains builds social working memory.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "mem-14",
    title: "Musical Symphony Layout",
    category: "Memory",
    subcategory: "Auditory-Spatial Recall",
    difficulty: "intermediate",
    type: "visual_memory",
    estimatedTimeSec: 18,
    cognitiveSkill: "Cross-Modal Memory",
    instruction: "Memorize the instrument orchestra lineup.",
    memorizeDurationSec: 6,
    memorizeItems: ["🎻 Violin", "🎺 Trumpet", "🥁 Drum", "🎷 Saxophone", "🎹 Piano"],
    question: "Which instrument was NOT in the ensemble?",
    options: [
      { id: "o1", label: "🎸 Electric Guitar", isCorrect: true },
      { id: "o2", label: "🎻 Violin", isCorrect: false },
      { id: "o3", label: "🎷 Saxophone", isCorrect: false },
      { id: "o4", label: "🎹 Piano", isCorrect: false },
    ],
    educationalWhy: "Category-specific visual filtering rapidly isolates intruders in short-term buffer.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-15",
    title: "Art Gallery Room Numbers",
    category: "Memory",
    subcategory: "Location Tagging",
    difficulty: "expert",
    type: "memory_recall",
    estimatedTimeSec: 25,
    cognitiveSkill: "Complex Multi-Tag Recall",
    instruction: "Remember the 3 paintings and their room numbers.",
    memorizeDurationSec: 10,
    memorizeStory: "'The Starry Dream' is in Room 102; 'The Golden Horizon' is in Room 204; 'The Whispering Forest' is in Room 308.",
    question: "Which room contains 'The Golden Horizon'?",
    options: [
      { id: "o1", label: "Room 204", isCorrect: true },
      { id: "o2", label: "Room 102", isCorrect: false },
      { id: "o3", label: "Room 308", isCorrect: false },
      { id: "o4", label: "Room 401", isCorrect: false },
    ],
    educationalWhy: "High-interference spatial pairing requires disciplined cognitive tag separation.",
    xpReward: 70,
    coinReward: 20,
  },
  {
    id: "mem-16",
    title: "Subway Metro Route Map",
    category: "Memory",
    subcategory: "Route Memory",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Sequential Topographical Memory",
    instruction: "Remember the 4 consecutive metro stops.",
    memorizeDurationSec: 8,
    memorizeStory: "Train Line Blue stops in order: Central Station → Marina Bay → Tech Park → Sunrise Terminal.",
    question: "What is the stop immediately AFTER Marina Bay?",
    options: [
      { id: "o1", label: "Tech Park", isCorrect: true },
      { id: "o2", label: "Sunrise Terminal", isCorrect: false },
      { id: "o3", label: "Central Station", isCorrect: false },
      { id: "o4", label: "Green Hill", isCorrect: false },
    ],
    educationalWhy: "Topographical sequencing exercises the parahippocampal place area.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-17",
    title: "Grocery Basket Audit",
    category: "Memory",
    subcategory: "Object Counting",
    difficulty: "beginner",
    type: "visual_memory",
    estimatedTimeSec: 15,
    cognitiveSkill: "Working Memory Capacity",
    instruction: "Memorize these 5 grocery items.",
    memorizeDurationSec: 5,
    memorizeItems: ["🥑 Avocado", "🍞 Sourdough Bread", "🥛 Almond Milk", "☕ Coffee Beans", "🍯 Raw Honey"],
    question: "Which item was NOT in the grocery basket?",
    options: [
      { id: "o1", label: "🧀 Cheddar Cheese", isCorrect: true },
      { id: "o2", label: "🥑 Avocado", isCorrect: false },
      { id: "o3", label: "🥛 Almond Milk", isCorrect: false },
      { id: "o4", label: "☕ Coffee Beans", isCorrect: false },
    ],
    educationalWhy: "Everyday item recall exercises pragmatic working memory retention.",
    xpReward: 45,
    coinReward: 10,
  },
  {
    id: "mem-18",
    title: "Emergency Broadcast Frequency",
    category: "Memory",
    subcategory: "Decimal Number Recall",
    difficulty: "advanced",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Precision Numeric Buffer",
    instruction: "Memorize the radio frequency.",
    memorizeDurationSec: 5,
    memorizeStory: "Emergency Radio Channel: 107.4 FM. Backup Signal: 94.8 FM.",
    question: "What was the PRIMARY Emergency Radio Frequency?",
    options: [
      { id: "o1", label: "107.4 FM", isCorrect: true },
      { id: "o2", label: "94.8 FM", isCorrect: false },
      { id: "o3", label: "104.7 FM", isCorrect: false },
      { id: "o4", label: "98.4 FM", isCorrect: false },
    ],
    educationalWhy: "Decimal digit retention prevents digit-transposition errors in critical tasks.",
    xpReward: 60,
    coinReward: 15,
  },
  {
    id: "mem-19",
    title: "Constellation Star Count",
    category: "Memory",
    subcategory: "Quantitative Memory",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Numerical Association",
    instruction: "Remember the star counts of each cluster.",
    memorizeDurationSec: 7,
    memorizeStory: "Orion Belt has 3 bright stars; Pleiades has 7 visible stars; Cassiopeia forms a 5-star crown.",
    question: "How many stars were noted in Cassiopeia?",
    options: [
      { id: "o1", label: "5 stars", isCorrect: true },
      { id: "o2", label: "3 stars", isCorrect: false },
      { id: "o3", label: "7 stars", isCorrect: false },
      { id: "o4", label: "9 stars", isCorrect: false },
    ],
    educationalWhy: "Semantic-quantitative binding strengthens mathematical working memory.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "mem-20",
    title: "Chemical Element Symbols",
    category: "Memory",
    subcategory: "Symbol Translation",
    difficulty: "intermediate",
    type: "memory_recall",
    estimatedTimeSec: 20,
    cognitiveSkill: "Associative Symbol Retrieval",
    instruction: "Remember the element test tube labels.",
    memorizeDurationSec: 7,
    memorizeStory: "Beaker 1: Au (Gold); Beaker 2: Ag (Silver); Beaker 3: Fe (Iron); Beaker 4: Cu (Copper).",
    question: "Which element was in Beaker 3?",
    options: [
      { id: "o1", label: "Fe (Iron)", isCorrect: true },
      { id: "o2", label: "Au (Gold)", isCorrect: false },
      { id: "o3", label: "Ag (Silver)", isCorrect: false },
      { id: "o4", label: "Cu (Copper)", isCorrect: false },
    ],
    educationalWhy: "Abstract symbol retrieval engages the left angular gyrus.",
    xpReward: 50,
    coinReward: 12,
  },
];
