import { CognitiveChallenge } from "./types";

export const SPEED_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "spd-01",
    title: "Directional Anomaly Reflex",
    category: "Reaction Speed",
    subcategory: "Optic Reflex",
    difficulty: "beginner",
    type: "reaction_speed",
    estimatedTimeSec: 10,
    cognitiveSkill: "Optic Nerve Speed & Discrimination",
    instruction: "Identify the directional anomaly as fast as possible.",
    question: "Which arrow is pointing in the OPPOSITE horizontal direction: ➡️  ➡️  ⬅️  ➡️ ?",
    options: [
      { id: "o1", label: "3rd Arrow (⬅️ Left)", isCorrect: true },
      { id: "o2", label: "1st Arrow (➡️ Right)", isCorrect: false },
      { id: "o3", label: "2nd Arrow (➡️ Right)", isCorrect: false },
      { id: "o4", label: "4th Arrow (➡️ Right)", isCorrect: false },
    ],
    educationalWhy: "Fast directional anomaly recognition tests optic nerve signal transmission to prefrontal motor areas.",
    xpReward: 40,
    coinReward: 10,
  },
  {
    id: "spd-02",
    title: "Color-Word Stroop Inhibition Reflex",
    category: "Reaction Speed",
    subcategory: "Inhibitory Speed",
    difficulty: "intermediate",
    type: "reaction_speed",
    estimatedTimeSec: 10,
    cognitiveSkill: "Prefrontal Inhibitory Control",
    instruction: "Suppress the urge to read the word. Name the physical font color.",
    question: "The word 'BLUE' is printed in RED font color. What is the physical FONT COLOR of the word?",
    options: [
      { id: "o1", label: "RED (Physical font ink color)", isCorrect: true },
      { id: "o2", label: "BLUE (Semantic word text)", isCorrect: false },
      { id: "o3", label: "GREEN (Secondary spectrum distractor)", isCorrect: false },
      { id: "o4", label: "YELLOW (High contrast distractor)", isCorrect: false },
    ],
    educationalWhy: "The Stroop Effect tests your anterior cingulate cortex's ability to suppress automatic reading in favor of raw color recognition.",
    xpReward: 50,
    coinReward: 12,
  },
  {
    id: "spd-03",
    title: "Rapid Magnitude Sprint",
    category: "Reaction Speed",
    subcategory: "Quantitative Estimation",
    difficulty: "intermediate",
    type: "speed_round",
    estimatedTimeSec: 12,
    cognitiveSkill: "Rapid Estimation Under Pressure",
    instruction: "Tap the mathematically largest value within 5 seconds.",
    question: "Which arithmetic expression equals the HIGHEST numerical value?",
    options: [
      { id: "o1", label: "9 × 8 (= 72)", isCorrect: true },
      { id: "o2", label: "12 × 5 (= 60)", isCorrect: false },
      { id: "o3", label: "7 × 9 (= 63)", isCorrect: false },
      { id: "o4", label: "8 × 8 (= 64)", isCorrect: false },
    ],
    educationalWhy: "Rapid arithmetic comparison exercises approximate number systems (ANS) in the intraparietal sulcus.",
    xpReward: 45,
    coinReward: 12,
  },
  {
    id: "spd-04",
    title: "Speed Anomaly Symbol Detection",
    category: "Reaction Speed",
    subcategory: "Visual Search Speed",
    difficulty: "intermediate",
    type: "reaction_speed",
    estimatedTimeSec: 12,
    cognitiveSkill: "Fast Visual Search & Pop-Out Effect",
    instruction: "Find the single letter hidden among identical distractors.",
    question: "Find the single letter 'E' hidden in this row: F  F  F  E  F  F",
    options: [
      { id: "o1", label: "4th position (Letter E)", isCorrect: true },
      { id: "o2", label: "2nd position (Letter F)", isCorrect: false },
      { id: "o3", label: "5th position (Letter F)", isCorrect: false },
      { id: "o4", label: "1st position (Letter F)", isCorrect: false },
    ],
    educationalWhy: "Visual feature search trains parallel optic processing, spotting structural feature deviations in milliseconds.",
    xpReward: 45,
    coinReward: 10,
  },
];
