import { CognitiveChallenge } from "./types";

export const SPEED_CHALLENGES: CognitiveChallenge[] = [
  {
    id: "spd-01",
    title: "Directional Anomaly Reflex",
    category: "Reaction Speed",
    subcategory: "Optic Reflex",
    difficulty: "beginner",
    type: "reaction_speed",
    estimatedTimeSec: 10,
    cognitiveSkill: "Optic Nerve Speed & Discrimination",
    instruction: "Identify the directional anomaly as fast as possible.",
    question: "Which arrow is pointing in the OPPOSITE direction: ➡️  ➡️  ⬅️  ➡️ ?",
    options: [
      { id: "o1", label: "3rd Arrow (⬅️ Left)", isCorrect: true },
      { id: "o2", label: "1st Arrow (➡️ Right)", isCorrect: false },
      { id: "o3", label: "2nd Arrow (➡️ Right)", isCorrect: false },
      { id: "o4", label: "4th Arrow (➡️ Right)", isCorrect: false },
    ],
    educationalWhy: "Fast directional anomaly recognition tests optic nerve signal transmission to prefrontal motor areas.",
    xpReward: 40,
    coinReward: 10,
  },
  {
    id: "spd-02",
    title: "Vertical Arrow Reflex",
    category: "Reaction Speed",
    subcategory: "Vertical Orientation",
    difficulty: "beginner",
    type: "reaction_speed",
    estimatedTimeSec: 10,
    cognitiveSkill: "Vertical Visual Tracking",
    instruction: "Identify the odd direction immediately.",
    question: "Which arrow is pointing in the OPPOSITE direction: ⬆️  ⬆️  ⬇️  ⬆️ ?",
    options: [
      { id: "o1", label: "3rd Arrow (⬇️ Down)", isCorrect: true },
      { id: "o2", label: "1st Arrow (⬆️ Up)", isCorrect: false },
      { id: "o3", label: "2nd Arrow (⬆️ Up)", isCorrect: false },
      { id: "o4", label: "4th Arrow (⬆️ Up)", isCorrect: false },
    ],
    educationalWhy: "Vertical orientation discrimination exercises superior colliculus coordination.",
    xpReward: 40,
    coinReward: 10,
  },
  {
    id: "spd-03",
    title: "Rapid Magnitude Sprint",
    category: "Reaction Speed",
    subcategory: "Quantitative Estimation",
    difficulty: "intermediate",
    type: "speed_round",
    estimatedTimeSec: 12,
    cognitiveSkill: "Rapid Estimation Under Pressure",
    instruction: "Tap the mathematically largest value within 5 seconds.",
    question: "Which expression equals the HIGHEST numerical value?",
    options: [
      { id: "o1", label: "9 × 8 (= 72)", isCorrect: true },
      { id: "o2", label: "12 × 5 (= 60)", isCorrect: false },
      { id: "o3", label: "7 × 9 (= 63)", isCorrect: false },
      { id: "o4", label: "8 × 8 (= 64)", isCorrect: false },
    ],
    educationalWhy: "Instant quantitative estimation prevents cognitive hesitation under pressure.",
    xpReward: 50,
    coinReward: 15,
  },
  {
    id: "spd-04",
    title: "Stroop Interference Velocity",
    category: "Reaction Speed",
    subcategory: "Inhibitory Speed",
    difficulty: "intermediate",
    type: "reaction_speed",
    estimatedTimeSec: 10,
    cognitiveSkill: "Inhibitory Control Velocity",
    instruction: "Identify the font ink color, suppressing the written word text!",
    question: "The word says 'BLUE' written in GREEN ink. What is the ink color?",
    options: [
      { id: "o1", label: "Green", isCorrect: true },
      { id: "o2", label: "Blue", isCorrect: false },
      { id: "o3", label: "Red", isCorrect: false },
      { id: "o4", label: "Yellow", isCorrect: false },
    ],
    educationalWhy: "Overcoming the Stroop effect at high speed trains anterior cingulate cortex response inhibition.",
    xpReward: 50,
    coinReward: 12,
  },
];
