import { CognitiveChallenge } from "./types";

export const WORKPLACE_FINANCE_CHALLENGES: CognitiveChallenge[] = [
  // ─── WORKPLACE NEGOTIATION & EXECUTIVE CLARITY ─────────────────────────────
  {
    id: "wf-neg-01",
    title: "High-Stakes Client Negotiation in Lagos",
    category: "Executive Decisions",
    subcategory: "Negotiation & Emotional Control",
    difficulty: "intermediate",
    type: "critical_scenario",
    estimatedTimeSec: 45,
    cognitiveSkill: "Cognitive Reappraisal & Strategic Anchoring",
    instruction: "Read the business scenario and select the most cognitively sound negotiation strategy.",
    question: "Tunde is negotiating a major supply contract in Victoria Island. The client suddenly offers 30% below cost, expecting an immediate emotional reaction. What is the most effective prefrontal executive response?",
    options: [
      {
        id: "opt-1",
        label: "Pause for 3 seconds of diaphragmatic breathing, then ask a calibrated open-ended question: 'How am I supposed to deliver quality at that price point?'",
        isCorrect: true,
        explanation: "Pausing inhibits the amygdala's fight-or-flight response, while open-ended 'How' questions force the counterpart's prefrontal cortex to solve your dilemma.",
      },
      {
        id: "opt-2",
        label: "Immediately counter with an aggressive price increase to show dominance and test their resolve.",
        isCorrect: false,
        explanation: "Aggressive countering triggers defensive threat responses in the counterpart, causing negotiations to stall.",
      },
      {
        id: "opt-3",
        label: "Accept the deal immediately out of fear of losing the relationship entirely.",
        isCorrect: false,
        explanation: "Accepting a loss-making deal harms business viability and signals low bargaining confidence.",
      },
      {
        id: "opt-4",
        label: "Walk out of the meeting room without saying a word to make them feel guilty.",
        isCorrect: false,
        explanation: "Abruptly leaving breaks rapport and terminates productive problem-solving dialogue.",
      },
    ],
    educationalWhy: "Neuroscience shows that taking a 3-second tactical pause prevents amygdala hijacking during high-stakes financial discussions.",
    xpReward: 40,
    coinReward: 15,
  },
  {
    id: "wf-fin-02",
    title: "Kingston SME Cash Flow & Inventory Optimization",
    category: "Logic & Reasoning",
    subcategory: "Financial Mental Math & Risk Analysis",
    difficulty: "intermediate",
    type: "pattern_recognition",
    estimatedTimeSec: 40,
    cognitiveSkill: "Numeric Working Memory & Working Capital Logic",
    instruction: "Calculate the optimal cash allocation under supply chain inflation.",
    question: "Maya manages a retail distribution hub in Kingston. Her monthly fixed overhead is $400,000 JMD. She has $1,200,000 JMD in cash. Supplier A offers a 15% bulk discount if paid upfront today ($600,000 JMD), but accounts receivable collections take 45 days. What is the safest mathematical decision?",
    options: [
      {
        id: "opt-1",
        label: "Reserve 2 full months of overhead ($800,000 JMD) and negotiate a partial bulk order with Supplier A for $400,000 JMD.",
        isCorrect: true,
        explanation: "Maintaining a 2-month operating liquidity buffer protects solvency during collection delays while still capturing partial volume savings.",
      },
      {
        id: "opt-2",
        label: "Spend $1,000,000 JMD on maximum inventory to maximize the discount, leaving only $200,000 JMD cash.",
        isCorrect: false,
        explanation: "Leaving only half a month of overhead creates an extreme insolvency risk if receivables are delayed.",
      },
      {
        id: "opt-3",
        label: "Reject all supplier discounts and keep 100% of money sitting idle in a non-interest checking account.",
        isCorrect: false,
        explanation: "Holding excess unallocated cash causes value erosion due to inflation without optimizing supplier terms.",
      },
      {
        id: "opt-4",
        label: "Take an emergency high-interest loan to buy double the inventory.",
        isCorrect: false,
        explanation: "High-interest debt increases fixed overhead and compounds cash flow risk.",
      },
    ],
    educationalWhy: "Working capital management requires dual-task cognitive evaluation of liquidity risk versus discount yield.",
    xpReward: 45,
    coinReward: 20,
  },
  {
    id: "wf-focus-03",
    title: "Deep Work in a Chaotic Open Office in Accra",
    category: "Focus & Attention",
    subcategory: "Auditory Filtering & Distraction Resilience",
    difficulty: "beginner",
    type: "focus_fire",
    estimatedTimeSec: 30,
    cognitiveSkill: "Top-Down Selective Attention & Sensory Gating",
    instruction: "Choose the scientifically proven focus preservation technique.",
    question: "Kwame is drafting an urgent proposal in an open office in Airport City, Accra. Coworkers are discussing football, phones are ringing, and email alerts are flashing. Which strategy most effectively gates auditory distraction in the temporal lobe?",
    options: [
      {
        id: "opt-1",
        label: "Put on headphones with brown noise or binaural 40Hz beats, full-screen the document, and set a visible '25-minute Deep Work' timer.",
        isCorrect: true,
        explanation: "Brown noise masks speech frequencies, reducing thalamic sensory interrupts, while a visible boundary deters social interruptions.",
      },
      {
        id: "opt-2",
        label: "Try to listen to the coworkers' conversation while typing to practice extreme multitasking.",
        isCorrect: false,
        explanation: "The human brain cannot process two verbal streams simultaneously; speech automatically invades phonological working memory.",
      },
      {
        id: "opt-3",
        label: "Turn up fast music with loud lyrics in a familiar language.",
        isCorrect: false,
        explanation: "Familiar lyrics compete directly with the verbal processing required for drafting proposals.",
      },
      {
        id: "opt-4",
        label: "Check email every 5 minutes to ensure no new emergencies arrive.",
        isCorrect: false,
        explanation: "Frequent checking creates continuous attention residue, fragmenting cognitive stamina.",
      },
    ],
    educationalWhy: "Masking human speech with continuous noise profiles eliminates involuntary linguistic processing in Wernicke's area.",
    xpReward: 35,
    coinReward: 15,
  },
  {
    id: "wf-lead-04",
    title: "Resolving Workplace Conflict Between Key Team Leads in Nairobi",
    category: "Emotional Intelligence",
    subcategory: "Empathy & Perspective Taking",
    difficulty: "intermediate",
    type: "critical_scenario",
    estimatedTimeSec: 45,
    cognitiveSkill: "Theory of Mind & Conflict De-escalation",
    instruction: "Identify the leadership approach that triggers the highest psychological safety and accountability.",
    question: "Amara leads an engineering team in Nairobi. Her lead developer and product manager are in a heated argument over launch timelines, blaming each other for delays. How should Amara structure the intervention meeting?",
    options: [
      {
        id: "opt-1",
        label: "Have each person state the shared project outcome first, then explain the other person's core constraint from their perspective before discussing solutions.",
        isCorrect: true,
        explanation: "Forced perspective-taking activates Theory of Mind circuits, breaking tribal 'us vs them' defensiveness.",
      },
      {
        id: "opt-2",
        label: "Publicly reprimand the developer in front of the team to show who has executive authority.",
        isCorrect: false,
        explanation: "Public humiliation destroys psychological safety and triggers chronic workplace disengagement.",
      },
      {
        id: "opt-3",
        label: "Pick a side immediately based on who has been at the company longer.",
        isCorrect: false,
        explanation: "Seniority bias ignores objective operational realities and creates resentment in high performers.",
      },
      {
        id: "opt-4",
        label: "Ignore the disagreement and hope they work it out naturally over time.",
        isCorrect: false,
        explanation: "Unresolved leadership conflicts compound, slowing down organizational momentum.",
      },
    ],
    educationalWhy: "Perspective-taking forces the ventromedial prefrontal cortex to model the other person's internal mental state.",
    xpReward: 40,
    coinReward: 20,
  },
  {
    id: "wf-fin-05",
    title: "Financial Impulse Control: The 48-Hour Delay Rule",
    category: "Executive Decisions",
    subcategory: "Impulse Control & Dopamine Gating",
    difficulty: "beginner",
    type: "critical_scenario",
    estimatedTimeSec: 35,
    cognitiveSkill: "Delayed Gratification & Prefrontal Gating",
    instruction: "Evaluate the neuroscience of consumer impulse buying.",
    question: "After receiving an unexpected bonus, David sees an expensive luxury watch online and feels a sudden intense urge to buy it immediately. What neurological mechanism explains why waiting 48 hours dramatically improves financial decision quality?",
    options: [
      {
        id: "opt-1",
        label: "The initial dopamine anticipation surge subsides after 48 hours, allowing rational prefrontal evaluation of true utility and long-term financial goals.",
        isCorrect: true,
        explanation: "Dopamine peaks during novelty anticipation; delaying purchase allows the striatum's craving signal to cool down to baseline.",
      },
      {
        id: "opt-2",
        label: "The price of the luxury item is guaranteed to drop in 48 hours.",
        isCorrect: false,
        explanation: "Waiting does not change merchant pricing; it resets internal cognitive and emotional evaluation.",
      },
      {
        id: "opt-3",
        label: "Human memory completely forgets desires that are more than two days old.",
        isCorrect: false,
        explanation: "Genuine needs are remembered; only superficial impulsive cravings decay rapidly.",
      },
      {
        id: "opt-4",
        label: "Banks automatically block transactions made within 24 hours of receiving a bonus.",
        isCorrect: false,
        explanation: "Financial discipline is an internal behavioral protocol, not an automated banking block.",
      },
    ],
    educationalWhy: "Applying a temporal friction buffer decouples emotional dopaminergic impulses from executive financial execution.",
    xpReward: 35,
    coinReward: 15,
  },
];
