export interface BrainQuestion {
  id: string;
  category: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  question: string;
  type: "multiple-choice" | "text-input";
  options?: string[];
  correctAnswer: string;
  explanation: string;
  hint?: string;
  xp: number;
  coins: number;
}

export const BRAIN_QUESTIONS: BrainQuestion[] = [
  // ═══════════════════════════════════════════
  // 🧠 MEMORY
  // ═══════════════════════════════════════════
  {
    id: "mem-1",
    category: "memory",
    difficulty: "beginner",
    question: "Your mama send you market: rice, beans, tomatoes, and pepper. Which one she NO send you buy?",
    type: "multiple-choice",
    options: ["Rice", "Beans", "Ogi", "Pepper"],
    correctAnswer: "Ogi",
    explanation: "Your mama never mention ogi! Na wetin you add yourself. Memory na about wetin you hear, not wetin you expect.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-2",
    category: "memory",
    difficulty: "beginner",
    question: "Look at this list for 10 seconds: mango, pepper, salt, oil. How many items dey the list?",
    type: "multiple-choice",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
    explanation: "4 items dey! Mango, pepper, salt, oil. You fit remember am if you chunk am — group the food items together.",
    hint: "Count am one by one.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-3",
    category: "memory",
    difficulty: "intermediate",
    question: "Which number come next for this sequence: 2, 4, 8, 16, ___?",
    type: "multiple-choice",
    options: ["24", "32", "30", "20"],
    correctAnswer: "32",
    explanation: "Every number dey double! 2×2=4, 4×2=8, 8×2=16, 16×2=32. Na geometric progression be that.",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-4",
    category: "memory",
    difficulty: "intermediate",
    question: "Your friend tell you say im number na 080-3456-7890. Without looking back, which 4 digits dey the middle?",
    type: "multiple-choice",
    options: ["3456", "7890", "0803", "5678"],
    correctAnswer: "3456",
    explanation: "3456 na the middle digits! When you dey remember number, try break am into chunks — na that be the secret.",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-5",
    category: "memory",
    difficulty: "advanced",
    question: "Which of these 5 words you no see: elephant, guitar, bicycle, volcano, refrigerator?",
    type: "multiple-choice",
    options: ["Volcano", "Bicycle", "Guitar", "All were shown"],
    correctAnswer: "All were shown",
    explanation: "Surprise! All 5 words dey for the list. Sometimes your brain go dey look for wetin no dey. Na trick question be that — double-check your memory!",
    xp: 22,
    coins: 8,
  },
  {
    id: "mem-6",
    category: "memory",
    difficulty: "beginner",
    question: "Wetin dey come after this pattern: 🔴🔵🔴🔵🔴___?",
    type: "multiple-choice",
    options: ["🔴", "🔵", "🟢", "🟡"],
    correctAnswer: "🔵",
    explanation: "Na alternating pattern — red, blue, red, blue, red... next na blue! Pattern recognition na one key aspect of memory.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-7",
    category: "memory",
    difficulty: "advanced",
    question: "You read this sentence: 'The big brown cat sat on the warm mat.' Which word be the longest for the sentence?",
    type: "multiple-choice",
    options: ["biggest", "sitting", "sentence", "warmest"],
    correctAnswer: "sentence",
    explanation: "'Sentence' na the longest word with 8 letters! Sometimes we dey focus on the meaning wey we forget to observe the words demselves.",
    xp: 22,
    coins: 8,
  },
  {
    id: "mem-8",
    category: "memory",
    difficulty: "beginner",
    question: "Close your eyes. How many windows dey your room right now?",
    type: "multiple-choice",
    options: ["1", "2", "3", "I need to check"],
    correctAnswer: "I need to check",
    explanation: "If you no sure, that na normal! Spatial memory dey improve with practice. Try study your environment more carefully today.",
    hint: "Look around your room well well before answering.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-9",
    category: "memory",
    difficulty: "intermediate",
    question: "Which of these foods NO appear for Nigerian jollof rice: tomato, onions, rice, pizza?",
    type: "multiple-choice",
    options: ["Tomato", "Onions", "Pizza", "Rice"],
    correctAnswer: "Pizza",
    explanation: "Pizza no dey inside jollof! You fit use context to help your memory — relate new info to things wey you sabi well well.",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-10",
    category: "memory",
    difficulty: "advanced",
    question: "Type these numbers from memory after reading once: 7, 2, 9, 5, 1",
    type: "text-input",
    correctAnswer: "72951",
    explanation: "Working memory challenge! You suppose remember the order. Try create a story: '7 kids found 951 naira' — stories dey help brain store better.",
    hint: "Try create a small story with the numbers.",
    xp: 25,
    coins: 10,
  },

  // ═══════════════════════════════════════════
  // 🎯 FOCUS
  // ═══════════════════════════════════════════
  {
    id: "foc-1",
    category: "focus",
    difficulty: "beginner",
    question: "How many letter 'e' dey for this word: 'experience'?",
    type: "multiple-choice",
    options: ["2", "3", "4", "5"],
    correctAnswer: "4",
    explanation: "E-X-P-E-R-I-E-N-C-E — four 'e' dey there! Close attention to detail na the foundation of focus.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-2",
    category: "focus",
    difficulty: "beginner",
    question: "Complete this proverb: 'The early bird catches the ___'?",
    type: "multiple-choice",
    options: ["Money", "Worm", "Bus", "Sleep"],
    correctAnswer: "Worm",
    explanation: "'The early bird catches the worm' — who dey wake early na im get advantage. Focus start with discipline!",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-3",
    category: "focus",
    difficulty: "intermediate",
    question: "Which color dey appear MOST for this sequence: 🔴🔵🟡🔴🔵🔴🟡🔴🔵🔴?",
    type: "multiple-choice",
    options: ["Red 🔴", "Blue 🔵", "Yellow 🟡", "Equal"],
    correctAnswer: "Red 🔴",
    explanation: "Red dey appear 5 times, Blue 3 times, Yellow 2 times. Careful observation na the key — your eyes suppose dey sharp!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-4",
    category: "focus",
    difficulty: "intermediate",
    question: "You dey for meeting. Your phone dey vibrate with message notifications. Wetin be the BEST thing to do?",
    type: "multiple-choice",
    options: [
      "Check phone quick quick",
      "Ignore am and focus on meeting",
      "Put phone for silent mode",
      "Both B and C"
    ],
    correctAnswer: "Both B and C",
    explanation: "Silent your phone AND focus — na the double move! Multitasking na brain enemy. Single-tasking na the boss move.",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-5",
    category: "focus",
    difficulty: "beginner",
    question: "Count backwards from 20 by 2s. Which number dey next after 14?",
    type: "multiple-choice",
    options: ["13", "12", "11", "10"],
    correctAnswer: "12",
    explanation: "20, 18, 16, 14, 12... Na pattern dey! When you dey focus, your brain fit track sequences better. Keep the focus flowing!",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-6",
    category: "focus",
    difficulty: "advanced",
    question: "Which word appear exactly TWICE for this list: cat, dog, cat, bird, dog, fish?",
    type: "multiple-choice",
    options: ["Cat only", "Dog only", "Cat and Dog", "Bird and Fish"],
    correctAnswer: "Cat and Dog",
    explanation: "Cat dey twice (position 1 and 3), Dog dey twice (position 2 and 5). Focused attention dey help you track wetin dey happen around you.",
    xp: 22,
    coins: 8,
  },
  {
    id: "foc-7",
    category: "focus",
    difficulty: "beginner",
    question: "How many seconds you think you fit focus on ONE thing without checking your phone?",
    type: "multiple-choice",
    options: ["Less than 30 seconds", "30-60 seconds", "1-5 minutes", "More than 5 minutes"],
    correctAnswer: "More than 5 minutes",
    explanation: "The average human attention span na about 8 seconds (less than goldfish!). But you fit train your brain to focus pass that. Practice makes perfect!",
    hint: "Be honest with yourself — the goal na improvement!",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-8",
    category: "focus",
    difficulty: "advanced",
    question: "Read this paragraph: 'Lagos traffic dey always bad on Monday mornings. But on Tuesdays, e dey sometimes okay.' What day traffic dey okay?",
    type: "multiple-choice",
    options: ["Monday", "Tuesday", "Wednesday", "The text no say"],
    correctAnswer: "Tuesday",
    explanation: "Tuesday traffic dey SOMETIMES okay — not always! Active listening na about picking the small details wey people dey miss.",
    xp: 22,
    coins: 8,
  },
  {
    id: "foc-9",
    category: "focus",
    difficulty: "intermediate",
    question: "Which of these activities dey HELP your focus pass the rest?",
    type: "multiple-choice",
    options: ["Scrolling TikTok", "Meditation", "Watching Nollywood", "Playing PS5"],
    correctAnswer: "Meditation",
    explanation: "Meditation na like gym for your brain! Even 5 minutes per day fit improve your attention span for real.",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-10",
    category: "focus",
    difficulty: "beginner",
    question: "Your friend dey talk to you but you dey look TV. Which one na multitasking?",
    type: "multiple-choice",
    options: [
      "Listening AND watching",
      "Just watching TV",
      "Just listening",
      "None of them"
    ],
    correctAnswer: "Listening AND watching",
    explanation: "When you dey try do two things at once, na multitasking. But research show say your brain actually dey switch fast-fast between the two — e never really dey do two things at once!",
    xp: 10,
    coins: 3,
  },

  // ═══════════════════════════════════════════
  // 💡 THINKING
  // ═══════════════════════════════════════════
  {
    id: "thk-1",
    category: "thinking",
    difficulty: "beginner",
    question: "You get 5 oranges. You give your friend 2. How many you get left?",
    type: "multiple-choice",
    options: ["2", "3", "4", "5"],
    correctAnswer: "3",
    explanation: "5 - 2 = 3! Basic math na the foundation of critical thinking. Every big problem na small maths put together.",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-2",
    category: "thinking",
    difficulty: "beginner",
    question: "If today na Monday, which day go come after 3 days?",
    type: "multiple-choice",
    options: ["Wednesday", "Thursday", "Friday", "Tuesday"],
    correctAnswer: "Thursday",
    explanation: "Monday + 1 = Tuesday, + 2 = Wednesday, + 3 = Thursday. Time reasoning na important skill — you suppose fit calculate time for your head!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-3",
    category: "thinking",
    difficulty: "intermediate",
    question: "A farmer get 17 sheep. All except 9 die. How many sheep remain?",
    type: "multiple-choice",
    options: ["8", "9", "17", "26"],
    correctAnswer: "9",
    explanation: "'All EXCEPT 9' mean say 9 still dey alive! Na wordplay be that — always read question well well before you answer.",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-4",
    category: "thinking",
    difficulty: "intermediate",
    question: "Wetin be the difference between 'fact' and 'opinion': 'Suya na the best food for Nigeria'?",
    type: "multiple-choice",
    options: ["Na fact", "Na opinion", "Na both", "Na neither"],
    correctAnswer: "Na opinion",
    explanation: "E no be fact because 'best' na subjective — different people get different taste! Learning to separate fact from opinion na key thinking skill.",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-5",
    category: "thinking",
    difficulty: "advanced",
    question: "If all cats love fish and Tunde be cat, wetin Tunde love?",
    type: "multiple-choice",
    options: ["Meat", "Fish", "Milk", "We no know"],
    correctAnswer: "Fish",
    explanation: "All cats love fish + Tunde be cat = Tunde love fish! Na logical deduction be that — premises lead to conclusion.",
    xp: 22,
    coins: 8,
  },
  {
    id: "thk-6",
    category: "thinking",
    difficulty: "beginner",
    question: "A bottle of water cost N200. You get N500. How much change you go get?",
    type: "multiple-choice",
    options: ["N200", "N300", "N500", "N700"],
    correctAnswer: "N300",
    explanation: "500 - 200 = 300! Quick mental math dey help you for market and everywhere for life.",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-7",
    category: "thinking",
    difficulty: "advanced",
    question: "You dey inside dark room. You get one match, one candle, and one lantern. Which one you light first?",
    type: "multiple-choice",
    options: ["Candle", "Lantern", "Match", "None"],
    correctAnswer: "Match",
    explanation: "You must light the MATCH first before you fit light anything else! Na trick question — critical thinking mean say you dey think step by step.",
    xp: 22,
    coins: 8,
  },
  {
    id: "thk-8",
    category: "thinking",
    difficulty: "intermediate",
    question: "Which word be the OPPOSITE of 'plenty'?",
    type: "multiple-choice",
    options: ["Many", "Small", "Enough", "Too much"],
    correctAnswer: "Small",
    explanation: "Plenty mean 'a lot' — the opposite na 'small' or 'few'. Vocabulary dey help your thinking because better words = better thoughts.",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-9",
    category: "thinking",
    difficulty: "advanced",
    question: "If you dey go from Lagos to Abuja and you don pass Ibadan, how many states you don enter?",
    type: "multiple-choice",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
    explanation: "Lagos to Ibadan = enter Oyo State. Ibadan to Abuja pass through Oyo, Ogun, or other states. But you definitely don enter at least 2 states! Geography + logic dey work together.",
    xp: 22,
    coins: 8,
  },
  {
    id: "thk-10",
    category: "thinking",
    difficulty: "beginner",
    question: "You get 3 siblings. Each of them get 2 legs. How many legs your siblings get in total?",
    type: "multiple-choice",
    options: ["4", "6", "8", "10"],
    correctAnswer: "8",
    explanation: "3 siblings × 2 legs each = 8 legs! Multiplication na your friend. Every big problem you fit break am down to small maths.",
    xp: 10,
    coins: 3,
  },

  // ═══════════════════════════════════════════
  // 📚 LEARNING
  // ═══════════════════════════════════════════
  {
    id: "lrn-1",
    category: "learning",
    difficulty: "beginner",
    question: "Wetin be the capital of Nigeria?",
    type: "multiple-choice",
    options: ["Lagos", "Abuja", "Kano", "Port Harcourt"],
    correctAnswer: "Abuja",
    explanation: "Abuja na the capital since 1991! Lagos na the biggest city, but Abuja be the seat of government. You sabi your country?",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-2",
    category: "learning",
    difficulty: "beginner",
    question: "How many continents dey for the world?",
    type: "multiple-choice",
    options: ["5", "6", "7", "8"],
    correctAnswer: "7",
    explanation: "7 continents: Africa, Asia, Europe, North America, South America, Antarctica, and Oceania. Africa na the second largest! Be proud of your roots.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-3",
    category: "learning",
    difficulty: "intermediate",
    question: "What year Nigeria get independence from Britain?",
    type: "multiple-choice",
    options: ["1957", "1960", "1963", "1970"],
    correctAnswer: "1960",
    explanation: "October 1, 1960! That's why we dey celebrate Independence Day every year. Know your history na power.",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-4",
    category: "learning",
    difficulty: "intermediate",
    question: "Which gas we human dey breathe in?",
    type: "multiple-choice",
    options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"],
    correctAnswer: "Oxygen",
    explanation: "We dey breathe in oxygen and breathe out carbon dioxide. Basic biology — your brain dey use about 20% of all the oxygen wey you breathe!",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-5",
    category: "learning",
    difficulty: "advanced",
    question: "How many bones dey the adult human body?",
    type: "multiple-choice",
    options: ["106", "206", "306", "406"],
    correctAnswer: "206",
    explanation: "206 bones! Babies get about 270 but some dey join together as dem grow. Your body na engineering marvel!",
    xp: 22,
    coins: 8,
  },
  {
    id: "lrn-6",
    category: "learning",
    difficulty: "beginner",
    question: "Which ocean be the biggest for the world?",
    type: "multiple-choice",
    options: ["Atlantic", "Indian", "Pacific", "Arctic"],
    correctAnswer: "Pacific",
    explanation: "Pacific Ocean na the biggest — e cover more ground than all the land for the world combined! Science knowledge dey expand your thinking.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-7",
    category: "learning",
    difficulty: "advanced",
    question: "Who be the first president of independent Nigeria?",
    type: "multiple-choice",
    options: ["Yakubu Gowon", "Nnamdi Azikiwe", "Obafemi Awolowo", "Ahmadu Bello"],
    correctAnswer: "Nnamdi Azikiwe",
    explanation: "Dr. Nnamdi Azikiwe na the first President of Nigeria (ceremonial role, 1963-1966). Tafawa Balewa na the first Prime Minister. History na important!",
    xp: 22,
    coins: 8,
  },
  {
    id: "lrn-8",
    category: "learning",
    difficulty: "intermediate",
    question: "Wetin 'ubiquitous' mean? E dey used to describe something wey dey everywhere.",
    type: "multiple-choice",
    options: ["Very expensive", "Found everywhere", "Very old", "Extremely rare"],
    correctAnswer: "Found everywhere",
    explanation: "Ubiquitous mean 'dey everywhere at once'. Like phone — phone don become ubiquitous for Nigeria! Big vocabulary = big brain.",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-9",
    category: "learning",
    difficulty: "beginner",
    question: "Which language dey speak pass for the world?",
    type: "multiple-choice",
    options: ["English", "Spanish", "Mandarin Chinese", "Hindi"],
    correctAnswer: "Mandarin Chinese",
    explanation: "Over 1 billion people dey speak Mandarin! But English na the most widely spoken for business. Learning new languages dey boost your brain.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-10",
    category: "learning",
    difficulty: "advanced",
    question: "The human brain weigh approximately how much?",
    type: "multiple-choice",
    options: ["About 1 kg (2.2 lbs)", "About 3 kg (6.6 lbs)", "About 5 kg (11 lbs)", "About 8 kg (17.6 lbs)"],
    correctAnswer: "About 1 kg (2.2 lbs)",
    explanation: "Your brain weigh about 1.4 kg — less than 3 pounds! Small but mighty. E dey use 20% of your body's energy even though e be just 2% of your weight.",
    xp: 22,
    coins: 8,
  },

  // ═══════════════════════════════════════════
  // ❤️ HEALTH
  // ═══════════════════════════════════════════
  {
    id: "hlth-1",
    category: "health",
    difficulty: "beginner",
    question: "How many hours of sleep adult suppose get per night?",
    type: "multiple-choice",
    options: ["4-5 hours", "5-6 hours", "7-9 hours", "10-12 hours"],
    correctAnswer: "7-9 hours",
    explanation: "7-9 hours na the sweet spot! When you dey sleep, your brain dey clean itself and store your memories. Sleep na brain food!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-2",
    category: "health",
    difficulty: "beginner",
    question: "How many glasses of water you suppose drink per day (approximately)?",
    type: "multiple-choice",
    options: ["2-3", "4-5", "6-8", "12-15"],
    correctAnswer: "6-8",
    explanation: "6-8 glasses na the general rule! Your brain na about 75% water — when you dey dehydrated, your focus go drop sharp sharp.",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-3",
    category: "health",
    difficulty: "intermediate",
    question: "Which of these foods dey GOOD for your brain?",
    type: "multiple-choice",
    options: ["Junk food", "Fish (like salmon)", "Sugary drinks", "Chin Chin"],
    correctAnswer: "Fish (like salmon)",
    explanation: "Fish get omega-3 fatty acids wey your brain dey need to function well. Other brain food: eggs, nuts, berries, and dark chocolate! Your brain dey pay you back when you feed am well.",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-4",
    category: "health",
    difficulty: "beginner",
    question: "Wetin dey happen to your brain when you exercise?",
    type: "multiple-choice",
    options: ["E dey shrink", "E dey grow and get stronger", "Nothing", "E dey get tired"],
    correctAnswer: "E dey grow and get stronger",
    explanation: "Exercise dey increase blood flow to your brain and even help create new brain cells! Even 20 minutes of walking fit boost your thinking.",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-5",
    category: "health",
    difficulty: "intermediate",
    question: "How long you suppose take screen break according to the 20-20-20 rule?",
    type: "multiple-choice",
    options: [
      "Every 20 minutes, look 20 feet away for 20 seconds",
      "Every 20 hours, close phone for 20 minutes",
      "Every 2 days, rest for 20 hours",
      "There's no such rule"
    ],
    correctAnswer: "Every 20 minutes, look 20 feet away for 20 seconds",
    explanation: "The 20-20-20 rule! Every 20 minutes, look at something 20 feet away for 20 seconds. Your eyes and brain go thank you!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-6",
    category: "health",
    difficulty: "advanced",
    question: "Wetin be 'brain fog'?",
    type: "multiple-choice",
    options: [
      "A weather condition",
      "Confusion, forgetfulness, lack of focus",
      "A type of headache",
      "When your brain dey hot"
    ],
    correctAnswer: "Confusion, forgetfulness, lack of focus",
    explanation: "Brain fog na when your brain dey feel like say e no dey work well — confusion, forgetfulness, and lack of focus. Common causes: poor sleep, stress, dehydration, and poor diet.",
    xp: 22,
    coins: 8,
  },
  {
    id: "hlth-7",
    category: "health",
    difficulty: "beginner",
    question: "Which of these dey CAUSE brain fog?",
    type: "multiple-choice",
    options: ["Drinking water", "Lack of sleep", "Walking", "Reading books"],
    correctAnswer: "Lack of sleep",
    explanation: "Lack of sleep na one of the biggest cause of brain fog! Your brain dey clean and recharge when you sleep. No sleep = dirty, tired brain.",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-8",
    category: "health",
    difficulty: "intermediate",
    question: "Wetin be the benefit of meditation for your brain?",
    type: "multiple-choice",
    options: [
      "It makes you invisible",
      "It improves focus, reduces stress, and increases grey matter",
      "It makes you taller",
      "It gives you superpowers"
    ],
    correctAnswer: "It improves focus, reduces stress, and increases grey matter",
    explanation: "Meditation dey literally change your brain structure! Studies show say e dey increase grey matter for areas wey dey control focus, learning, and emotions. Even 10 minutes per day dey work!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-9",
    category: "health",
    difficulty: "advanced",
    question: "Which food get the MOST omega-3 fatty acids?",
    type: "multiple-choice",
    options: ["Apple", "Salmon (fish)", "Rice", "Bread"],
    correctAnswer: "Salmon (fish)",
    explanation: "Salmon na omega-3 king! Other sources: mackerel (kote), sardines, walnuts, and flaxseed. Omega-3 dey build your brain cells and keep e healthy.",
    xp: 22,
    coins: 8,
  },
  {
    id: "hlth-10",
    category: "health",
    difficulty: "beginner",
    question: "When you dey stressed, wetin dey happen to your body?",
    type: "multiple-choice",
    options: [
      "You dey feel happy",
      "Your body dey release cortisol — heart beat fast, muscles tense",
      "Nothing dey happen",
      "You dey lose weight"
    ],
    correctAnswer: "Your body dey release cortisol — heart beat fast, muscles tense",
    explanation: "Stress dey release cortisol, wey dey prepare your body to 'fight or flee'. Small stress dey help, but chronic stress dey damage your brain over time. Exercise, sleep, and meditation dey help manage am.",
    xp: 10,
    coins: 3,
  },

  // ═══════════════════════════════════════════
  // 🎨 CREATIVITY
  // ═══════════════════════════════════════════
  {
    id: "cre-1",
    category: "creativity",
    difficulty: "beginner",
    question: "How many uses you fit find for a rubber band?",
    type: "multiple-choice",
    options: ["Only 1", "2-3", "5+", "10+"],
    correctAnswer: "10+",
    explanation: "Rubber band fit do PLENTY things: hair tie, money holder, book marker, game prop, phone grip, and more! Divergent thinking na the engine of creativity.",
    xp: 10,
    coins: 3,
  },
  {
    id: "cre-2",
    category: "creativity",
    difficulty: "beginner",
    question: "If rain dey fall heavy and you no get umbrella, which of these be the MOST creative solution?",
    type: "multiple-choice",
    options: [
      "Wait inside shop",
      "Use newspaper cover your head",
      "Swim through the rain",
      "Both B and creative alternatives!"
    ],
    correctAnswer: "Both B and creative alternatives!",
    explanation: "Sometimes the most creative solution na to combine ideas! Use newspaper, plastic bag, or even banana leaf. Creativity na about resourcefulness.",
    xp: 10,
    coins: 3,
  },
  {
    id: "cre-3",
    category: "creativity",
    difficulty: "intermediate",
    question: "If color dey fit talk, wetin you think GREEN go say?",
    type: "multiple-choice",
    options: [
      "'I be traffic light'",
      "'I be nature, peace, and fresh beginning'",
      "'I be money'",
      "'I be boring'"
    ],
    correctAnswer: "'I be nature, peace, and fresh beginning'",
    explanation: "Green dey symbolize nature, growth, and peace! Different people go see different meanings — that's the beauty of abstract thinking. Creativity dey thrive for ambiguity!",
    xp: 15,
    coins: 5,
  },
  {
    id: "cre-4",
    category: "creativity",
    difficulty: "intermediate",
    question: "Which word NO dey belong: mango, orange, banana, potato, pawpaw?",
    type: "multiple-choice",
    options: ["Mango", "Orange", "Potato", "Pawpaw"],
    correctAnswer: "Potato",
    explanation: "Potato na vegetable — the others all be fruits! Creative people dey notice patterns wey others dey miss. Classification be a creativity exercise!",
    xp: 15,
    coins: 5,
  },
  {
    id: "cre-5",
    category: "creativity",
    difficulty: "advanced",
    question: "SCAMPER na creativity technique. The 'S' stand for which of these?",
    type: "multiple-choice",
    options: ["Solve", "Substitute", "Simplify", "Start"],
    correctAnswer: "Substitute",
    explanation: "SCAMPER: Substitute, Combine, Adapt, Modify, Put to other use, Eliminate, Reverse. It's a structured way to think creatively about existing things!",
    xp: 22,
    coins: 8,
  },
  {
    id: "cre-6",
    category: "creativity",
    difficulty: "beginner",
    question: "You fit use bottle do which of these, aside drink?",
    type: "multiple-choice",
    options: [
      "Flower vase",
      "Watering can",
      "Musical instrument",
      "All of the above"
    ],
    correctAnswer: "All of the above",
    explanation: "Bottle fit be flower vase, watering can, shaker instrument, storage container, and more! 'Alternate Uses' na one of the best creativity exercises. Try am now — how many uses you fit find?",
    xp: 10,
    coins: 3,
  },
  {
    id: "cre-7",
    category: "creativity",
    difficulty: "advanced",
    question: "Which shape be MOST associated with creative thinking?",
    type: "multiple-choice",
    options: ["Square (structured)", "Circle (free-flowing)", "Triangle (directional)", "Squiggly line (unstructured)"],
    correctAnswer: "Squiggly line (unstructured)",
    explanation: "Squiggly lines dey represent free, unstructured thinking! When you dey brainstorm, try drawing squiggly lines instead of straight ones — research show say this dey boost creative output.",
    xp: 22,
    coins: 8,
  },
  {
    id: "cre-8",
    category: "creativity",
    difficulty: "intermediate",
    question: "Reverse brainstorming na: you brainstorm ways to make a problem WORSE, then reverse am. Wetin be the benefit?",
    type: "multiple-choice",
    options: [
      "You dey waste time",
      "E dey reveal solutions wey you for no think about",
      "E dey make you sad",
      "E no dey work"
    ],
    correctAnswer: "E dey reveal solutions wey you for no think about",
    explanation: "When you think about wetin dey cause the problem, you fit identify solutions from the opposite direction! Creativity na about looking things from different angles.",
    xp: 15,
    coins: 5,
  },
  {
    id: "cre-9",
    category: "creativity",
    difficulty: "beginner",
    question: "Wetin you fit use describe Lagos traffic using ONLY emojis?",
    type: "multiple-choice",
    options: [
      "🚗🚗🚗😤⏱️😭",
      "🌅✨🎵😌",
      "📚💡🧠✅",
      "🏃💨🌊🏊"
    ],
    correctAnswer: "🚗🚗🚗😤⏱️😭",
    explanation: "Cars, anger, time waste, and tears — Lagos traffic in a nutshell! Creative expression dey help your brain make new connections between ideas.",
    xp: 10,
    coins: 3,
  },
  {
    id: "cre-10",
    category: "creativity",
    difficulty: "advanced",
    question: "A haiku be a 3-line poem with 5-7-5 syllables. Which of these be a correct haiku?",
    type: "multiple-choice",
    options: [
      "Jollof rice so hot / Party jollof best of all / Stomach dey full well",
      "The sun is very hot today and it is bright",
      "Roses are red, violets are blue",
      "To be or not to be"
    ],
    correctAnswer: "Jollof rice so hot / Party jollof best of all / Stomach dey full well",
    explanation: "Jollof rice so hot (5) / Party jollof best of all (7) / Stomach dey full well (5) — that's a perfect haiku with Nigerian flair! Creative constraints dey force your brain to think differently.",
    xp: 22,
    coins: 8,
  },

  // ═══════════════════════════════════════════
  // 🤝 EMOTIONAL INTELLIGENCE
  // ═══════════════════════════════════════════
  {
    id: "eq-1",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Your friend dey cry. Wetin be the FIRST thing you suppose do?",
    type: "multiple-choice",
    options: [
      "Tell am to stop crying",
      "Ask wetin happen and listen",
      "Post am for social media",
      "Ignore am"
    ],
    correctAnswer: "Ask wetin happen and listen",
    explanation: "Empathy start with listening! Before you give advice or try to fix anything, first understand wetin the person dey feel. Active listening na superpower.",
    xp: 10,
    coins: 3,
  },
  {
    id: "eq-2",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "You dey vex because your friend late for 30 minutes. Wetin be the BEST response?",
    type: "multiple-choice",
    options: [
      "Shout at am for the whole world to hear",
      "Pause, breathe, then talk about am calmly",
      "Never talk to am again",
      "Post shady status about am"
    ],
    correctAnswer: "Pause, breathe, then talk about am calmly",
    explanation: "Reactive vs. Responsive — the pause dey make the difference! When you dey angry, your amygdala (emotional brain) dey control you. When you pause, your prefrontal cortex (thinking brain) fit take over.",
    xp: 10,
    coins: 3,
  },
  {
    id: "eq-3",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Your colleague dey always dey quiet for meetings. Which emotion fit dey hiding there?",
    type: "multiple-choice",
    options: [
      "Arrogance",
      "Shyness, insecurity, or feeling unheard",
      "Laziness",
      "Nothing"
    ],
    correctAnswer: "Shyness, insecurity, or feeling unheard",
    explanation: "Quiet people no be rude — dem fit dey shy, insecure, or feel say wetin dem go talk no go matter. Social awareness mean say you dey consider other people's feelings, not just wetin you see.",
    xp: 15,
    coins: 5,
  },
  {
    id: "eq-4",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "You dey argue with your partner. Wetin be the most productive thing to do?",
    type: "multiple-choice",
    options: [
      "Raise your voice pass im own",
      "Walk out without saying anything",
      "Take a break, then come back to discuss calmly",
      "Bring up old grudges"
    ],
    correctAnswer: "Take a break, then come back to discuss calmly",
    explanation: "When emotions dey high, your thinking brain dey shut down! Take a break (but promise to come back), then discuss like adults. Conflict resolution na skill wey you fit learn.",
    xp: 15,
    coins: 5,
  },
  {
    id: "eq-5",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "Nonviolent Communication (NVC) get 4 steps. Which one dey come LAST?",
    type: "multiple-choice",
    options: [
      "Observation (wetin you see)",
      "Feeling (wetin you dey feel)",
      "Need (wetin you need)",
      "Request (wetin you want)"
    ],
    correctAnswer: "Request (wetin you want)",
    explanation: "NVC: Observation → Feeling → Need → Request. Example: 'When you come late (observation), I dey feel worried (feeling) because I need reliability (need). You fit call me next time? (request)'. Powerful stuff!",
    xp: 22,
    coins: 8,
  },
  {
    id: "eq-6",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Which of these dey show RESPECT for another person?",
    type: "multiple-choice",
    options: [
      "Interrupting when dem dey talk",
      "Looking at your phone while dem dey talk",
      "Listening without interrupting",
      "Telling dem wetin to do"
    ],
    correctAnswer: "Listening without interrupting",
    explanation: "Active listening na one of the biggest signs of respect! When you dey listen, you dey show say the person's words matter to you. That na the foundation of every good relationship.",
    xp: 10,
    coins: 3,
  },
  {
    id: "eq-7",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "Your friend share good news: 'I just get promoted!' Which response dey show active constructive responding?",
    type: "multiple-choice",
    options: [
      "'Okay'",
      "'Nice! Tell me everything — how you feel? Wetin you go do to celebrate?'",
      "'I never get promoted before'",
      "'E go be hard for the new role'"
    ],
    correctAnswer: "'Nice! Tell me everything — how you feel? Wetin you go do to celebrate?'",
    explanation: "Active constructive responding mean you dey ENTHUSIASTICALLY engage with the good news! You dey ask questions, you dey celebrate with them. Research show say this na the #1 predictor of relationship quality.",
    xp: 22,
    coins: 8,
  },
  {
    id: "eq-8",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Wetin 'self-compassion' mean?",
    type: "multiple-choice",
    options: [
      "Beating yourself up when you make mistake",
      "Talking to yourself like you go talk to a friend",
      "Ignoring your mistakes",
      "Pretending everything dey okay"
    ],
    correctAnswer: "Talking to yourself like you go talk to a friend",
    explanation: "When you make mistake, talk to yourself the way you go talk to your best friend! 'It's okay, you go do better next time' — na that be self-compassion. Self-hatred never help anybody improve.",
    xp: 10,
    coins: 3,
  },
  {
    id: "eq-9",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Your family dey pressure you about marriage. Which emotional skill dey most important here?",
    type: "multiple-choice",
    options: [
      "Aggressive confrontation",
      "Emotional regulation and boundary setting",
      "Complete avoidance",
      "Doing whatever dem want"
    ],
    correctAnswer: "Emotional regulation and boundary setting",
    explanation: "You fit love your family AND set boundaries! 'I understand say you dey worry, but this na my decision and I need you to respect am.' Calm, clear, and respectful — na that be emotional maturity.",
    xp: 15,
    coins: 5,
  },
  {
    id: "eq-10",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "Cognitive reappraisal na: you change how you see a situation to change how you feel. If you fail exam, which be a reappraisal?",
    type: "multiple-choice",
    options: [
      "'I be useless person'",
      "'This na feedback on wetin I need to study more'",
      "'Exams be waste of time'",
      "'I go never pass'"
    ],
    correctAnswer: "'This na feedback on wetin I need to study more'",
    explanation: "Reappraisal no be pretending say e no pain — e be reframing! You dey see the situation differently so e fit motivate you instead of discourage you. This na one of the most powerful emotional skills wey exist.",
    xp: 22,
    coins: 8,
  },
];
