import { createClient } from "@supabase/supabase-js";
import "dotenv/config";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
  console.error("Missing Supabase environment variables");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey, {
  auth: { persistSession: false },
});

const categories = [
  {
    slug: "memory",
    name: "Memory",
    description: "Exercises to improve short-term and long-term memory",
    icon: "brain",
    color: "#6366f1",
    sort_order: 1,
  },
  {
    slug: "focus",
    name: "Focus",
    description: "Build deep concentration and reduce distractions",
    icon: "target",
    color: "#f59e0b",
    sort_order: 2,
  },
  {
    slug: "thinking",
    name: "Thinking",
    description: "Sharpen critical thinking and problem-solving skills",
    icon: "lightbulb",
    color: "#10b981",
    sort_order: 3,
  },
  {
    slug: "learning",
    name: "Learning",
    description: "Accelerate your ability to learn new skills",
    icon: "book",
    color: "#3b82f6",
    sort_order: 4,
  },
  {
    slug: "health",
    name: "Health",
    description: "Physical habits that support cognitive performance",
    icon: "heart",
    color: "#ef4444",
    sort_order: 5,
  },
  {
    slug: "creativity",
    name: "Creativity",
    description: "Unlock creative thinking and innovation",
    icon: "palette",
    color: "#ec4899",
    sort_order: 6,
  },
  {
    slug: "emotional-intelligence",
    name: "Emotional Intelligence",
    description: "Understand emotions and build better relationships",
    icon: "users",
    color: "#8b5cf6",
    sort_order: 7,
  },
];

interface ActivitySeed {
  title: string;
  description: string;
  difficulty: "beginner" | "intermediate" | "advanced";
  estimated_time: number;
  xp: number;
  coins: number;
  benefits: string[];
  instructions?: string;
  tips?: string;
}

const activitiesByCategory: Record<string, ActivitySeed[]> = {
  memory: [
    {
      title: "Free Recall",
      description: "After reading, close the book and write down everything you remember.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Strengthens memory retrieval", "Improves active recall"],
      instructions: "Read a short article or chapter, then write down all key points from memory.",
      tips: "Do this immediately after reading for maximum effect.",
    },
    {
      title: "Memory Palace",
      description: "Use a familiar location to memorize a list of items.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Enhances spatial memory", "Builds mnemonic skills"],
      instructions: "Visualize a familiar route and place items along it mentally.",
    },
    {
      title: "Name Recall Challenge",
      description: "Meet someone new and make a deliberate effort to remember their name.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 3,
      benefits: ["Improves social memory", "Builds connection habit"],
    },
    {
      title: "Story Method",
      description: "Create a story that links random items together to remember them.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Strengthens associative memory", "Boosts creativity"],
    },
    {
      title: "Reverse Timeline",
      description: "Recall your day in reverse chronological order.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Sharpens episodic memory", "Increases mindfulness"],
    },
    {
      title: "Number Mnemonics",
      description: "Convert numbers into words or images to remember them.",
      difficulty: "intermediate",
      estimated_time: 12,
      xp: 18,
      coins: 6,
      benefits: ["Improves number recall", "Teaches mnemonic systems"],
    },
    {
      title: "Photo Memory Drill",
      description: "Study an image for 30 seconds, then describe it in detail from memory.",
      difficulty: "advanced",
      estimated_time: 10,
      xp: 22,
      coins: 8,
      benefits: ["Enhances visual memory", "Increases attention to detail"],
    },
    {
      title: "Lyrics Recall",
      description: "Listen to a song and write down the lyrics from memory.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Trains auditory memory", "Fun and engaging"],
    },
    {
      title: "Grocery List Challenge",
      description: "Go shopping without a written list — use only your memory.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 5,
      benefits: ["Real-world memory training", "Practical skill building"],
    },
    {
      title: "Chunking Practice",
      description: "Break long strings of information into chunks.",
      difficulty: "beginner",
      estimated_time: 8,
      xp: 10,
      coins: 3,
      benefits: ["Improves working memory", "Enhances information processing"],
    },
    {
      title: "Flashcard Review",
      description: "Review flashcards for a topic you're learning.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Strengthens long-term memory", "Uses spaced repetition"],
    },
    {
      title: "Telephone Number Recall",
      description: "Memorize a phone number by repeating it in chunks throughout the day.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Everyday memory practice", "Easy to integrate"],
    },
    {
      title: "Visual Association",
      description: "Connect new information to vivid mental images.",
      difficulty: "intermediate",
      estimated_time: 12,
      xp: 18,
      coins: 6,
      benefits: ["Deepens encoding", "Makes information stick"],
    },
    {
      title: "Memory Competition",
      description: "Challenge a friend to a memory game — who can remember more items?",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 10,
      benefits: ["Social motivation", "Pressure training"],
    },
    {
      title: "Method of Loci",
      description: "Place items you want to remember along a familiar journey.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Ancient memory technique", "Highly effective"],
    },
    {
      title: "Card Recall",
      description: "Shuffle a deck of cards and try to recall the order after studying it.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 20,
      coins: 8,
      benefits: ["Visual memory", "Pattern recognition"],
    },
    {
      title: "Face-Name Matching",
      description: "Look at photos of strangers and match faces to names after 5 minutes.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Social memory", "Real-world skill"],
    },
    {
      title: "Shopping Receipt Recall",
      description: "Study a receipt for 2 minutes, then list every item from memory.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 12,
      coins: 4,
      benefits: ["Working memory", "Attention to detail"],
    },
    {
      title: "Memory Maze",
      description: "Study a simple maze for 1 minute, then draw it from memory.",
      difficulty: "advanced",
      estimated_time: 8,
      xp: 22,
      coins: 8,
      benefits: ["Spatial memory", "Visual reconstruction"],
    },
    {
      title: "Color-Number Association",
      description: "Memorize a list of color-number pairs, then recall them under time pressure.",
      difficulty: "intermediate",
      estimated_time: 8,
      xp: 16,
      coins: 6,
      benefits: ["Associative memory", "Speed recall"],
    },
    {
      title: "Daily Details Log",
      description: "At the end of the day, write down 10 specific details you noticed.",
      difficulty: "beginner",
      estimated_time: 8,
      xp: 10,
      coins: 3,
      benefits: ["Observational memory", "Mindfulness"],
    },
    {
      title: "Word List Battle",
      description: "Study 20 random words, then recall as many as possible in 2 minutes.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 12,
      coins: 4,
      benefits: ["Short-term memory", "Competitive fun"],
    },
    {
      title: "Music Interval Memory",
      description: "Listen to two musical notes and identify the interval between them.",
      difficulty: "advanced",
      estimated_time: 10,
      xp: 25,
      coins: 10,
      benefits: ["Auditory memory", "Ear training"],
    },
    {
      title: "3-Item Carry",
      description: "Keep 3 random items in your working memory all day without writing them down.",
      difficulty: "intermediate",
      estimated_time: 5,
      xp: 15,
      coins: 5,
      benefits: ["Working memory stamina", "Mental discipline"],
    },
  ],
  focus: [
    {
      title: "Pomodoro Session",
      description: "Work for 25 minutes, rest for 5. Repeat 4 times.",
      difficulty: "beginner",
      estimated_time: 25,
      xp: 20,
      coins: 8,
      benefits: ["Builds focus endurance", "Prevents burnout"],
      instructions: "Set a timer for 25 minutes of uninterrupted work, then take a 5-minute break.",
    },
    {
      title: "Deep Work Block",
      description: "Spend 60 minutes on a single task with zero distractions.",
      difficulty: "advanced",
      estimated_time: 60,
      xp: 40,
      coins: 15,
      benefits: ["Builds intense concentration", "Produces high-quality output"],
    },
    {
      title: "Single-Tasking Exercise",
      description: "Do one thing at a time for 30 minutes — no multitasking.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 25,
      coins: 10,
      benefits: ["Breaks multitasking habit", "Improves quality of work"],
    },
    {
      title: "Distraction Log",
      description: "Every time you get distracted, write down what pulled your attention.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Identifies distraction patterns", "Builds self-awareness"],
    },
    {
      title: "Mindful Breathing",
      description: "Focus on your breath for 5 minutes. When your mind wanders, bring it back.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 3,
      benefits: ["Calms the mind", "Builds focus muscle"],
    },
    {
      title: "Digital Detox Hour",
      description: "Spend one hour with no screens — read, walk, or journal.",
      difficulty: "intermediate",
      estimated_time: 60,
      xp: 30,
      coins: 12,
      benefits: ["Reduces digital dependency", "Restores attention span"],
    },
    {
      title: "Listening Drill",
      description: "Listen to a podcast or talk and summarize key points afterward.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 5,
      benefits: ["Improves auditory focus", "Active listening practice"],
    },
    {
      title: "No-Interruption Meeting",
      description: "In your next conversation, listen without interrupting.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Builds patience", "Improves relationships"],
    },
    {
      title: "Focus Timer Challenge",
      description: "Gradually increase your focus session by 5 minutes each day.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 22,
      coins: 8,
      benefits: ["Progressive overload for attention", "Measurable improvement"],
    },
    {
      title: "Environmental Audit",
      description: "Remove 3 distractions from your workspace.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Optimizes workspace", "Reduces friction"],
    },
    {
      title: "Reading Retention",
      description: "Read a page slowly and summarize each paragraph in one sentence.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 18,
      coins: 6,
      benefits: ["Deep reading practice", "Improves comprehension"],
    },
    {
      title: "Meditation Session",
      description: "Sit in silence and focus on your breath or a single point of attention.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Reduces stress", "Builds concentration"],
    },
    {
      title: "Flow State Prep",
      description: "Set clear goals, remove distractions, and start your most important task.",
      difficulty: "intermediate",
      estimated_time: 20,
      xp: 20,
      coins: 8,
      benefits: ["Prepares mind for deep work", "Increases productivity"],
    },
    {
      title: "Attention Meditation",
      description: "Focus on a single object (like a candle flame) for 10 minutes.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Sharpens visual focus", "Calms mental chatter"],
    },
    {
      title: "Dual N-Back",
      description: "Practice the dual n-back exercise for working memory and focus.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Scientifically validated", "Improves fluid intelligence"],
    },
    {
      title: "One-Thing Challenge",
      description: "Pick ONE task and do it for 45 minutes with zero context switching.",
      difficulty: "advanced",
      estimated_time: 45,
      xp: 35,
      coins: 15,
      benefits: ["Deep focus endurance", "Quality output"],
    },
    {
      title: "Focus Bingo",
      description: "Create a bingo card of distractions — mark each time you resist one.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 5,
      benefits: ["Gamifies focus", "Positive reinforcement"],
    },
    {
      title: "Time Block Planning",
      description: "Plan your entire day in 30-minute blocks — stick to the schedule.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 18,
      coins: 6,
      benefits: ["Structured day", "Reduces decision fatigue"],
    },
    {
      title: "Notification Fast",
      description: "Turn off all non-essential notifications for 4 hours.",
      difficulty: "intermediate",
      estimated_time: 5,
      xp: 20,
      coins: 8,
      benefits: ["Reduces interruptions", "Restores attention"],
    },
    {
      title: "Visual Fixation",
      description: "Stare at a fixed point on the wall for 5 minutes without looking away.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 4,
      benefits: ["Concentration training", "Mental stillness"],
    },
    {
      title: "Counting Breaths",
      description: "Count 100 breaths without losing track — start over if you do.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Sustained attention", "Mindfulness"],
    },
    {
      title: "Reading Without Subvocalizing",
      description: "Read a page without silently saying the words in your head.",
      difficulty: "advanced",
      estimated_time: 10,
      xp: 22,
      coins: 8,
      benefits: ["Speed reading prep", "Quiets inner voice"],
    },
    {
      title: "Monotask Meal",
      description: "Eat a meal with no phone, TV, book, or conversation — just eating.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 10,
      coins: 4,
      benefits: ["Mindful eating", "Single-tasking practice"],
    },
    {
      title: "Concentration Game",
      description: "Play a card matching game (memory-style) for 10 minutes.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Visual focus", "Working memory"],
    },
  ],
  thinking: [
    {
      title: "Decision Journal",
      description: "Write a decision you made today, why you made it, and the expected outcome.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Improves decision quality", "Builds self-awareness"],
    },
    {
      title: "First Principles Analysis",
      description: "Break a problem down to its fundamental truths and reason up from there.",
      difficulty: "advanced",
      estimated_time: 20,
      xp: 30,
      coins: 12,
      benefits: ["Teaches fundamental thinking", "Breaks assumptions"],
    },
    {
      title: "Pros & Cons Grid",
      description: "List pros and cons of a decision you're facing.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Clarifies thinking", "Reduces decision fatigue"],
    },
    {
      title: "Second-Order Thinking",
      description: "For a decision, ask 'and then what?' five times.",
      difficulty: "intermediate",
      estimated_time: 12,
      xp: 20,
      coins: 8,
      benefits: ["Long-term thinking", "Anticipates consequences"],
    },
    {
      title: "Inversion Exercise",
      description: "Instead of asking how to succeed, ask how to fail — then avoid those things.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Reveals blind spots", "Risk management"],
    },
    {
      title: "Mental Model Review",
      description: "Learn and apply one mental model (e.g. Occam's Razor, Pareto Principle).",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Expands thinking toolkit", "Better decisions"],
    },
    {
      title: "Devil's Advocate",
      description: "Argue the opposite side of your own belief for 10 minutes.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Reduces bias", "Builds intellectual humility"],
    },
    {
      title: "Premortem Analysis",
      description: "Imagine your project failed completely — what went wrong?",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Identifies risks early", "Proactive problem solving"],
    },
    {
      title: "Cognitive Bias Check",
      description: "Identify 3 cognitive biases that might be affecting your current thinking.",
      difficulty: "advanced",
      estimated_time: 12,
      xp: 22,
      coins: 8,
      benefits: ["Reduces irrational thinking", "Self-correction skill"],
    },
    {
      title: "Thought Experiment",
      description: "Explore a 'what if' scenario in detail.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Expands imagination", "Creative problem solving"],
    },
    {
      title: "Socratic Questioning",
      description: "Challenge your own assumptions by asking 'why' five times.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Deeper understanding", "Uncover root causes"],
    },
    {
      title: "Probabilistic Thinking",
      description: "Assign probabilities to different outcomes and update as you learn more.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Better risk assessment", "Calibrated decision making"],
    },
    {
      title: "Argument Mapping",
      description: "Draw a visual map of an argument showing premises and conclusions.",
      difficulty: "advanced",
      estimated_time: 20,
      xp: 28,
      coins: 10,
      benefits: ["Clarifies complex reasoning", "Improves logic"],
    },
    {
      title: "Post-Mortem Review",
      description: "Analyze a recent failure or mistake and extract lessons.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Learning from failure", "Continuous improvement"],
    },
    {
      title: "Lateral Thinking Puzzle",
      description: "Solve a lateral thinking puzzle that requires creative connections.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Breaks rigid thinking", "Encourages creativity"],
    },
    {
      title: "Decision Matrix",
      description: "Create a weighted decision matrix for a choice you're facing.",
      difficulty: "intermediate",
      estimated_time: 20,
      xp: 22,
      coins: 8,
      benefits: ["Structured decisions", "Quantitative thinking"],
    },
    {
      title: "Occam's Razor Exercise",
      description: "Take a complex problem and find the simplest possible explanation.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Simplifies complexity", "Critical thinking"],
    },
    {
      title: "Word Association Chain",
      description: "Start with one word and create a chain of associations — see where you end up.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Divergent thinking", "Creativity warm-up"],
    },
    {
      title: "Logical Fallacy Hunt",
      description: "Find 3 logical fallacies in today's news, ads, or conversations.",
      difficulty: "advanced",
      estimated_time: 10,
      xp: 25,
      coins: 10,
      benefits: ["Critical thinking", "Media literacy"],
    },
    {
      title: "System Thinking Map",
      description: "Draw a system map showing how parts of a problem interact.",
      difficulty: "advanced",
      estimated_time: 20,
      xp: 30,
      coins: 12,
      benefits: ["Systems thinking", "Holistic view"],
    },
    {
      title: "Hypothesis Testing",
      description: "State a hypothesis, design a mini-experiment, and test it today.",
      difficulty: "advanced",
      estimated_time: 20,
      xp: 28,
      coins: 10,
      benefits: ["Scientific thinking", "Empirical mindset"],
    },
    {
      title: "Chess Puzzle",
      description: "Solve a chess puzzle (find the best move in a given position).",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 20,
      coins: 8,
      benefits: ["Strategic thinking", "Pattern recognition"],
    },
    {
      title: "Sudoku",
      description: "Complete a Sudoku puzzle (medium difficulty).",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Logical reasoning", "Concentration"],
    },
    {
      title: "Straw Man Self-Critique",
      description: "Build the weakest version of your argument and then demolish it.",
      difficulty: "advanced",
      estimated_time: 12,
      xp: 22,
      coins: 8,
      benefits: ["Intellectual rigor", "Antifragile thinking"],
    },
  ],
  learning: [
    {
      title: "Read 15 Minutes",
      description: "Read a book or long-form article for 15 minutes.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Builds knowledge", "Improves focus"],
    },
    {
      title: "Teach Someone Else",
      description: "Explain a concept you learned today to someone else.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Deepens understanding", "Identifies gaps"],
    },
    {
      title: "Feynman Technique",
      description: "Explain a concept in simple terms as if teaching a child.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 22,
      coins: 8,
      benefits: ["Reveals gaps in knowledge", "Simplifies complex ideas"],
    },
    {
      title: "Active Recall Session",
      description: "Close your notes and try to recall everything from memory.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Strengthens neural pathways", "High retention"],
    },
    {
      title: "Learn One New Word",
      description: "Look up a new word, its meaning, and use it in a sentence today.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Expands vocabulary", "Quick win"],
    },
    {
      title: "Online Course Module",
      description: "Complete one module of an online course.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 30,
      coins: 12,
      benefits: ["Structured learning", "Skill building"],
    },
    {
      title: "Summarize What You Learned",
      description: "Write a 3-sentence summary of something new you learned today.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 3,
      benefits: ["Consolidates learning", "Builds writing habit"],
    },
    {
      title: "Cross-Discipline Reading",
      description: "Read about a topic completely outside your field.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Widens perspective", "Encourages curiosity"],
    },
    {
      title: "Skill Practice Session",
      description: "Dedicated practice of a skill you're developing.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 25,
      coins: 10,
      benefits: ["Deliberate practice", "Accelerates mastery"],
    },
    {
      title: "Read and Reflect",
      description: "Read a passage and write a reflection on how it applies to your life.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Connects learning to life", "Deep comprehension"],
    },
    {
      title: "Flashcard Creation",
      description: "Create 10 flashcards for a topic you're studying.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Active learning", "Study tool creation"],
    },
    {
      title: "Podcast Learning",
      description: "Listen to an educational podcast and note 3 key takeaways.",
      difficulty: "beginner",
      estimated_time: 20,
      xp: 15,
      coins: 5,
      benefits: ["Learning on the go", "Auditory learning"],
    },
    {
      title: "Spaced Repetition Review",
      description: "Review material you learned 1, 3, and 7 days ago.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 22,
      coins: 8,
      benefits: ["Long-term retention", "Efficient study"],
    },
    {
      title: "Visual Note-Taking",
      description: "Create a visual mind map of a topic instead of linear notes.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Visual thinking", "Better connections"],
    },
    {
      title: "Learning Journal Entry",
      description: "Write in your learning journal: what you learned, how you learned it, and what's next.",
      difficulty: "beginner",
      estimated_time: 8,
      xp: 10,
      coins: 4,
      benefits: ["Metacognition", "Tracking progress"],
    },
    {
      title: "Wikipedia Rabbit Hole",
      description: "Start on one Wikipedia page and follow links to learn about 5 connected topics.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 4,
      benefits: ["Curiosity-driven learning", "Makes connections"],
    },
    {
      title: "Skill Swap",
      description: "Teach someone a skill you know and have them teach you one in return.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 30,
      coins: 12,
      benefits: ["Reciprocal learning", "Social connection"],
    },
    {
      title: "Documentary Deep Dive",
      description: "Watch a documentary on a topic you know nothing about.",
      difficulty: "beginner",
      estimated_time: 45,
      xp: 20,
      coins: 8,
      benefits: ["Broadens horizons", "Passive learning"],
    },
    {
      title: "Mistake Analysis",
      description: "Review a recent mistake and identify the specific knowledge gap that caused it.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Targeted learning", "Growth mindset"],
    },
    {
      title: "Dual Coding Practice",
      description: "Learn a concept using both words AND visuals simultaneously.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Dual coding theory", "Stronger encoding"],
    },
    {
      title: "Interleaved Practice",
      description: "Study 3 different topics in rotation instead of one topic at a time.",
      difficulty: "advanced",
      estimated_time: 30,
      xp: 28,
      coins: 10,
      benefits: ["Better discrimination", "Transferable knowledge"],
    },
    {
      title: "How Things Work",
      description: "Pick an everyday object and learn exactly how it works.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Curiosity", "Practical knowledge"],
    },
    {
      title: "Anki Session",
      description: "Review your Anki (or other spaced repetition) deck for 10 minutes.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Spaced repetition", "Long-term retention"],
    },
    {
      title: "Reading Sprint",
      description: "Read as many pages as possible in 10 minutes, then summarize.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Speed reading practice", "Comprehension under pressure"],
    },
  ],
  health: [
    {
      title: "Walk 20 Minutes",
      description: "Take a 20-minute walk outdoors.",
      difficulty: "beginner",
      estimated_time: 20,
      xp: 15,
      coins: 5,
      benefits: ["Boosts blood flow to brain", "Improves mood", "Enhances creativity"],
    },
    {
      title: "Hydration Check",
      description: "Drink at least 8 glasses of water today.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Brain needs hydration", "Improves focus"],
    },
    {
      title: "Morning Stretch",
      description: "10-minute full body stretch routine.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Increases blood flow", "Reduces tension"],
    },
    {
      title: "Power Nap",
      description: "Nap for 20 minutes to recharge cognitive energy.",
      difficulty: "beginner",
      estimated_time: 20,
      xp: 12,
      coins: 5,
      benefits: ["Restores alertness", "Improves memory consolidation"],
    },
    {
      title: "Screen Break Routine",
      description: "Every 90 minutes, take a 5-minute break from screens.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 10,
      coins: 4,
      benefits: ["Reduces eye strain", "Prevents mental fatigue"],
    },
    {
      title: "Exercise Session",
      description: "30 minutes of physical exercise (cardio, strength, or yoga).",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 25,
      coins: 10,
      benefits: ["Boosts brain-derived neurotrophic factor", "Improves mood"],
    },
    {
      title: "Healthy Meal Prep",
      description: "Prepare a brain-healthy meal with omega-3s, antioxidants, and complex carbs.",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 20,
      coins: 8,
      benefits: ["Supports brain health", "Builds healthy habits"],
    },
    {
      title: "Sleep Hygiene Check",
      description: "Go to bed 30 minutes earlier than usual.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 12,
      coins: 5,
      benefits: ["Improves memory consolidation", "Restores cognitive function"],
    },
    {
      title: "Nature Exposure",
      description: "Spend 15 minutes in nature — park, garden, or trees.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 5,
      benefits: ["Reduces stress", "Restores attention"],
    },
    {
      title: "Cold Shower",
      description: "End your shower with 30 seconds of cold water.",
      difficulty: "intermediate",
      estimated_time: 5,
      xp: 15,
      coins: 6,
      benefits: ["Increases alertness", "Builds mental toughness"],
    },
    {
      title: "Posture Check",
      description: "Maintain good posture throughout the day — set hourly reminders.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Improves oxygen flow", "Reduces fatigue"],
    },
    {
      title: "Sunlight Exposure",
      description: "Get 15 minutes of morning sunlight.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 10,
      coins: 4,
      benefits: ["Regulates circadian rhythm", "Boosts vitamin D"],
    },
    {
      title: "Breathing Exercise",
      description: "5 minutes of box breathing (4-4-4-4 pattern).",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Reduces stress", "Calms nervous system"],
    },
    {
      title: "Workout Session",
      description: "Complete a structured workout (gym, home, or sports).",
      difficulty: "intermediate",
      estimated_time: 45,
      xp: 30,
      coins: 12,
      benefits: ["Physical fitness", "Mental resilience"],
    },
    {
      title: "Evening Wind-Down",
      description: "Create a 30-minute screen-free wind-down routine before bed.",
      difficulty: "beginner",
      estimated_time: 30,
      xp: 15,
      coins: 5,
      benefits: ["Better sleep quality", "Reduces bedtime anxiety"],
    },
    {
      title: "Blue Light Block",
      description: "Wear blue-light blocking glasses 2 hours before bed.",
      difficulty: "beginner",
      estimated_time: 2,
      xp: 5,
      coins: 2,
      benefits: ["Melatonin support", "Sleep quality"],
    },
    {
      title: "Progressive Muscle Relaxation",
      description: "Tense and release each muscle group from toes to head.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Stress reduction", "Body awareness"],
    },
    {
      title: "Dance Break",
      description: "Put on your favorite song and dance for 3 minutes.",
      difficulty: "beginner",
      estimated_time: 3,
      xp: 8,
      coins: 3,
      benefits: ["Mood boost", "Cardiovascular", "Fun"],
    },
    {
      title: "Omega-3 Meal Prep",
      description: "Cook a meal rich in omega-3 fatty acids (salmon, walnuts, flax).",
      difficulty: "intermediate",
      estimated_time: 30,
      xp: 20,
      coins: 8,
      benefits: ["Brain health", "Long-term cognitive support"],
    },
    {
      title: "Stair Climbing",
      description: "Take the stairs instead of the elevator all day. Count total floors.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 8,
      coins: 3,
      benefits: ["Cardiovascular health", "Leg strength"],
    },
    {
      title: "Eye Exercise Routine",
      description: "Follow the 20-20-20 rule: every 20 minutes, look 20 feet away for 20 seconds.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 5,
      coins: 2,
      benefits: ["Reduces eye strain", "Prevents digital fatigue"],
    },
    {
      title: "Walking Meeting",
      description: "Take your next phone call while walking outside.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 10,
      coins: 4,
      benefits: ["Movement", "Fresh air", "Dual purpose"],
    },
    {
      title: "Yoga Flow",
      description: "Follow a 15-minute yoga video or routine.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Flexibility", "Mind-body connection", "Stress relief"],
    },
    {
      title: "Caffeine Curfew",
      description: "No caffeine after 2 PM — notice the difference in sleep quality.",
      difficulty: "intermediate",
      estimated_time: 2,
      xp: 12,
      coins: 5,
      benefits: ["Better sleep", "Natural energy regulation"],
    },
  ],
  creativity: [
    {
      title: "Morning Pages",
      description: "Write 3 pages of stream-of-consciousness thoughts first thing.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Clears mental clutter", "Unlocks creativity"],
    },
    {
      title: "Brainstorm 10 Ideas",
      description: "Generate 10 ideas for a problem you're facing — no judgment allowed.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Divergent thinking", "Overcomes creative block"],
    },
    {
      title: "Constraint Creation",
      description: "Create something with an artificial constraint (e.g. only 50 words).",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Forces creative solutions", "Breaks habits"],
    },
    {
      title: "Idea Combination",
      description: "Combine two unrelated concepts to create something new.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Innovative thinking", "Makes unexpected connections"],
    },
    {
      title: "Creative Journaling",
      description: "Write a short story, poem, or creative reflection.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Self-expression", "Creativity practice"],
    },
    {
      title: "Reverse Brainstorming",
      description: "Brainstorm ways to make a problem worse, then reverse the ideas.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Unconventional solutions", "Fun approach"],
    },
    {
      title: "Analogies Exercise",
      description: "Find 3 analogies for a concept you're working on.",
      difficulty: "intermediate",
      estimated_time: 12,
      xp: 18,
      coins: 6,
      benefits: ["Connects domains", "Deepens understanding"],
    },
    {
      title: "Doodle Session",
      description: "Spend 10 minutes doodling without any goal.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Relaxes the mind", "Sparks ideas"],
    },
    {
      title: "SCAMPER Exercise",
      description: "Apply SCAMPER (Substitute, Combine, Adapt...) to an existing product.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Structured creativity", "Innovation technique"],
    },
    {
      title: "Random Word Association",
      description: "Open a book to a random word and connect it to your current problem.",
      difficulty: "beginner",
      estimated_time: 8,
      xp: 12,
      coins: 4,
      benefits: ["Breaks thought patterns", "Sparks new ideas"],
    },
    {
      title: "Creative Challenge",
      description: "Complete a daily creative challenge (draw, write, compose, build).",
      difficulty: "intermediate",
      estimated_time: 20,
      xp: 22,
      coins: 8,
      benefits: ["Builds creative muscle", "Daily practice"],
    },
    {
      title: "Mind Mapping",
      description: "Create a mind map for a topic or problem.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Visual thinking", "Makes connections"],
    },
    {
      title: "What If Scenario",
      description: "Ask 'what if' about a current situation and explore the possibilities.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Expands thinking", "Imaginative exploration"],
    },
    {
      title: "Creative Constraints",
      description: "Solve a problem using only resources you already have.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Resourcefulness", "Practical creativity"],
    },
    {
      title: "Original Idea Challenge",
      description: "Come up with one completely original idea today.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 15,
      coins: 5,
      benefits: ["Original thinking", "Innovation practice"],
    },
    {
      title: "Six Hats Thinking",
      description: "Analyze a problem from 6 perspectives: facts, emotions, risks, benefits, creativity, process.",
      difficulty: "advanced",
      estimated_time: 20,
      xp: 30,
      coins: 12,
      benefits: ["Multi-perspective thinking", "Structured creativity"],
    },
    {
      title: "Color Palette Creation",
      description: "Create a 5-color palette inspired by a photo or mood.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 10,
      coins: 4,
      benefits: ["Visual creativity", "Design skills"],
    },
    {
      title: "Metaphor Making",
      description: "Describe your current challenge using a metaphor from a completely different domain.",
      difficulty: "intermediate",
      estimated_time: 8,
      xp: 18,
      coins: 6,
      benefits: ["Abstract thinking", "Fresh perspectives"],
    },
    {
      title: "Musical Improv",
      description: "Hum or whistle a melody you've never heard before — record it.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 12,
      coins: 4,
      benefits: ["Musical creativity", "Self-expression"],
    },
    {
      title: "Interview Preparation",
      description: "Prepare 10 creative questions to ask someone interesting.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Curiosity practice", "Conversation skills"],
    },
    {
      title: "Rebrand Exercise",
      description: "Pick a famous brand and redesign its identity (name, logo, tagline).",
      difficulty: "intermediate",
      estimated_time: 20,
      xp: 22,
      coins: 8,
      benefits: ["Creative thinking", "Brand strategy"],
    },
    {
      title: "Photo Challenge",
      description: "Take 10 photos with a theme — find beauty in everyday objects.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 12,
      coins: 5,
      benefits: ["Visual creativity", "Mindfulness"],
    },
    {
      title: "Alternate Uses",
      description: "Pick an object and list 20 alternate uses for it.",
      difficulty: "beginner",
      estimated_time: 6,
      xp: 10,
      coins: 4,
      benefits: ["Divergent thinking", "Creativity warm-up"],
    },
    {
      title: "Poetry Exercise",
      description: "Write a haiku (5-7-5) about your day.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 4,
      benefits: ["Creative constraint", "Self-expression"],
    },
    {
      title: "Prototype Sprint",
      description: "Build a rough prototype of an idea using whatever materials you have.",
      difficulty: "intermediate",
      estimated_time: 25,
      xp: 25,
      coins: 10,
      benefits: ["Rapid prototyping", "Hands-on creativity"],
    },
  ],
  "emotional-intelligence": [
    {
      title: "Gratitude List",
      description: "Write down 3 things you're grateful for today.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 3,
      benefits: ["Increases happiness", "Shifts perspective"],
    },
    {
      title: "Emotion Labeling",
      description: "Throughout the day, name the emotions you feel.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Emotional awareness", "Self-regulation"],
    },
    {
      title: "Active Listening Practice",
      description: "In your next conversation, listen to understand, not to reply.",
      difficulty: "intermediate",
      estimated_time: 15,
      xp: 20,
      coins: 8,
      benefits: ["Better relationships", "Deeper connections"],
    },
    {
      title: "Empathy Exercise",
      description: "Imagine someone else's perspective in detail — what do they feel?",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Builds empathy", "Reduces conflict"],
    },
    {
      title: "Journal Prompt: Today's Emotions",
      description: "Write about the strongest emotion you felt today and why.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 4,
      benefits: ["Self-reflection", "Emotional processing"],
    },
    {
      title: "Compliment Someone",
      description: "Give a genuine compliment to someone today.",
      difficulty: "beginner",
      estimated_time: 2,
      xp: 8,
      coins: 3,
      benefits: ["Spreads positivity", "Strengthens bonds"],
    },
    {
      title: "Pause and Respond",
      description: "Before responding to a triggering situation, pause for 5 seconds.",
      difficulty: "intermediate",
      estimated_time: 5,
      xp: 15,
      coins: 6,
      benefits: ["Reactive to responsive", "Better outcomes"],
    },
    {
      title: "Nonviolent Communication",
      description: "Practice the NVC framework: observation, feeling, need, request.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Conflict resolution", "Clear communication"],
    },
    {
      title: "Social Connection",
      description: "Reach out to a friend or family member you haven't spoken to recently.",
      difficulty: "beginner",
      estimated_time: 10,
      xp: 12,
      coins: 5,
      benefits: ["Strengthens relationships", "Builds support network"],
    },
    {
      title: "Body Scan",
      description: "Notice physical sensations in your body — where do you feel tension?",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 3,
      benefits: ["Mind-body connection", "Stress awareness"],
    },
    {
      title: "React vs Respond Analysis",
      description: "Reflect on a recent reaction — how could you have responded differently?",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Pattern recognition", "Emotional growth"],
    },
    {
      title: "Values Check-In",
      description: "Did your actions today align with your core values?",
      difficulty: "intermediate",
      estimated_time: 8,
      xp: 15,
      coins: 5,
      benefits: ["Value-driven living", "Authenticity"],
    },
    {
      title: "Forgiveness Practice",
      description: "Write a letter of forgiveness (you don't need to send it).",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 25,
      coins: 10,
      benefits: ["Emotional release", "Reduces resentment"],
    },
    {
      title: "Self-Compassion Break",
      description: "When you make a mistake, speak to yourself as you would to a friend.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 4,
      benefits: ["Reduces self-criticism", "Builds resilience"],
    },
    {
      title: "Mindful Conversation",
      description: "Have a conversation where you are fully present — no phone, no distractions.",
      difficulty: "intermediate",
      estimated_time: 20,
      xp: 20,
      coins: 8,
      benefits: ["Deep connection", "Quality interaction"],
    },
    {
      title: "3 Good Things",
      description: "Share three good things that happened today with someone else.",
      difficulty: "beginner",
      estimated_time: 5,
      xp: 10,
      coins: 4,
      benefits: ["Positivity practice", "Social bonding"],
    },
    {
      title: "Emotional Diary",
      description: "Track your emotions hourly for one day — notice patterns.",
      difficulty: "intermediate",
      estimated_time: 10,
      xp: 18,
      coins: 6,
      benefits: ["Pattern recognition", "Self-awareness"],
    },
    {
      title: "Active Constructive Responding",
      description: "When someone shares good news, respond with enthusiastic and specific interest.",
      difficulty: "intermediate",
      estimated_time: 5,
      xp: 15,
      coins: 6,
      benefits: ["Relationship building", "Positive psychology"],
    },
    {
      title: "Boundary Setting",
      description: "Identify one boundary you need to set and communicate it clearly.",
      difficulty: "advanced",
      estimated_time: 10,
      xp: 25,
      coins: 10,
      benefits: ["Self-respect", "Healthy relationships"],
    },
    {
      title: "Mirror Exercise",
      description: "Look at yourself in the mirror and say something kind for 2 minutes.",
      difficulty: "advanced",
      estimated_time: 2,
      xp: 20,
      coins: 8,
      benefits: ["Self-compassion", "Vulnerability practice"],
    },
    {
      title: "Active Empathy Challenge",
      description: "For one hour, imagine everyone you interact with is fighting a difficult battle.",
      difficulty: "intermediate",
      estimated_time: 60,
      xp: 25,
      coins: 10,
      benefits: ["Compassion", "Patience"],
    },
    {
      title: "Reappraisal Practice",
      description: "Take a negative situation and find 3 positive reframes for it.",
      difficulty: "intermediate",
      estimated_time: 8,
      xp: 18,
      coins: 6,
      benefits: ["Emotional regulation", "Cognitive flexibility"],
    },
    {
      title: "Non-Judgment Day",
      description: "Go one day without judging anyone (including yourself).",
      difficulty: "advanced",
      estimated_time: 5,
      xp: 30,
      coins: 12,
      benefits: ["Acceptance", "Inner peace"],
    },
    {
      title: "Love Letter Writing",
      description: "Write a heartfelt letter to someone you appreciate.",
      difficulty: "beginner",
      estimated_time: 15,
      xp: 15,
      coins: 5,
      benefits: ["Gratitude", "Deep connection"],
    },
    {
      title: "Trigger Mapping",
      description: "Identify 3 emotional triggers and plan a healthy response for each.",
      difficulty: "advanced",
      estimated_time: 15,
      xp: 28,
      coins: 10,
      benefits: ["Emotional mastery", "Self-regulation"],
    },
  ],
};

async function seed() {
  console.log("Seeding BrainGym database...\n");

  // Check if data already exists
  const { count } = await supabase
    .from("categories")
    .select("*", { count: "exact", head: true });

  if (count && count > 0) {
    console.log("Database already seeded. Skipping.");
    return;
  }

  // Seed categories
  const { data: insertedCategories, error: catError } = await supabase
    .from("categories")
    .insert(categories)
    .select();

  if (catError) {
    console.error("Error seeding categories:", catError);
    process.exit(1);
  }

  console.log(`✓ Inserted ${insertedCategories.length} categories`);

  // Seed activities
  const categoryMap = new Map(
    insertedCategories.map((c: { slug: string; id: string }) => [c.slug, c.id])
  );

  let totalActivities = 0;

  for (const [slug, activities] of Object.entries(activitiesByCategory)) {
    const categoryId = categoryMap.get(slug);
    if (!categoryId) {
      console.warn(`No category found for slug: ${slug}`);
      continue;
    }

    const records = activities.map((a) => ({
      category_id: categoryId,
      title: a.title,
      description: a.description,
      difficulty: a.difficulty,
      estimated_time: a.estimated_time,
      xp: a.xp,
      coins: a.coins,
      benefits: a.benefits,
      instructions: a.instructions || null,
      tips: a.tips || null,
    }));

    const { error: actError } = await supabase
      .from("activities")
      .insert(records);

    if (actError) {
      console.error(`Error seeding activities for ${slug}:`, actError);
    } else {
      totalActivities += records.length;
    }
  }

  console.log(`✓ Inserted ${totalActivities} activities`);
  console.log("\nSeed complete!");
}

seed().catch(console.error);
