/**
 * AGE-CUSTOMIZED BRAIN GAMES & QUESTIONS ENGINE
 * Provides specialized cognitive games and tailored question sets
 * customized to each age bracket (15-19, 20-25, 26-30, 31-35, 36-40, 41-45, 46-50+).
 */

import { AgeTierId, AGE_TIER_CONFIGS } from "./types";
import { CognitiveChallenge } from "@/lib/challenges-engine/types";

export interface AgeCustomizedGame {
  id: string;
  ageTier: AgeTierId;
  title: string;
  tagline: string;
  category: "Memory" | "Focus" | "Logic" | "Emotional Intelligence" | "Decision Making" | "Speed";
  cognitiveSkill: string;
  emoji: string;
  gradient: string;
  difficulty: "Adaptive" | "Easy" | "Medium" | "Hard" | "Expert";
  durationMinutes: number;
  xpReward: number;
  coinReward: number;
  lifeScenarioExplanation: string;
  gameplayPrompt: string;
  targetOutcome: string;
}

export const AGE_CUSTOMIZED_GAMES: Record<AgeTierId, AgeCustomizedGame[]> = {
  "15-19": [
    {
      id: "game-teen-exam-recall",
      ageTier: "15-19",
      title: "Exam Active Recall Sprint",
      tagline: "Ditch passive rereading. Master high-speed formula and definition retrieval under timed exam conditions.",
      category: "Memory",
      cognitiveSkill: "Active Semantic Retrieval",
      emoji: "🎒",
      gradient: "from-indigo-500/20 to-blue-500/20",
      difficulty: "Adaptive",
      durationMinutes: 4,
      xpReward: 35,
      coinReward: 15,
      lifeScenarioExplanation: "When opening a difficult test paper, passive notes fade from working memory. Active retrieval builds durable synaptic pathways.",
      gameplayPrompt: "Recall key terms and formulas before the countdown ends without checking notes.",
      targetOutcome: "Boosts WAEC/JAMB/SAT exam retention by 40%.",
    },
    {
      id: "game-teen-distraction-gate",
      ageTier: "15-19",
      title: "Notification Dopamine Gate",
      tagline: "Train prefrontal impulse inhibition against social media notifications while studying.",
      category: "Focus",
      cognitiveSkill: "Selective Inhibitory Control",
      emoji: "📵",
      gradient: "from-amber-500/20 to-rose-500/20",
      difficulty: "Medium",
      durationMinutes: 5,
      xpReward: 40,
      coinReward: 20,
      lifeScenarioExplanation: "Developing teen prefrontal cortex is hyper-sensitive to social dopamine pings. Gating builds high-focus study stamina.",
      gameplayPrompt: "Tap the correct focus target while ignoring rapidly popping simulated notification alerts.",
      targetOutcome: "Extends uninterrupted study blocks to 45+ minutes.",
    },
    {
      id: "game-teen-speed-math",
      ageTier: "15-19",
      title: "Pocket Money & Fast Math Balancer",
      tagline: "Rapid mental arithmetic and impulse savings calculations for allowance and transport budgeting.",
      category: "Logic",
      cognitiveSkill: "Working Memory Arithmetic",
      emoji: "🪙",
      gradient: "from-emerald-500/20 to-teal-500/20",
      difficulty: "Adaptive",
      durationMinutes: 3,
      xpReward: 30,
      coinReward: 15,
      lifeScenarioExplanation: "Calculating trade-offs between instant snacking and saving for personal goals trains executive forward planning.",
      gameplayPrompt: "Solve rapid money allocations under 10 seconds per round.",
      targetOutcome: "Builds financial intuition and fast quantitative agility.",
    },
  ],

  "20-25": [
    {
      id: "game-youth-feynman-synthesizer",
      ageTier: "20-25",
      title: "Feynman Concept Synthesizer",
      tagline: "Explain complex academic or technical concepts in 3 simple sentences as if teaching a 10-year-old.",
      category: "Memory",
      cognitiveSkill: "Conceptual Schema Compression",
      emoji: "🎓",
      gradient: "from-violet-500/20 to-indigo-500/20",
      difficulty: "Adaptive",
      durationMinutes: 5,
      xpReward: 45,
      coinReward: 20,
      lifeScenarioExplanation: "University exams and thesis defenses reward deep conceptual comprehension over superficial jargon.",
      gameplayPrompt: "Deconstruct technical definitions into elementary analogies without using banned filler words.",
      targetOutcome: "Eliminates academic cramming forgetfulness.",
    },
    {
      id: "game-youth-interview-matrix",
      ageTier: "20-25",
      title: "First Job Interview Reaction Matrix",
      tagline: "Overcome freeze responses during unexpected behavioral questions in job and internship interviews.",
      category: "Decision Making",
      cognitiveSkill: "High-Pressure Fluid Reasoning",
      emoji: "💼",
      gradient: "from-cyan-500/20 to-blue-500/20",
      difficulty: "Medium",
      durationMinutes: 4,
      xpReward: 40,
      coinReward: 20,
      lifeScenarioExplanation: "Amygdala threat loops cause verbal stumbling during recruiter evaluation. Tactical pause restores articulation.",
      gameplayPrompt: "Select the highest-leverage structured response (STAR method) within 4 seconds.",
      targetOutcome: "Delivers poise and high confidence during career interviews.",
    },
    {
      id: "game-youth-budget-roi",
      ageTier: "20-25",
      title: "Starter Salary & ROI Allocator",
      tagline: "Calculate emergency buffers, rent ratios, and investments from early career paychecks.",
      category: "Logic",
      cognitiveSkill: "Probabilistic Financial Gating",
      emoji: "📈",
      gradient: "from-emerald-500/20 to-green-500/20",
      difficulty: "Adaptive",
      durationMinutes: 4,
      xpReward: 35,
      coinReward: 15,
      lifeScenarioExplanation: "Early adulthood financial habits determine long-term wealth trajectory.",
      gameplayPrompt: "Allocate fluctuating income across survival, emergency fund, and skills investment.",
      targetOutcome: "Instills zero-debt financial resilience.",
    },
  ],

  "26-30": [
    {
      id: "game-career-proposal-poker",
      ageTier: "26-30",
      title: "Client Pitch & Negotiation Poker",
      tagline: "Read subtle counter-party cues and defend project pricing during high-stakes business pitches.",
      category: "Decision Making",
      cognitiveSkill: "Negotiation Agility & Deduction",
      emoji: "🚀",
      gradient: "from-amber-500/20 to-orange-500/20",
      difficulty: "Adaptive",
      durationMinutes: 5,
      xpReward: 50,
      coinReward: 25,
      lifeScenarioExplanation: "Navigating corporate contracts requires holding strategic composure when clients demand aggressive discounts.",
      gameplayPrompt: "Calculate expected value and counter with value anchors rather than emotional concessions.",
      targetOutcome: "Increases proposal win rates and prevents contract underpricing.",
    },
    {
      id: "game-career-48hr-buffer",
      ageTier: "26-30",
      title: "48-Hour Financial Impulse Gate",
      tagline: "Block dopamine-driven lifestyle creep and luxury gadget impulsive purchases.",
      category: "Emotional Intelligence",
      cognitiveSkill: "Executive Inhibitory Control",
      emoji: "🛡️",
      gradient: "from-rose-500/20 to-red-500/20",
      difficulty: "Medium",
      durationMinutes: 3,
      xpReward: 35,
      coinReward: 15,
      lifeScenarioExplanation: "Income growth in late 20s often triggers impulsive lifestyle inflation. Gating protects capital.",
      gameplayPrompt: "Categorize purchase triggers into essential asset vs dopamine distraction within 3 seconds.",
      targetOutcome: "Saves 20–30% more monthly capital for investing.",
    },
    {
      id: "game-career-deepwork-stamina",
      ageTier: "26-30",
      title: "90-Min Deep Work Cognitive Stamina",
      tagline: "Maintain laser focus through complex coding, writing, or analysis without browser tab hopping.",
      category: "Focus",
      cognitiveSkill: "Sustained Attentional Endurance",
      emoji: "⚡",
      gradient: "from-teal-500/20 to-emerald-500/20",
      difficulty: "Hard",
      durationMinutes: 6,
      xpReward: 50,
      coinReward: 25,
      lifeScenarioExplanation: "High-value career output is produced in deep, undisturbed cognitive blocks.",
      gameplayPrompt: "Identify subtle data pattern anomalies across 5 sequential high-complexity puzzles.",
      targetOutcome: "Builds stamina for uninterrupted 2-hour strategic work blocks.",
    },
  ],

  "31-35": [
    {
      id: "game-mid-dual-track-memory",
      ageTier: "31-35",
      title: "Executive Dual-Track Working Memory",
      tagline: "Retain multi-department action items and supplier timelines despite constant interruptions.",
      category: "Memory",
      cognitiveSkill: "Dual N-Back Working Memory",
      emoji: "💼",
      gradient: "from-blue-500/20 to-indigo-500/20",
      difficulty: "Adaptive",
      durationMinutes: 5,
      xpReward: 50,
      coinReward: 25,
      lifeScenarioExplanation: "Managing staff, customers, and domestic tasks overloads short-term working memory.",
      gameplayPrompt: "Track both auditory numbers and visual location markers simultaneously across 10 rounds.",
      targetOutcome: "Stops mental fog and dropped deliverables.",
    },
    {
      id: "game-mid-sme-cashflow",
      ageTier: "31-35",
      title: "SME Cash Flow Volatility Solver",
      tagline: "Navigate sudden inflation, delayed invoice payments, and payroll emergencies without panic.",
      category: "Logic",
      cognitiveSkill: "Stress-Resilient Quantitative Logic",
      emoji: "📊",
      gradient: "from-emerald-500/20 to-teal-500/20",
      difficulty: "Hard",
      durationMinutes: 4,
      xpReward: 45,
      coinReward: 20,
      lifeScenarioExplanation: "Cash flow volatility triggers acute prefrontal freeze. Structured triage maintains liquidity.",
      gameplayPrompt: "Triage 4 competing expense claims to keep the enterprise solvent within a 15-second clock.",
      targetOutcome: "Protects business runway and executive mental peace.",
    },
    {
      id: "game-mid-domestic-reset",
      ageTier: "31-35",
      title: "Evening 90-Sec Domestic Reset",
      tagline: "Transition from workplace fatigue to calm, warm parenting and spousal connection.",
      category: "Emotional Intelligence",
      cognitiveSkill: "Autonomic Nervous System Modulation",
      emoji: "🏡",
      gradient: "from-rose-500/20 to-orange-500/20",
      difficulty: "Adaptive",
      durationMinutes: 3,
      xpReward: 35,
      coinReward: 15,
      lifeScenarioExplanation: "Entering the home with residual work cortisol causes short temper with young children.",
      gameplayPrompt: "Sync your breathing with the visual vagal pacer and discard work worries into the virtual lockbox.",
      targetOutcome: "Creates domestic warmth and emotional harmony.",
    },
  ],

  "36-40": [
    {
      id: "game-lead-boardroom-alignment",
      ageTier: "36-40",
      title: "Boardroom Stakeholder Alignment",
      tagline: "Synthesize conflicting executive opinions and build unanimous consensus on high-risk bets.",
      category: "Decision Making",
      cognitiveSkill: "Multi-Agent Game Theory",
      emoji: "🏢",
      gradient: "from-violet-500/20 to-purple-500/20",
      difficulty: "Expert",
      durationMinutes: 5,
      xpReward: 55,
      coinReward: 30,
      lifeScenarioExplanation: "Senior leadership demands seeing through organizational political agendas to protect the core vision.",
      gameplayPrompt: "Evaluate 3 stakeholder motivations and select the win-win concession path.",
      targetOutcome: "Unlocks executive consensus and prevents project gridlock.",
    },
    {
      id: "game-lead-decision-fatigue",
      ageTier: "36-40",
      title: "Decision Fatigue Optimization",
      tagline: "Filter low-leverage requests to protect prime morning cognitive bandwidth for high-impact strategy.",
      category: "Focus",
      cognitiveSkill: "Cognitive Bandwidth Rationing",
      emoji: "🎯",
      gradient: "from-teal-500/20 to-cyan-500/20",
      difficulty: "Medium",
      durationMinutes: 4,
      xpReward: 40,
      coinReward: 20,
      lifeScenarioExplanation: "Making hundreds of micro-decisions by 2 PM impairs strategic judgment.",
      gameplayPrompt: "Sort incoming organizational demands into: Delegate, Automate, Delete, or Deep Focus.",
      targetOutcome: "Saves 3 hours of executive energy daily.",
    },
  ],

  "41-45": [
    {
      id: "game-exec-crisis-war-room",
      ageTier: "41-45",
      title: "Crisis Management War Room",
      tagline: "Navigate organizational PR or operational emergencies with zero panic and disciplined triage.",
      category: "Decision Making",
      cognitiveSkill: "High-Ambiguity Crisis Resolution",
      emoji: "👔",
      gradient: "from-slate-500/20 to-zinc-600/20",
      difficulty: "Expert",
      durationMinutes: 5,
      xpReward: 60,
      coinReward: 30,
      lifeScenarioExplanation: "Executive leadership is defined by composure during unexpected black swan events.",
      gameplayPrompt: "Isolate the root cause of an unfolding crisis across 4 operational telemetry streams.",
      targetOutcome: "Maintains organizational stability under fire.",
    },
    {
      id: "game-exec-teen-coregulation",
      ageTier: "41-45",
      title: "Teen Emotional Co-Regulation",
      tagline: "De-escalate adolescent emotional storms with calm, non-reactive prefrontal composure.",
      category: "Emotional Intelligence",
      cognitiveSkill: "Mirror Neuron Co-Regulation",
      emoji: "🕊️",
      gradient: "from-rose-500/20 to-amber-500/20",
      difficulty: "Adaptive",
      durationMinutes: 4,
      xpReward: 45,
      coinReward: 20,
      lifeScenarioExplanation: "Adolescent brains test boundaries; matching reactivity escalates conflict while calm anchors trust.",
      gameplayPrompt: "Select the de-escalating empathetic inquiry rather than the defensive lecture.",
      targetOutcome: "Deepens trust with teenage children and younger employees.",
    },
  ],

  "46-50+": [
    {
      id: "game-senior-semantic-web",
      ageTier: "46-50+",
      title: "Semantic Association Memory Web",
      tagline: "Strengthen paired-associate recall, names, faces, and rapid vocabulary access.",
      category: "Memory",
      cognitiveSkill: "Associative Neuroplastic Maintenance",
      emoji: "👑",
      gradient: "from-amber-500/20 to-yellow-500/20",
      difficulty: "Adaptive",
      durationMinutes: 5,
      xpReward: 50,
      coinReward: 25,
      lifeScenarioExplanation: "Cross-linking semantic concepts stimulates acetylcholine and fortifies long-term hippocampal plasticity.",
      gameplayPrompt: "Connect distant conceptual associations across multi-node memory clusters.",
      targetOutcome: "Preserves lightning-fast word and name retrieval.",
    },
    {
      id: "game-senior-motor-cognitive-sync",
      ageTier: "46-50+",
      title: "Dual-Task Motor & Cognitive Sync",
      tagline: "Combine rhythmic physical movement cues with rapid arithmetic and logical sorting.",
      category: "Speed",
      cognitiveSkill: "Cerebellar-Prefrontal Co-activation",
      emoji: "🧠",
      gradient: "from-emerald-500/20 to-teal-500/20",
      difficulty: "Medium",
      durationMinutes: 4,
      xpReward: 45,
      coinReward: 20,
      lifeScenarioExplanation: "Dual-task training triggers Brain-Derived Neurotrophic Factor (BDNF) to build new neural connections.",
      gameplayPrompt: "Tap alternating rhythm pulses while categorizing high-level strategic axioms.",
      targetOutcome: "Sharpens motor-cognitive agility and physical balance.",
    },
  ],
};

/**
 * Get customized games for a specific age tier
 */
export function getGamesForAgeTier(ageTier: AgeTierId): AgeCustomizedGame[] {
  return AGE_CUSTOMIZED_GAMES[ageTier] || AGE_CUSTOMIZED_GAMES["26-30"];
}
