import type { BrainQuestion } from "./types";

export const BRAIN_QUESTIONS_EN: BrainQuestion[] = [
  // ─── MEMORY (mem-1 to mem-10) ──────────────────────────────────────────────
  {
    id: "mem-1",
    category: "memory",
    difficulty: "beginner",
    question: "Your mother sends you to the market: rice, beans, tomatoes, and pepper. Which item did she NOT ask you to buy?",
    type: "multiple-choice",
    options: ["Rice", "Beans", "Ogi", "Pepper"],
    correctAnswer: "Ogi",
    explanation: "Your mother never mentioned ogi! You added that yourself. Memory is about retaining what you hear, not what you assume.",
    hint: "Think carefully about what was actually said.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-2",
    category: "memory",
    difficulty: "beginner",
    question: "How many colours are on the Nigerian flag?",
    type: "multiple-choice",
    options: ["One", "Two", "Three", "Four"],
    correctAnswer: "Two",
    explanation: "The Nigerian flag has just two colours — green and white. Green represents agriculture, and white represents peace.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-3",
    category: "memory",
    difficulty: "beginner",
    question: "Which of these is the odd one out? Cat, Dog, Eagle, Lion.",
    type: "multiple-choice",
    options: ["Cat", "Dog", "Eagle", "Lion"],
    correctAnswer: "Eagle",
    explanation: "The eagle is the only bird in the list. Spotting differences is a key memory skill called selective attention.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-4",
    category: "memory",
    difficulty: "beginner",
    question: "Type the name of the largest ocean in the world.",
    type: "text-input",
    correctAnswer: "Pacific",
    explanation: "The Pacific Ocean covers more area than all the land on Earth combined! Its name comes from the Latin word 'pacificus', meaning peaceful.",
    hint: "It starts with 'P' and sounds like 'peace-ific'.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-5",
    category: "memory",
    difficulty: "intermediate",
    question: "In the song 'Jollof Rice' by various Afrobeats artists, which country is often playfully blamed for having the best jollof?",
    type: "multiple-choice",
    options: ["Ghana", "Nigeria", "Senegal", "Sierra Leone"],
    correctAnswer: "Nigeria",
    explanation: "The jollof rice debate between Nigeria and Ghana is legendary! Both countries claim theirs is the best. Nigerians are particularly passionate about this.",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-6",
    category: "memory",
    difficulty: "intermediate",
    question: "Which of these Nollywood films was released first?",
    type: "multiple-choice",
    options: ["Living in Bondage", "The Wedding Party", "October 1", "Lionheart"],
    correctAnswer: "Living in Bondage",
    explanation: "Living in Bondage was released in 1992 and is considered one of the films that launched the modern Nollywood industry. It's a true classic!",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-7",
    category: "memory",
    difficulty: "intermediate",
    question: "Type the capital city of Kenya.",
    type: "text-input",
    correctAnswer: "Nairobi",
    explanation: "Nairobi is known as the 'Green City in the Sun'. It's the only capital city in the world with a national park within its borders!",
    hint: "It starts with 'N' and is in East Africa.",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-8",
    category: "memory",
    difficulty: "advanced",
    question: "Which mnemonic technique involves associating items with specific locations along a familiar route?",
    type: "multiple-choice",
    options: ["The Method of Loci", "Spaced Repetition", "Chunking", "Elaborative Rehearsal"],
    correctAnswer: "The Method of Loci",
    explanation: "The Method of Loci, also known as the 'Memory Palace', was used by ancient Greek orators. You visualise placing items at specific locations along a route you know well, like your walk to school.",
    xp: 20,
    coins: 8,
  },
  {
    id: "mem-9",
    category: "memory",
    difficulty: "advanced",
    question: "What is the term for the phenomenon where recalling a memory can accidentally alter it?",
    type: "multiple-choice",
    options: ["Misinformation Effect", "Cryptomnesia", "Déjà Vu", "Tip-of-the-Tongue"],
    correctAnswer: "Misinformation Effect",
    explanation: "Elizabeth Loftus's famous research showed that exposure to misleading information after an event can change how we remember it. This is why eyewitness testimony can be unreliable.",
    xp: 20,
    coins: 8,
  },
  {
    id: "mem-10",
    category: "memory",
    difficulty: "advanced",
    question: "In cognitive psychology, what does the acronym 'WM' stand for when discussing temporary storage of information?",
    type: "multiple-choice",
    options: ["Working Memory", "Wide Memory", "Weak Memory", "Weighted Memory"],
    correctAnswer: "Working Memory",
    explanation: "Working Memory, proposed by Alan Baddeley, is like your brain's notepad. It temporarily holds and manipulates information — like when you're doing mental maths or following directions in Lagos traffic.",
    xp: 20,
    coins: 8,
  },

  // ─── FOCUS (foc-1 to foc-10) ───────────────────────────────────────────────
  {
    id: "foc-1",
    category: "focus",
    difficulty: "beginner",
    question: "Which of these is most likely to improve your focus while studying?",
    type: "multiple-choice",
    options: ["Keeping your phone on the table", "Playing Afrobeats at full volume", "Removing distractions and finding a quiet spot", "Studying whilst watching Nollywood"],
    correctAnswer: "Removing distractions and finding a quiet spot",
    explanation: "Your brain can only truly multitask when tasks are automatic (like walking). For studying, a distraction-free environment helps your prefrontal cortex concentrate.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-2",
    category: "focus",
    difficulty: "beginner",
    question: "How long is one 'Pomodoro' in the popular Pomodoro Technique?",
    type: "multiple-choice",
    options: ["15 minutes", "25 minutes", "45 minutes", "60 minutes"],
    correctAnswer: "25 minutes",
    explanation: "The Pomodoro Technique uses 25-minute focus blocks followed by 5-minute breaks. Named after a tomato-shaped kitchen timer! It works because your brain thrives on structured intervals.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-3",
    category: "focus",
    difficulty: "beginner",
    question: "Type the name of the part of the brain responsible for controlling attention and decision-making.",
    type: "text-input",
    correctAnswer: "Prefrontal cortex",
    hint: "It's at the front of your brain.",
    explanation: "The prefrontal cortex is like the CEO of your brain. It handles planning, focus, and impulse control — it's why you can resist that extra piece of fried rice even when it looks delicious!",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-4",
    category: "focus",
    difficulty: "beginner",
    question: "Which activity best trains your sustained attention?",
    type: "multiple-choice",
    options: ["Scrolling through Instagram", "Reading a book for 30 minutes", "Switching between five apps", "Watching multiple short TikToks"],
    correctAnswer: "Reading a book for 30 minutes",
    explanation: "Reading a book requires sustained focus on one task. Social media trains your brain for rapid switching, which actually weakens your ability to concentrate deeply over time.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-5",
    category: "focus",
    difficulty: "intermediate",
    question: "In Lagos, the Danfo drivers are famous for their ability to navigate chaotic traffic. What cognitive skill does this best demonstrate?",
    type: "multiple-choice",
    options: ["Selective attention", "Long-term memory", "Emotional regulation", "Pattern recognition"],
    correctAnswer: "Selective attention",
    explanation: "Danfo drivers must constantly filter relevant information (other vehicles, passengers, traffic lights) from irrelevant distractions (hawkers, pedestrians, music blaring). This is selective attention in its most intense form!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-6",
    category: "focus",
    difficulty: "intermediate",
    question: "Which neurotransmitter is MOST directly associated with maintaining attention and focus?",
    type: "multiple-choice",
    options: ["Serotonin", "Dopamine", "Melatonin", "Endorphin"],
    correctAnswer: "Dopamine",
    explanation: "Dopamine is the 'motivation molecule'. It helps regulate attention and reward. Too little dopamine is linked to ADHD. Interesting fact — dark chocolate and exercise boost dopamine naturally!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-7",
    category: "focus",
    difficulty: "intermediate",
    question: "Type the name of the psychological state where you are so absorbed in an activity that time seems to disappear.",
    type: "text-input",
    correctAnswer: "Flow",
    explanation: "Flow state was named by psychologist Mihaly Csikszentmihalyi. It occurs when a task is challenging enough to engage you but not so hard that you feel overwhelmed. Athletes, musicians, and coders all chase this feeling!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-8",
    category: "focus",
    difficulty: "advanced",
    question: "Which of these is a genuine neurological phenomenon that causes attention lapses during repetitive tasks?",
    type: "multiple-choice",
    options: ["Attentional blink", "Vigilance decrement", "Change blindness", "Inattentional deafness"],
    correctAnswer: "Vigilance decrement",
    explanation: "The vigilance decrement is the decline in attention during prolonged monitoring tasks. Research shows most people can only maintain peak vigilance for about 20 minutes — which is why air traffic controllers work in shifts!",
    xp: 20,
    coins: 8,
  },
  {
    id: "foc-9",
    category: "focus",
    difficulty: "advanced",
    question: "According to research, what is the optimal ratio of focused work to break time for peak cognitive performance?",
    type: "multiple-choice",
    options: ["50 minutes work : 10 minutes break", "90 minutes work : 20 minutes break", "25 minutes work : 5 minutes break", "120 minutes work : 30 minutes break"],
    correctAnswer: "50 minutes work : 10 minutes break",
    explanation: "While the Pomodoro uses 25:5, research on ultradian rhythms suggests 50-90 minutes of focused work followed by a proper break aligns with your brain's natural cycles. The 50:10 ratio is considered optimal for most people.",
    xp: 20,
    coins: 8,
  },
  {
    id: "foc-10",
    category: "focus",
    difficulty: "advanced",
    question: "In attention research, what does the 'Posner paradigm' primarily measure?",
    type: "multiple-choice",
    options: ["Emotional regulation", "Spatial attention and alerting", "Memory consolidation", "Language processing"],
    correctAnswer: "Spatial attention and alerting",
    explanation: "Michael Posner's attention network model identifies three networks: alerting (readiness), orienting (directing attention), and executive (conflict resolution). The Posner cueing task is one of the most cited experiments in cognitive psychology.",
    xp: 20,
    coins: 8,
  },

  // ─── THINKING (thk-1 to thk-10) ────────────────────────────────────────────
  {
    id: "thk-1",
    category: "thinking",
    difficulty: "beginner",
    question: "A farmer has 15 cows. All but 8 died. How many cows are left?",
    type: "multiple-choice",
    options: ["7", "8", "15", "0"],
    correctAnswer: "8",
    explanation: "This is a classic trick question! 'All but 8' means 8 survived. Your brain wanted to subtract 8 from 15, but the answer was hiding in plain sight. Critical thinking means reading carefully!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-2",
    category: "thinking",
    difficulty: "beginner",
    question: "Which logical fallacy is demonstrated when someone says 'Everyone in my area does it, so it must be right'?",
    type: "multiple-choice",
    options: ["Ad Hominem", "Bandwagon Fallacy", "Straw Man", "False Dilemma"],
    correctAnswer: "Bandwagon Fallacy",
    explanation: "The Bandwagon Fallacy (argumentum ad populum) assumes something is true or good because many people do it. But popularity doesn't equal correctness — think of how many people believed the Earth was flat!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-3",
    category: "thinking",
    difficulty: "beginner",
    question: "If all roses are flowers, and some flowers fade quickly, can we conclude that some roses fade quickly?",
    type: "multiple-choice",
    options: ["Yes, definitely", "No, not necessarily", "Only in summer", "Only red roses"],
    correctAnswer: "No, not necessarily",
    explanation: "This is a syllogism test. 'Some flowers fade quickly' doesn't tell us WHICH flowers. The roses might be in the group that doesn't fade quickly. Logical thinking requires precise reasoning, not assumptions!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-4",
    category: "thinking",
    difficulty: "beginner",
    question: "Type the name of the thinking error where you only notice information that confirms what you already believe.",
    type: "text-input",
    correctAnswer: "Confirmation bias",
    hint: "It starts with 'confirmation'.",
    explanation: "Confirmation bias is why people who believe superstitions only remember the times they 'came true'. Your brain is wired to seek confirming evidence — you have to actively fight this!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-5",
    category: "thinking",
    difficulty: "intermediate",
    question: "In Nigeria, someone says 'My uncle's friend's neighbour won the lottery after touching a tortoise.' What reasoning error is at play?",
    type: "multiple-choice",
    options: ["Post Hoc Fallacy", "Anecdotal Evidence", "Both of these", "Neither"],
    correctAnswer: "Both of these",
    explanation: "This combines the Post Hoc Fallacy (assuming one event caused another because it came before) with Anecdotal Evidence (using a single story as proof). One person's experience doesn't make a scientific law!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-6",
    category: "thinking",
    difficulty: "intermediate",
    question: "A businessman in Lagos sells shoes for ₦15,000 and makes a 25% profit. What was his cost price?",
    type: "multiple-choice",
    options: ["₦11,250", "₦12,000", "₦12,500", "₦10,000"],
    correctAnswer: "₦12,000",
    explanation: "If the selling price is 125% of cost (100% + 25% profit), then: Cost = ₦15,000 ÷ 1.25 = ₦12,000. Mental maths like this is essential for everyday thinking!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-7",
    category: "thinking",
    difficulty: "intermediate",
    question: "Which type of thinking involves generating multiple possible solutions to a problem?",
    type: "multiple-choice",
    options: ["Convergent thinking", "Divergent thinking", "Lateral thinking", "Linear thinking"],
    correctAnswer: "Divergent thinking",
    explanation: "Divergent thinking is the creative opposite of convergent thinking (finding the single 'right' answer). Brainstorming sessions use divergent thinking — there are no wrong answers, only possibilities!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-8",
    category: "thinking",
    difficulty: "advanced",
    question: "In propositional logic, what is the truth value of 'If it is raining, then the ground is wet' when it IS raining but the ground is NOT wet?",
    type: "multiple-choice",
    options: ["True", "False", "Cannot be determined", "Paradox"],
    correctAnswer: "False",
    explanation: "In formal logic, a conditional statement 'If P then Q' is only false when P is true and Q is false. If it's raining but the ground isn't wet (maybe there's a roof!), the statement is false. This is the foundation of mathematical logic.",
    xp: 20,
    coins: 8,
  },
  {
    id: "thk-9",
    category: "thinking",
    difficulty: "advanced",
    question: "What is the 'Dunning-Kruger effect'?",
    type: "multiple-choice",
    options: [
      "Low-ability individuals overestimate their competence",
      "High-ability individuals underestimate their competence",
      "Both of the above",
      "People become more skilled with age"
    ],
    correctAnswer: "Both of the above",
    explanation: "The Dunning-Kruger effect shows that people with low ability at a task tend to overestimate their ability, while experts often underestimate theirs. It's named after psychologists David Dunning and Justin Kruger.",
    xp: 20,
    coins: 8,
  },
  {
    id: "thk-10",
    category: "thinking",
    difficulty: "advanced",
    question: "Which philosopher proposed the 'Trolley Problem' thought experiment about moral decision-making?",
    type: "multiple-choice",
    options: ["Immanuel Kant", "Philippa Foot", "John Stuart Mill", "Aristotle"],
    correctAnswer: "Philippa Foot",
    explanation: "Philippa Foot introduced the Trolley Problem in 1967. It asks whether it's moral to divert a trolley to kill one person instead of five. It's used to explore utilitarian versus deontological ethics — there's no easy answer!",
    xp: 20,
    coins: 8,
  },

  // ─── LEARNING (lrn-1 to lrn-10) ───────────────────────────────────────────
  {
    id: "lrn-1",
    category: "learning",
    difficulty: "beginner",
    question: "Which study technique involves testing yourself on material rather than just re-reading it?",
    type: "multiple-choice",
    options: ["Highlighting", "Passive reading", "Active recall", "Copying notes"],
    correctAnswer: "Active recall",
    explanation: "Active recall (or retrieval practice) is one of the most effective study techniques backed by science. Every time you force your brain to retrieve information, the memory gets stronger!",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-2",
    category: "learning",
    difficulty: "beginner",
    question: "Type the name of the curve that shows how quickly we forget information over time.",
    type: "text-input",
    correctAnswer: "Forgetting curve",
    hint: "Named by a German psychologist named Hermann Ebbinghaus.",
    explanation: "The Ebbinghaus Forgetting Curve shows that we forget about 70% of new information within 24 hours without review. This is why spaced repetition is so powerful!",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-3",
    category: "learning",
    difficulty: "beginner",
    question: "Which of these is the BEST way to remember something you've just learned?",
    type: "multiple-choice",
    options: ["Read it 10 times quickly", "Teach it to someone else", "Write it once and never look at it", "Skip to the next topic immediately"],
    correctAnswer: "Teach it to someone else",
    explanation: "The Feynman Technique! Teaching forces you to organise your thoughts, identify gaps in understanding, and explain concepts simply. If you can teach it, you truly understand it.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-4",
    category: "learning",
    difficulty: "beginner",
    question: "How many times should you review new material within the first week to combat the forgetting curve?",
    type: "multiple-choice",
    options: ["Once", "At least 3-4 times", "Only during exams", "Never review"],
    correctAnswer: "At least 3-4 times",
    explanation: "Spaced repetition shows that reviewing at increasing intervals (1 day, 3 days, 7 days) helps transfer information to long-term memory. Your brain needs repeated exposure to 'lock in' learning!",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-5",
    category: "learning",
    difficulty: "intermediate",
    question: "In the Yoruba language, 'omo' can mean different things depending on context. What learning concept does this demonstrate?",
    type: "multiple-choice",
    options: ["Cognitive load theory", "Context-dependent memory", "Schema theory", "Transfer-appropriate processing"],
    correctAnswer: "Context-dependent memory",
    explanation: "Context-dependent memory shows that recall is better when the environment matches the learning context. In Yoruba, 'omo' means 'child' but in other contexts can mean other things — your brain uses context to decode meaning!",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-6",
    category: "learning",
    difficulty: "intermediate",
    question: "What is 'interleaving' in the context of learning strategies?",
    type: "multiple-choice",
    options: [
      "Studying one topic for a very long time",
      "Mixing different topics or types of problems during study",
      "Studying only at night",
      "Skipping difficult topics"
    ],
    correctAnswer: "Mixing different topics or types of problems during study",
    explanation: "Interleaving means mixing different subjects or problem types in one study session. It feels harder but produces better long-term learning because your brain practices switching between concepts!",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-7",
    category: "learning",
    difficulty: "intermediate",
    question: "Type the term for the phenomenon where practicing a skill in different environments helps you apply it more flexibly.",
    type: "text-input",
    correctAnswer: "Varied practice",
    hint: "Think about changing where and how you practice.",
    explanation: "Varied practice (or contextual interference) means practising in different settings, with different tools, or at different times. Athletes who train in varied conditions perform better in unpredictable game situations!",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-8",
    category: "learning",
    difficulty: "advanced",
    question: "Which cognitive science concept explains why students who study everything the night before perform worse than those who study gradually?",
    type: "multiple-choice",
    options: ["Cognitive load theory", "Spacing effect", "Serial position effect", "Zeigarnik effect"],
    correctAnswer: "Spacing effect",
    explanation: "The spacing effect, demonstrated by Ebbinghaus, shows that distributed practice over time produces stronger, more durable memories than massed practice (cramming). Your brain literally needs time to consolidate learning!",
    xp: 20,
    coins: 8,
  },
  {
    id: "lrn-9",
    category: "learning",
    difficulty: "advanced",
    question: "In educational psychology, what does 'metacognition' refer to?",
    type: "multiple-choice",
    options: ["Learning about science", "Thinking about your own thinking and learning processes", "Memorising facts quickly", "Group study techniques"],
    correctAnswer: "Thinking about your own thinking and learning processes",
    explanation: "Metacognition is 'thinking about thinking'. It includes planning your study approach, monitoring your understanding, and evaluating your learning. Students with strong metacognitive skills learn more effectively!",
    xp: 20,
    coins: 8,
  },
  {
    id: "lrn-10",
    category: "learning",
    difficulty: "advanced",
    question: "According to cognitive load theory, what are the three types of cognitive load that affect learning?",
    type: "multiple-choice",
    options: [
      "Intrinsic, extraneous, and germane",
      "Visual, auditory, and kinesthetic",
      "Short-term, long-term, and working",
      "Schema, automation, and practice"
    ],
    correctAnswer: "Intrinsic, extraneous, and germane",
    explanation: "Intrinsic load is the difficulty of the material itself, extraneous load is unnecessary complexity (bad design), and germane load is the effort to build understanding. Good teaching reduces extraneous load to free up space for learning!",
    xp: 20,
    coins: 8,
  },

  // ─── CREATIVITY (crv-1 to crv-10) ─────────────────────────────────────────
  {
    id: "crv-1",
    category: "creativity",
    difficulty: "beginner",
    question: "How many uses can you think of for a newspaper? Which creativity technique involves listing as many uses as possible in a set time?",
    type: "multiple-choice",
    options: ["Mind mapping", "Brainstorming", "Random word association", "SCAMPER"],
    correctAnswer: "Brainstorming",
    explanation: "Brainstorming, developed by Alex Osborn, encourages generating as many ideas as possible without judging them. Quantity leads to quality — even silly ideas can spark brilliant ones!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-2",
    category: "creativity",
    difficulty: "beginner",
    question: "Type the name of the famous artist who painted the Mona Lisa.",
    type: "text-input",
    correctAnswer: "Leonardo da Vinci",
    hint: "He was Italian and lived during the Renaissance.",
    explanation: "Leonardo da Vinci was the ultimate Renaissance man — artist, scientist, inventor, and more. He carried a notebook everywhere to sketch ideas. Note-taking is a creativity superpower!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-3",
    category: "creativity",
    difficulty: "beginner",
    question: "Afrobeats artist Burna Boy is known for blending multiple genres. What creativity skill does this represent?",
    type: "multiple-choice",
    options: ["Convergent thinking", "Combinational creativity", "Algorithmic thinking", "Rote memorisation"],
    correctAnswer: "Combinational creativity",
    explanation: "Combinational creativity involves connecting existing ideas in novel ways. Burna Boy blends Afrobeats with dancehall, reggae, pop, and hip-hop — taking familiar elements and creating something entirely new!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-4",
    category: "creativity",
    difficulty: "beginner",
    question: "Which of these is NOT a barrier to creativity?",
    type: "multiple-choice",
    options: ["Fear of failure", "Curiosity", "Perfectionism", "Overthinking"],
    correctAnswer: "Curiosity",
    explanation: "Curiosity is actually a CATALYST for creativity, not a barrier! Fear of failure, perfectionism, and overthinking all kill creative ideas before they have a chance to develop.",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-5",
    category: "creativity",
    difficulty: "intermediate",
    question: "The SCAMPER technique includes Substitute, Combine, Adapt, Modify, Put to other uses, Eliminate, and what?",
    type: "multiple-choice",
    options: ["Reverse", "Repeat", "Review", "Remove"],
    correctAnswer: "Reverse",
    explanation: "SCAMPER is a creative thinking tool. 'Reverse' means flipping or rearranging things. What if buses came to you instead of you going to the bus stop? That's how ride-hailing apps were born!",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-6",
    category: "creativity",
    difficulty: "intermediate",
    question: "Nollywood's low-budget filmmaking style led to an explosion of creative storytelling. In psychology, what is this phenomenon called?",
    type: "multiple-choice",
    options: ["Creative constraint", "Analysis paralysis", "Decision fatigue", "Choice overload"],
    correctAnswer: "Creative constraint",
    explanation: "Creative constraint theory shows that limitations can actually boost creativity! Nollywood filmmakers couldn't afford Hollywood budgets, so they innovated with storytelling, dialogue, and cultural themes instead.",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-7",
    category: "creativity",
    difficulty: "intermediate",
    question: "Type the name of the thinking technique where you deliberately challenge assumptions by asking 'What if the opposite were true?'",
    type: "text-input",
    correctAnswer: "Reverse thinking",
    hint: "You flip your assumptions upside down.",
    explanation: "Reverse thinking (or inversion) is a powerful creativity tool. Instead of asking 'How do I succeed?', ask 'How would I guarantee failure?' — then avoid those things! It reveals blind spots your normal thinking misses.",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-8",
    category: "creativity",
    difficulty: "advanced",
    question: "In creativity research, what is the 'incubation effect'?",
    type: "multiple-choice",
    options: [
      "Creativity improves when you stop actively working on a problem",
      "Creative people are born, not made",
      "Group brainstorming always produces better ideas",
      "Creativity decreases with age"
    ],
    correctAnswer: "Creativity improves when you stop actively working on a problem",
    explanation: "The incubation effect shows that stepping away from a problem allows your unconscious mind to continue working on it. Many famous discoveries — Archimedes' bathtub, Newton's apple — happened during moments of rest!",
    xp: 20,
    coins: 8,
  },
  {
    id: "crv-9",
    category: "creativity",
    difficulty: "advanced",
    question: "What is the 'remote associates test' (RAT) used to measure in psychology?",
    type: "multiple-choice",
    options: ["Emotional intelligence", "Convergent creative thinking", "Spatial reasoning", "Linguistic ability"],
    correctAnswer: "Convergent creative thinking",
    explanation: "The RAT asks you to find a word that connects three seemingly unrelated words (e.g., 'cottage', 'swiss', 'cake' → 'cheese'). It measures convergent creativity — finding the single best answer that links ideas together.",
    xp: 20,
    coins: 8,
  },
  {
    id: "crv-10",
    category: "creativity",
    difficulty: "advanced",
    question: "Which psychologist proposed the 'Four C' model of creativity: Mini-c, Little-c, Pro-c, and Big-C?",
    type: "multiple-choice",
    options: ["Mihaly Csikszentmihalyi", "Mark Runco", "Howard Gardner", "Robert Sternberg"],
    correctAnswer: "Mark Runco",
    explanation: "Mark Runco's Four C model shows that creativity exists on a spectrum — from personal insights (Mini-c) to everyday creativity (Little-c) to professional (Pro-c) to eminent (Big-C, like Shakespeare). Everyone has creativity at some level!",
    xp: 20,
    coins: 8,
  },

  // ─── HEALTH (hlth-1 to hlth-10) ────────────────────────────────────────────
  {
    id: "hlth-1",
    category: "health",
    difficulty: "beginner",
    question: "How many hours of sleep do most teenagers (13–18) need per night according to the NHS?",
    type: "multiple-choice",
    options: ["5–6 hours", "6–7 hours", "8–10 hours", "11–12 hours"],
    correctAnswer: "8–10 hours",
    explanation: "The NHS recommends 8–10 hours for teenagers. Your brain does critical maintenance work during sleep — consolidating memories, clearing toxins, and repairing cells. Skimping on sleep literally makes you less intelligent!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-2",
    category: "health",
    difficulty: "beginner",
    question: "Which of these foods is the BEST brain fuel?",
    type: "multiple-choice",
    options: ["Sweets and candy", "Eggs, fish, and nuts", "Fizzy drinks", "Crisps and biscuits"],
    correctAnswer: "Eggs, fish, and nuts",
    explanation: "Eggs contain choline (memory), fish has omega-3s (brain cell structure), and nuts provide vitamin E (brain protection). Your brain uses 20% of your daily calories — feed it well!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-3",
    category: "health",
    difficulty: "beginner",
    question: "Type the name of the chemical released during exercise that improves mood and reduces stress.",
    type: "text-input",
    correctAnswer: "Endorphins",
    hint: "It rhymes with 'endorphins'... wait, that IS the word!",
    explanation: "Endorphins are your brain's natural painkillers and mood boosters. A 30-minute walk or dance session to Afrobeats releases them! This is why exercise is sometimes called nature's antidepressant.",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-4",
    category: "health",
    difficulty: "beginner",
    question: "How much water should you aim to drink daily for optimal brain function?",
    type: "multiple-choice",
    options: ["1–2 glasses", "4–5 glasses", "6–8 glasses", "12+ glasses"],
    correctAnswer: "6–8 glasses",
    explanation: "Your brain is about 75% water. Even mild dehydration (1-2%) can impair concentration, mood, and memory. Keep a water bottle handy — your brain will thank you!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-5",
    category: "health",
    difficulty: "intermediate",
    question: "In Lagos, the daily traffic jam can last 3+ hours. Which brain structure is most affected by chronic stress from situations like this?",
    type: "multiple-choice",
    options: ["Hippocampus", "Amygdala", "Prefrontal cortex", "Cerebellum"],
    correctAnswer: "Hippocampus",
    explanation: "Chronic stress releases cortisol which literally shrinks the hippocampus — the memory and learning centre. This is why long-term stress can make it harder to remember things and learn new information!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-6",
    category: "health",
    difficulty: "intermediate",
    question: "What is the recommended screen time limit before bed for optimal sleep quality?",
    type: "multiple-choice",
    options: ["30 minutes", "1 hour", "2 hours", "No limit"],
    correctAnswer: "1 hour",
    explanation: "Blue light from screens suppresses melatonin production (your sleep hormone). Experts recommend stopping screen use at least 1 hour before bed. Try reading a physical book instead!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-7",
    category: "health",
    difficulty: "intermediate",
    question: "Type the name of the part of the brain responsible for balance and coordination.",
    type: "text-input",
    correctAnswer: "Cerebellum",
    hint: "It's at the back of your brain and means 'little brain' in Latin.",
    explanation: "The cerebellum contains more neurons than the rest of the brain combined! It coordinates movement, balance, and is increasingly linked to cognitive functions like attention and language.",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-8",
    category: "health",
    difficulty: "advanced",
    question: "What is the 'glymphatic system' and why is it important for brain health?",
    type: "multiple-choice",
    options: [
      "A digestive system for the brain that only works during sleep",
      "A network of blood vessels in the brain",
      "A type of brain cell",
      "The brain's electrical signalling system"
    ],
    correctAnswer: "A digestive system for the brain that only works during sleep",
    explanation: "The glymphatic system is your brain's waste-clearance system. It's most active during deep sleep, flushing out toxins including beta-amyloid (linked to Alzheimer's). This is why sleep is literally brain maintenance!",
    xp: 20,
    coins: 8,
  },
  {
    id: "hlth-9",
    category: "health",
    difficulty: "advanced",
    question: "Research shows that Mediterranean diet reduces cognitive decline risk. Which component is considered most neuroprotective?",
    type: "multiple-choice",
    options: ["Olive oil and its polyphenols", "Red wine", "Pasta", "Cheese"],
    correctAnswer: "Olive oil and its polyphenols",
    explanation: "Extra virgin olive oil contains oleocanthal and oleuropein, which have powerful anti-inflammatory and antioxidant effects on brain cells. These compounds help clear amyloid plaques and protect neurons from damage.",
    xp: 20,
    coins: 8,
  },
  {
    id: "hlth-10",
    category: "health",
    difficulty: "advanced",
    question: "What is 'neuroplasticity' and why is it crucial for lifelong brain health?",
    type: "multiple-choice",
    options: [
      "The brain's ability to reorganise and form new neural connections throughout life",
      "The fixed structure of the brain that doesn't change after childhood",
      "A type of brain surgery",
      "The brain's resistance to all damage"
    ],
    correctAnswer: "The brain's ability to reorganise and form new neural connections throughout life",
    explanation: "Neuroplasticity means your brain can change and adapt at ANY age. Learning new skills, exercise, social connection, and novel experiences all promote neuroplasticity. It's never too late to train your brain!",
    xp: 20,
    coins: 8,
  },

  // ─── EMOTIONAL INTELLIGENCE (ei-1 to ei-10) ───────────────────────────────
  {
    id: "ei-1",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Your friend gets angry when you arrive late. Which response shows the highest emotional intelligence?",
    type: "multiple-choice",
    options: [
      "Tell them they're overreacting",
      "Ignore them completely",
      "Acknowledge their feelings and apologise sincerely",
      "Get angry back at them"
    ],
    correctAnswer: "Acknowledge their feelings and apologise sincerely",
    explanation: "Emotional intelligence starts with recognising and validating others' feelings. A genuine apology shows empathy — you understand their perspective without being defensive. This builds trust and stronger relationships.",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-2",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "What is the term for the ability to understand and manage your own emotions?",
    type: "multiple-choice",
    options: ["Emotional awareness", "Self-regulation", "Empathy", "Social skills"],
    correctAnswer: "Self-regulation",
    explanation: "Self-regulation is about managing your emotional responses. It's not about suppressing emotions (that's unhealthy) but about choosing how to respond. Think of it as having an internal 'pause button'.",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-3",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Type the name of the psychologist who popularised the concept of 'Emotional Intelligence' in 1995.",
    type: "text-input",
    correctAnswer: "Daniel Goleman",
    hint: "His surname starts with 'G' and he wrote a famous book on the topic.",
    explanation: "Daniel Goleman's 1995 book 'Emotional Intelligence' showed that EQ (emotional quotient) can be more important than IQ for success in life. He identified five key components: self-awareness, motivation, self-regulation, empathy, and social skills.",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-4",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "When you feel overwhelmed by anger, which technique is most effective for calming down quickly?",
    type: "multiple-choice",
    options: ["Punching a wall", "Taking 5 slow, deep breaths", "Shouting at someone", "Ignoring the feeling completely"],
    correctAnswer: "Taking 5 slow, deep breaths",
    explanation: "Deep breathing activates your parasympathetic nervous system — your body's 'rest and digest' mode. It lowers your heart rate and reduces cortisol. This technique works even in the middle of Lagos traffic!",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-5",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "In Yoruba culture, there's a saying 'Òwe l'ẹ́ṣin ọ̀rọ̀' (Proverbs are the horses of speech). What emotional intelligence skill does using proverbs demonstrate?",
    type: "multiple-choice",
    options: [
      "Self-awareness",
      "Social awareness and empathy",
      "Self-regulation",
      "Emotional expression"
    ],
    correctAnswer: "Social awareness and empathy",
    explanation: "Proverbs are a sophisticated way of communicating difficult truths with emotional sensitivity. Using them shows you understand your audience's emotions and cultural context — a key aspect of social awareness in emotional intelligence.",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-6",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "What is 'emotional labour' and why is it relevant to workplace wellbeing?",
    type: "multiple-choice",
    options: [
      "Working long hours on emotional tasks",
      "Managing your displayed emotions as part of your job role",
      "Being paid to attend therapy",
      "Doing creative work for a living"
    ],
    correctAnswer: "Managing your displayed emotions as part of your job role",
    explanation: "Emotional labour, coined by Arlie Hochschild, is when you must display certain emotions at work regardless of how you actually feel. Customer service workers, teachers, and healthcare workers do this daily — it's exhausting and can lead to burnout.",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-7",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Type the term for when you unconsciously adopt the emotions of people around you.",
    type: "text-input",
    correctAnswer: "Emotional contagion",
    hint: "Think of emotions spreading like a virus.",
    explanation: "Emotional contagion is why one person's bad mood can ruin an entire office! Mirror neurons in your brain automatically mimic others' emotional expressions, which then trigger the corresponding emotion in you. Choose your circle wisely!",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-8",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "What is the 'Johari Window' and how is it used in emotional intelligence development?",
    type: "multiple-choice",
    options: [
      "A tool for understanding self-awareness through feedback from others",
      "A Japanese meditation technique",
      "A type of personality test with four colours",
      "A method for conflict resolution in couples"
    ],
    correctAnswer: "A tool for understanding self-awareness through feedback from others",
    explanation: "The Johari Window, created by Joseph Luft and Harrington Ingham, has four quadrants: Open (known to self and others), Blind (unknown to self), Hidden (known to self only), and Unknown. Expanding the 'Open' area through feedback improves emotional intelligence!",
    xp: 20,
    coins: 8,
  },
  {
    id: "ei-9",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "Research shows that emotional intelligence predicts success better than IQ in many fields. Which specific aspect of EQ is the strongest predictor of leadership effectiveness?",
    type: "multiple-choice",
    options: [
      "Self-awareness",
      "Social awareness (empathy)",
      "Relationship management",
      "Self-regulation"
    ],
    correctAnswer: "Relationship management",
    explanation: "While all EQ components matter, relationship management — the ability to inspire, influence, develop others, and manage conflict — is the strongest predictor of leadership effectiveness. It combines all other EQ skills into action!",
    xp: 20,
    coins: 8,
  },
  {
    id: "ei-10",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "In African communal philosophy, the concept of 'Ubuntu' relates to emotional intelligence. What does 'Ubuntu' emphasise?",
    type: "multiple-choice",
    options: [
      "Individual achievement above all else",
      "I am because we are — interconnectedness and communal emotional wellbeing",
      "Suppressing emotions for the greater good",
      "Emotional independence from others"
    ],
    correctAnswer: "I am because we are — interconnectedness and communal emotional wellbeing",
    explanation: "Ubuntu, a Nguni Bantu term, captures the essence of emotional intelligence in African philosophy. It emphasises that our humanity is defined through our relationships with others. Archbishop Desmond Tutu described it as the essence of being human — recognizing that our wellbeing is inseparable from the wellbeing of others.",
    xp: 20,
    coins: 8,
  },
];
