import type { BrainQuestion } from "./types";

export const BRAIN_QUESTIONS_PCM: BrainQuestion[] = [
  // ============================================================
  // MEMORY (mem-1 to mem-10)
  // ============================================================
  {
    id: "mem-1",
    category: "memory",
    difficulty: "beginner",
    question: "Your mama send you market: rice, beans, tomatoes, and pepper. Which one she NO send you buy?",
    type: "multiple-choice",
    options: ["Rice", "Beans", "Ogi", "Pepper"],
    correctAnswer: "Ogi",
    explanation: "Your mama never mention ogi! Na wetin you add yourself. Memory na about wetin you hear, not wetin you expect.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-2",
    category: "memory",
    difficulty: "beginner",
    question: "You dey queue for bus stop. You enter danfo and your stop na Lekki. Driver pass Lekki. Where you dey now?",
    type: "multiple-choice",
    options: ["Lekki Phase 1", "Ajah", "Obalende", "VI"],
    correctAnswer: "Ajah",
    explanation: "Once driver pass your bus stop, na next stop you go land. This na simple memory — track where you dey and where you suppose dey!",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-3",
    category: "memory",
    difficulty: "beginner",
    question: "You see one babe for party. She wear yellow top and black jean. Next day, you see her for office. What you go remember first?",
    type: "multiple-choice",
    options: ["Her phone number", "Her yellow top", "Her name", "Her hairstyle"],
    correctAnswer: "Her yellow top",
    explanation: "Visual memory dey strong pass! You go remember wetin you see before wetin you hear. Na how our brain dey work.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-4",
    category: "memory",
    difficulty: "beginner",
    question: "Your phone ring, you no check am. Your friend talk say na mama call. How you go remember to call back?",
    type: "multiple-choice",
    options: ["Set reminder for your phone", "Put cloth for your door", "Forget am completely", "Go sleep"],
    correctAnswer: "Set reminder for your phone",
    explanation: "External memory na your friend! Technology dey help us remember wetin our brain fit forget. Use wetin you get.",
    hint: "Think about tools wey dey help us remember things.",
    xp: 10,
    coins: 3,
  },
  {
    id: "mem-5",
    category: "memory",
    difficulty: "intermediate",
    question: "You dey learn new route go work. First week, you dey check Google Maps. Second week, you remember some landmarks. What type of memory be this?",
    type: "multiple-choice",
    options: ["Short-term memory", "Spatial memory", "Muscle memory", "Sensory memory"],
    correctAnswer: "Spatial memory",
    explanation: "Spatial memory na how your brain dey store and recall locations. That one wey help you remember where things dey for house — even in NEPA darkness!",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-6",
    category: "memory",
    difficulty: "intermediate",
    question: "You read something last night. This morning, you no fit remember am well. What you fit do to remember better?",
    type: "multiple-choice",
    options: ["Read am again one time sharp sharp", "Sleep well and read am again", "Shout am ten times", "Forget am"],
    correctAnswer: "Sleep well and read am again",
    explanation: "Sleep dey help brain consolidate memory. When you sleep, your brain dey arrange wetin you learn like cloth for wardrobe!",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-7",
    category: "memory",
    difficulty: "intermediate",
    question: "Text-input: Your friend give you phone number 081-3456-7890. How you go remember the middle part?",
    type: "text-input",
    correctAnswer: "3456",
    explanation: "We dey always break numbers into smaller chunks. Chunks dey help brain hold information better. Try am with any number wey you wan remember!",
    xp: 15,
    coins: 5,
  },
  {
    id: "mem-8",
    category: "memory",
    difficulty: "advanced",
    question: "You dey prepare for exam. You study one topic finish. To remember am for long time, wetin be the best strategy?",
    type: "multiple-choice",
    options: ["Read am ten times one night", "Space your reading over days", "Copy am ten times", "Read only once very well"],
    correctAnswer: "Space your reading over days",
    explanation: "Spaced repetition na the king! Your brain dey remember better when you spread your reading. E be like say you dey water plant small small — e go grow better pass you pour bucket one time.",
    xp: 20,
    coins: 8,
  },
  {
    id: "mem-9",
    category: "memory",
    difficulty: "advanced",
    question: "You watch one Nollywood movie last month. Your friend ask you about the ending. You remember some scenes but not all. Why?",
    type: "multiple-choice",
    options: ["Your brain dey lazy", "Encoding failure — you no pay attention to some parts", "The movie no good", "You too old"],
    correctAnswer: "Encoding failure — you no pay attention to some parts",
    explanation: "Na encoding failure! If you no pay attention to something properly when you first see am, your brain no go store am well. E be like say you no put cloth well for wardrobe — when you wan find am, e dey miss!",
    xp: 20,
    coins: 8,
  },
  {
    id: "mem-10",
    category: "memory",
    difficulty: "advanced",
    question: "Text-input: Your jollof rice get 5 key ingredients. Name 3 of them to test your semantic memory.",
    type: "text-input",
    correctAnswer: "rice",
    explanation: "Semantic memory na wetin you know about the world — facts, knowledge, and meanings. Jollof rice always get rice, tomatoes, pepper, onions, and seasoning. Na common knowledge wey everybody suppose know!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // FOCUS (foc-1 to foc-10)
  // ============================================================
  {
    id: "foc-1",
    category: "focus",
    difficulty: "beginner",
    question: "You dey read, NEPA light go. Generator start. Your neighbor dey play Afrobeats loud. Wetin go help you concentrate?",
    type: "multiple-choice",
    options: ["Shout at neighbor", "Use earpiece or go quiet place", "Join the party", "Stop reading"],
    correctAnswer: "Use earpiece or go quiet place",
    explanation: "No go fight noise with noise! Find better environment to focus. Your brain dey work better when disturbance dey low.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-2",
    category: "focus",
    difficulty: "beginner",
    question: "You dey do assignment, your phone dey buzz for message. Wetin the best thing to do?",
    type: "multiple-choice",
    options: ["Check every message sharp sharp", "Turn phone face down or put for silent", "Reply all messages first", "Throw phone comot"],
    correctAnswer: "Turn phone face down or put for silent",
    explanation: "Phone na the biggest thief of focus! If you no see notification, you no go want check am. Simple trick, big result.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-3",
    category: "focus",
    difficulty: "beginner",
    question: "You want chop amala. You dey think about am while reading. How you go focus?",
    type: "multiple-choice",
    options: ["Go chop amala first", "Tell yourself: after reading I go chop", "Carry amala come reading table", "Stop reading permanently"],
    correctAnswer: "Tell yourself: after reading I go chop",
    explanation: "Reward system dey work well! If you promise yourself something nice after you finish, your brain go dey motivated to focus.",
    hint: "Think about delay gratification.",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-4",
    category: "focus",
    difficulty: "beginner",
    question: "You dey watch tutorial video, your mind dey wander to Wizkid concert. What be the sign?",
    type: "multiple-choice",
    options: ["You don dey tired", "The tutorial no clear", "Your attention span dey drop", "All of the above"],
    correctAnswer: "All of the above",
    explanation: "When your mind dey shift, na sign say something no right. You fit dey tired, or the thing no sweet you. Recognize am, adjust, and continue!",
    xp: 10,
    coins: 3,
  },
  {
    id: "foc-5",
    category: "focus",
    difficulty: "intermediate",
    question: "You dey work on project. Every 25 minutes, you take 5 minutes break. What they call this method?",
    type: "multiple-choice",
    options: ["Lagos traffic method", "Pomodoro technique", "Jollof method", "Nollywood method"],
    correctAnswer: "Pomodoro technique",
    explanation: "Pomodoro technique na top method! Work 25 minutes, rest 5 minutes. Your brain dey function better when e get small breaks to recharge. E be like say you dey charge phone — you no fit use am till flat!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-6",
    category: "focus",
    difficulty: "intermediate",
    question: "You dey do two things at once — dey reply WhatsApp and dey write report. Your report get errors. Why?",
    type: "multiple-choice",
    options: ["Your boss na ogboni", "Multitasking dey reduce quality", "Report no important", "WhatsApp na virus"],
    correctAnswer: "Multitasking dey reduce quality",
    explanation: "True talk — multitasking na myth! Your brain no dey do two things at once. E dey switch fast fast, but that switch dey cause errors. Do one thing well pass do two things anyhow!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-7",
    category: "focus",
    difficulty: "intermediate",
    question: "Text-input: What be the name of the technique where you set timer for 25 minutes before break?",
    type: "text-input",
    correctAnswer: "Pomodoro",
    explanation: "Na Pomodoro! Francesco Cirillo create am for 1980s. Tomato na the inspiration — Pomodoro mean tomato for Italian!",
    xp: 15,
    coins: 5,
  },
  {
    id: "foc-8",
    category: "focus",
    difficulty: "advanced",
    question: "You dey do deep work — coding for hours. Your friend dey call every 10 minutes. After many calls, your code get bugs. Wetin dey happen?",
    type: "multiple-choice",
    options: ["Your friend na saboteur", "Context switching dey increase cognitive load", "Your code na bad", "Computer dey slow"],
    correctAnswer: "Context switching dey increase cognitive load",
    explanation: "Context switching na brain thief! Every time you comot from your work go answer somebody, your brain dey use extra energy to go back. After many switches, brain don tire. Protect your deep work time!",
    xp: 20,
    coins: 8,
  },
  {
    id: "foc-9",
    category: "focus",
    difficulty: "advanced",
    question: "You notice say when you dey hungry, you no fit concentrate. What be the science behind am?",
    type: "multiple-choice",
    options: ["Your brain need glucose to function well", "Hunger dey make you spiritual", "Your stomach dey fight your brain", "No science, na laziness"],
    correctAnswer: "Your brain need glucose to function well",
    explanation: "Your brain na small organ but e dey use 20% of your body energy! When you dey hungry, glucose dey low, and your brain no get fuel to dey sharp. Eat well, think well!",
    xp: 20,
    coins: 8,
  },
  {
    id: "foc-10",
    category: "focus",
    difficulty: "advanced",
    question: "You dey write exam. One question hard you. You spend 30 minutes on am. Better approach?",
    type: "multiple-choice",
    options: ["Fight am till you finish", "Skip am, finish other questions, come back", "Leave the exam hall", "Ask your neighbor"],
    correctAnswer: "Skip am, finish other questions, come back",
    explanation: "Strategic na the name! No let one hard question waste all your time. Finish wetin you fit finish first, then come back to the hard one. Your brain fit don relax by then!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // THINKING (thk-1 to thk-10)
  // ============================================================
  {
    id: "thk-1",
    category: "thinking",
    difficulty: "beginner",
    question: "Your friend say: 'All politicians be the same.' Wetin be this type of thinking?",
    type: "multiple-choice",
    options: ["Critical thinking", "Stereotyping", "Creative thinking", "Logical thinking"],
    correctAnswer: "Stereotyping",
    explanation: "Stereotyping na when you use one idea to judge everybody. No be all politicians na the same — some dey try. Be careful with 'all' and 'never' talk!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-2",
    category: "thinking",
    difficulty: "beginner",
    question: "You want buy phone. You compare price, camera, and battery. Wetin be this type of thinking?",
    type: "multiple-choice",
    options: ["Emotional thinking", "Analytical thinking", "Random thinking", "No thinking"],
    correctAnswer: "Analytical thinking",
    explanation: "Analytical thinking na when you break something down into smaller parts to understand am well. E be like say you dey chop fish — you go remove bone before you eat!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-3",
    category: "thinking",
    difficulty: "beginner",
    question: "You dey cross road. You look left, right, and left again before you cross. What you dey use?",
    type: "multiple-choice",
    options: ["Common sense", "Problem-solving", "Decision-making", "All of the above"],
    correctAnswer: "All of the above",
    explanation: "You dey solve problem (how to cross safely), you dey decide (when to cross), and you dey use common sense! Brain dey work fast for dangerous situations.",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-4",
    category: "thinking",
    difficulty: "beginner",
    question: "Your papa say: 'If it rains, I no go market. It dey rain.' What you expect?",
    type: "multiple-choice",
    options: ["Papa go market", "Papa no go market", "Papa go buy umbrella", "Nobody know"],
    correctAnswer: "Papa no go market",
    explanation: "Na logical reasoning! If-then statement. If rain fall, papa no go market. Rain dey fall, so papa go stay house. Simple deduction!",
    xp: 10,
    coins: 3,
  },
  {
    id: "thk-5",
    category: "thinking",
    difficulty: "intermediate",
    question: "You dey argue with your friend. She say one thing, you say another. Both of you dey use emotions. This na example of what?",
    type: "multiple-choice",
    options: ["Rational debate", "Cognitive bias", "Scientific method", "Critical analysis"],
    correctAnswer: "Cognitive bias",
    explanation: "Cognitive bias na error for how we dey think. When emotions dey cloud our judgment, we no dey think clearly. Take breath, calm down, then think again!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-6",
    category: "thinking",
    difficulty: "intermediate",
    question: "Your friend say: 'I buy this shirt because Burna Boy wear am.' Wetin be the thinking error?",
    type: "multiple-choice",
    options: ["Bandwagon fallacy", "Ad hominem", "Slippery slope", "Straw man"],
    correctAnswer: "Bandwagon fallacy",
    explanation: "Bandwagon fallacy na when you do something because many people dey do am. Just because Burna Boy wear am no mean say the shirt go fine for you! Think for yourself!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-7",
    category: "thinking",
    difficulty: "intermediate",
    question: "Text-input: If all mangoes na fruits, and all fruits sweet, what be the logical conclusion about mangoes?",
    type: "text-input",
    correctAnswer: "Mangoes sweet",
    explanation: "Na syllogism — simple logical reasoning! If A = B, and B = C, then A = C. All mangoes na fruits, all fruits sweet, so all mangoes sweet. Logic dey sweet pass jollof!",
    xp: 15,
    coins: 5,
  },
  {
    id: "thk-8",
    category: "thinking",
    difficulty: "advanced",
    question: "You dey solve problem. You dey try different approaches — first principle thinking. Wetin be this method?",
    type: "multiple-choice",
    options: ["Copying别人的 solution", "Breaking problem to basic truths and building up", "Using old solutions", "Asking AI for answer"],
    correctAnswer: "Breaking problem to basic truths and building up",
    explanation: "First principles thinking na Elon Musk favorite! You break the problem down to the most basic truth, then build solution from there. E dey harder than copy-copy, but the result dey better pass!",
    xp: 20,
    coins: 8,
  },
  {
    id: "thk-9",
    category: "thinking",
    difficulty: "advanced",
    question: "You make one decision because you don already invest money for something. You no want lose the money so you continue. What be this thinking trap?",
    type: "multiple-choice",
    options: ["Opportunity cost", "Sunk cost fallacy", "Halo effect", "Dunning-Kruger effect"],
    correctAnswer: "Sunk cost fallacy",
    explanation: "Sunk cost fallacy na when you dey continue something because of wetin you don already spend — even if e no make sense again! The money don go. Focus on wetin dey forward, not wetin don pass!",
    xp: 20,
    coins: 8,
  },
  {
    id: "thk-10",
    category: "thinking",
    difficulty: "advanced",
    question: "You and your friend dey reason together. She dey play devil's advocate — dey challenge all your ideas. Wetin she dey do?",
    type: "multiple-choice",
    options: ["She hate you", "She dey help you see holes in your thinking", "She dey jealous", "She want fight"],
    correctAnswer: "She dey help you see holes in your thinking",
    explanation: "Devil's advocate na good thing! When person dey challenge your ideas, e dey make your thinking stronger. No take am personal — na for your own good. Iron dey sharpen iron!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // LEARNING (lrn-1 to lrn-10)
  // ============================================================
  {
    id: "lrn-1",
    category: "learning",
    difficulty: "beginner",
    question: "You want learn how to cook jollof rice. Wetin be the first thing you go do?",
    type: "multiple-choice",
    options: ["Start cooking immediately", "Watch video or get recipe", "Buy all ingredients first", "Call your mama"],
    correctAnswer: "Watch video or get recipe",
    explanation: "Preparation na the first step of learning! No just jump inside. First, gather information. Watch, read, understand. Then you go know wetin to do.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-2",
    category: "learning",
    difficulty: "beginner",
    question: "You dey learn new language. You no fit remember the words. Wetin go help?",
    type: "multiple-choice",
    options: ["Give up", "Practice small small every day", "Only study for exam", "Use Google Translate always"],
    correctAnswer: "Practice small small every day",
    explanation: "Consistency na the key to learning! Little drops of water dey make mighty ocean. Practice every day — even 15 minutes — e go add up!",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-3",
    category: "learning",
    difficulty: "beginner",
    question: "Your teacher explain maths for class. You no understand. Wetin be the best thing to do?",
    type: "multiple-choice",
    options: ["Shout 'I no sabi!'", "Ask teacher to explain again or find another source", "Copy your friend answer", "Tear the book"],
    correctAnswer: "Ask teacher to explain again or find another source",
    explanation: "No dey shy to ask questions! The best students na the ones wey dey ask questions. If one teacher no explain well, find another person wey go explain.",
    hint: "Asking questions na sign of strength, not weakness.",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-4",
    category: "learning",
    difficulty: "beginner",
    question: "You learn something today, tomorrow you forget. Wetin be the reason?",
    type: "multiple-choice",
    options: ["Your brain na sieve", "You no revise — forgetting dey normal without practice", "The thing no important", "You need medicine"],
    correctAnswer: "You no revise — forgetting dey normal without practice",
    explanation: "Forgetting curve na real! Ebbinghaus show say if you no revise, you go forget up to 70% for one day. Revise, revise, revise!",
    xp: 10,
    coins: 3,
  },
  {
    id: "lrn-5",
    category: "learning",
    difficulty: "intermediate",
    question: "You dey study. You dey highlight everything for textbook. Your friend say this method no effective. Why?",
    type: "multiple-choice",
    options: ["Highlighting na waste of time", "If you highlight everything, nothing dey stand out", "Highlighting dey damage book", "Your friend na hater"],
    correctAnswer: "If you highlight everything, nothing dey stand out",
    explanation: "Highlighting feel like say you dey learn, but e dey passive! Better method na to highlight only key points, then write summary for your own words.",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-6",
    category: "learning",
    difficulty: "intermediate",
    question: "You read one topic finish. To check if you understand am, wetin be the best way?",
    type: "multiple-choice",
    options: ["Read am again ten times", "Try teach the topic to somebody else", "Look at your notes again", "Sleep on it"],
    correctAnswer: "Try teach the topic to somebody else",
    explanation: "Feynman technique! If you fit explain something simple, you don really understand am. If you dey struggle to explain, that mean you need to study more. Teaching na the best way to learn!",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-7",
    category: "learning",
    difficulty: "intermediate",
    question: "Text-input: What be the name of the curve wey show say you fit forget up to 70% of wetin you learn if you no revise?",
    type: "text-input",
    correctAnswer: "Forgetting curve",
    explanation: "Hermann Ebbinghaus discover am! The forgetting curve show say your brain dey throw away information wey e think e no need. Revision na how you tell your brain say: 'This thing important, hold am!'",
    xp: 15,
    coins: 5,
  },
  {
    id: "lrn-8",
    category: "learning",
    difficulty: "advanced",
    question: "You dey learn coding. You no fit remember syntax. You dey frustrate. Wetin be the best approach?",
    type: "multiple-choice",
    options: ["Mugu no fit code", "Practice by building small projects — don't just memorize syntax", "Google everything", "Give up"],
    correctAnswer: "Practice by building small projects — don't just memorize syntax",
    explanation: "Project-based learning na the real deal! When you dey build something, your brain dey remember syntax because you dey use am. Learning by doing pass learning by reading!",
    xp: 20,
    coins: 8,
  },
  {
    id: "lrn-9",
    category: "learning",
    difficulty: "advanced",
    question: "You notice say you learn better when you dey stand up and dey talk. Your friend learn better when she dey sit and dey read. Why the difference?",
    type: "multiple-choice",
    options: ["Your friend na book worm", "People get different learning styles — visual, auditory, kinesthetic", "One of una dey wrong", "Na age dey cause am"],
    correctAnswer: "People get different learning styles — visual, auditory, kinesthetic",
    explanation: "No be everybody learn the same way! Some people na visual — dem dey learn by seeing. Some na auditory — dem dey learn by hearing. Some na kinesthetic — dem dey learn by doing. Know your own style!",
    xp: 20,
    coins: 8,
  },
  {
    id: "lrn-10",
    category: "learning",
    difficulty: "advanced",
    question: "You dey study hard but you no see improvement. Your friend study less but she dey pass. Wetin she dey do different?",
    type: "multiple-choice",
    options: ["She dey do exam malpractice", "She dey use active recall and spaced repetition", "She dey lucky", "She know the teacher"],
    correctAnswer: "She dey use active recall and spaced repetition",
    explanation: "Study smart pass study hard! Active recall mean say you dey test yourself instead of just reading. Spaced repetition mean say you dey come back to the material at intervals. These methods dey work better than just read-read-read!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // CREATIVITY (crv-1 to crv-10)
  // ============================================================
  {
    id: "crv-1",
    category: "creativity",
    difficulty: "beginner",
    question: "You want design birthday card for your friend. Wetin be the first step?",
    type: "multiple-choice",
    options: ["Copy your friend old card", "Brainstorm ideas — think about wetin she like", "Buy card from shop", "Draw one random thing"],
    correctAnswer: "Brainstorm ideas — think about wetin she like",
    explanation: "Brainstorming na the start of all creativity! Think about wetin your friend like, her favorite color, things wey make her happy. Then you go get better ideas.",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-2",
    category: "creativity",
    difficulty: "beginner",
    question: "You dey cook, you no get all ingredients. You use what you get to make something new. Wetin you dey show?",
    type: "multiple-choice",
    options: ["Laziness", "Resourcefulness and creativity", "Lack of money", "Bad cooking"],
    correctAnswer: "Resourcefulness and creativity",
    explanation: "Creativity no be just art! When you dey use wetin you get to solve problems, na creativity be that. Our mama dem na the most creative people — dem dey make magic for kitchen!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-3",
    category: "creativity",
    difficulty: "beginner",
    question: "Your boss say: 'Think outside the box.' Wetin he mean?",
    type: "multiple-choice",
    options: ["Comot for the office", "Think in new and different ways", "Carry box go house", "Think about box"],
    correctAnswer: "Think in new and different ways",
    explanation: "Thinking outside the box mean say you should no dey follow the same old way. Try new ideas, no dey fear to be different. That's where the best ideas dey hide!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-4",
    category: "creativity",
    difficulty: "beginner",
    question: "You dey write story, you no fit start. Wetin go help your creative block?",
    type: "multiple-choice",
    options: ["Write anything, even if e no make sense", "Wait for inspiration to come", "Stop writing forever", "Copy another person story"],
    correctAnswer: "Write anything, even if e no make sense",
    explanation: "The best way to start na to just start! Write anyhow — editing na for later. Your brain go warm up and better ideas go come. Perfectionism na creativity killer!",
    xp: 10,
    coins: 3,
  },
  {
    id: "crv-5",
    category: "creativity",
    difficulty: "intermediate",
    question: "You dey solve one problem. You try one way, e no work. You try another, e still no work. Your friend say: 'Try combine both ideas.' Wetin she dey do?",
    type: "multiple-choice",
    options: ["Wasting time", "Synthesis — combining ideas to create something new", "Confusing you", "Being smart"],
    correctAnswer: "Synthesis — combining ideas to create something new",
    explanation: "Synthesis na creativity superpower! When you take two ideas and combine them to form something new, na innovation be that. Afrobeats na synthesis — Fela combine jazz, highlife, and funk to create something wey never exist before!",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-6",
    category: "creativity",
    difficulty: "intermediate",
    question: "You dey paint. You make mistake — the color spill for canvas. Instead of throw away, you use am to create something beautiful. Wetin be this mindset?",
    type: "multiple-choice",
    options: ["Laziness", "Growth mindset — turning mistakes into opportunities", "Carelessness", "Bad painting"],
    correctAnswer: "Growth mindset — turning mistakes into opportunities",
    explanation: "Growth mindset na the belief say mistakes na learning opportunities. Instead of vex for mistakes, use am! Some of the best art come from 'accidents.' Your mistakes fit be your masterpiece!",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-7",
    category: "creativity",
    difficulty: "intermediate",
    question: "Text-input: What be the name of the thinking method where you use random words to spark new ideas?",
    type: "text-input",
    correctAnswer: "Brainstorming",
    explanation: "Brainstorming! You fit use random words to generate ideas. For example: if you get word 'traffic', you fit think about: traffic light, traffic jam, traffic police... Your brain go start connecting dots!",
    xp: 15,
    coins: 5,
  },
  {
    id: "crv-8",
    category: "creativity",
    difficulty: "advanced",
    question: "You dey create content for social media. You want your content to stand out. Wetin be the key?",
    type: "multiple-choice",
    options: ["Copy what everybody dey do", "Find your unique voice and perspective", "Post every minute", "Use only English"],
    correctAnswer: "Find your unique voice and perspective",
    explanation: "Your unique perspective na your superpower! No be everybody go like your content, but the ones wey go like am go dey loyal. Authenticity pass copy-paste any day!",
    xp: 20,
    coins: 8,
  },
  {
    id: "crv-9",
    category: "creativity",
    difficulty: "advanced",
    question: "You notice say your best ideas come when you dey do nothing — like for shower or for bed. Why?",
    type: "multiple-choice",
    options: ["You dey lazy", "Your brain dey default mode network — creative incubation", "You need medicine", "Na superstition"],
    correctAnswer: "Your brain dey default mode network — creative incubation",
    explanation: "Default mode network na when your brain dey at rest but still dey work in the background. That's when creative connections dey happen! So that shower idea no be accident — na science!",
    xp: 20,
    coins: 8,
  },
  {
    id: "crv-10",
    category: "creativity",
    difficulty: "advanced",
    question: "You get one big dream — you want start business. You dey scared say people go laugh. Wetin go help you?",
    type: "multiple-choice",
    options: ["Wait till you no fear", "Start small, learn as you dey go — fear no fit stop you", "Forget the dream", "Ask everybody for advice"],
    correctAnswer: "Start small, learn as you dey go — fear no fit stop you",
    explanation: "Creativity and innovation need courage! No wait till everything perfect — e never go perfect. Start small, make mistakes, learn. Every successful person start somewhere. Burna Boy no become star one day!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // HEALTH (hlth-1 to hlth-10)
  // ============================================================
  {
    id: "hlth-1",
    category: "health",
    difficulty: "beginner",
    question: "You dey feel tired every morning. Wetin be the first thing you go check?",
    type: "multiple-choice",
    options: ["Whether you dey sick", "Your sleep — whether you dey sleep well and enough", "Your phone battery", "Your food"],
    correctAnswer: "Your sleep — whether you dey sleep well and enough",
    explanation: "Sleep na the foundation of health! If you no dey sleep well, everything go suffer. Adult suppose sleep 7-9 hours. No be mumu thing — sleep na investment!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-2",
    category: "health",
    difficulty: "beginner",
    question: "You dey stress for work. Your body dey pain, head dey kill you. Wetin fit help?",
    type: "multiple-choice",
    options: ["Drink more coffee", "Exercise, rest, and talk to somebody", "Ignore am", "Take panadol every day"],
    correctAnswer: "Exercise, rest, and talk to somebody",
    explanation: "Exercise dey release endorphins — happy chemicals for body! Rest dey help body recover. Talking to somebody dey help your mental health. These three na the stress buster!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-3",
    category: "health",
    difficulty: "beginner",
    question: "You dey drink water every day. Wetin water dey do for body?",
    type: "multiple-choice",
    options: ["Nothing much", "It dey regulate temperature, transport nutrients, and remove waste", "E dey make you fat", "E dey make you tall"],
    correctAnswer: "It dey regulate temperature, transport nutrients, and remove waste",
    explanation: "Water na life! Your body na about 60% water. E dey control temperature, help digest food, carry nutrients go different parts of body, and flush out waste. Drink water every day — no be suggestion!",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-4",
    category: "health",
    difficulty: "beginner",
    question: "You dey chop jollof rice every day for lunch. Wetin you suppose add?",
    type: "multiple-choice",
    options: ["More rice", "Vegetables and fruits — balance na key", "More stew", "Nothing, jollof na complete meal"],
    correctAnswer: "Vegetables and fruits — balance na key",
    explanation: "Balance diet na the way to go! Jollof rice good, but your body need vegetables, fruits, and protein too. No be about one food — na about balance!",
    hint: "Think about food groups and balanced nutrition.",
    xp: 10,
    coins: 3,
  },
  {
    id: "hlth-5",
    category: "health",
    difficulty: "intermediate",
    question: "You dey sit down for desk for 8 hours every day. Your back dey pain. Wetin be the problem?",
    type: "multiple-choice",
    options: ["Your chair na bad", "Sedentary lifestyle — your body need movement", "You too old", "Na spiritual attack"],
    correctAnswer: "Sedentary lifestyle — your body need movement",
    explanation: "Your body na designed to move! When you dey sit for long time, your muscles dey weak, your back dey pain. Stand up every 30 minutes, stretch, move your body. Movement na medicine!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-6",
    category: "health",
    difficulty: "intermediate",
    question: "You dey always dey anxious before exam. Your heart dey beat fast, palm dey sweat. Wetin dey happen?",
    type: "multiple-choice",
    options: ["You dey dying", "Fight or flight response — your body preparing for danger", "You need surgery", "You dey possessed"],
    correctAnswer: "Fight or flight response — your body preparing for danger",
    explanation: "Fight or flight na your body security system! When e think danger dey, e release adrenaline. Your heart dey beat fast so blood fit move. E no be bad thing — e dey help you survive. Just learn to manage am!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-7",
    category: "health",
    difficulty: "intermediate",
    question: "Text-input: What be the name of the chemical wey your body release when you exercise, wey dey make you feel happy?",
    type: "text-input",
    correctAnswer: "Endorphins",
    explanation: "Endorphins na natural painkillers and mood boosters! When you exercise, your body dey release endorphins, and you go feel happy. That's why exercise dey good for mental health. No be joke — na science!",
    xp: 15,
    coins: 5,
  },
  {
    id: "hlth-8",
    category: "health",
    difficulty: "advanced",
    question: "You dey work, you no fit sleep at night. You dey check phone every time. Wetin be the problem?",
    type: "multiple-choice",
    options: ["You too sharp", "Blue light from screen dey suppress melatonin — your sleep hormone", "You need sleeping pill", "Na genes"],
    correctAnswer: "Blue light from screen dey suppress melatonin — your sleep hormone",
    explanation: "Blue light from phone and laptop dey trick your brain to think say na daytime! This dey suppress melatonin — the hormone wey help you sleep. Stop phone 1 hour before bed. Your sleep go improve!",
    xp: 20,
    coins: 8,
  },
  {
    id: "hlth-9",
    category: "health",
    difficulty: "advanced",
    question: "You dey always dey tired even though you dey sleep 10 hours. Wetin fit be the reason?",
    type: "multiple-choice",
    options: ["You too lazy", "Sleep quality dey matter pass sleep quantity — you no dey deep sleep", "You need 15 hours", "Na COVID"],
    correctAnswer: "Sleep quality dey matter pass sleep quantity — you no dey deep sleep",
    explanation: "Quality pass quantity! You fit sleep 10 hours but if your deep sleep no dey enough, you go still dey tired. Factors: stress, phone before bed, irregular sleep time, alcohol. Fix your sleep hygiene!",
    xp: 20,
    coins: 8,
  },
  {
    id: "hlth-10",
    category: "health",
    difficulty: "advanced",
    question: "You notice say when you dey exercise, your thinking dey better. You dey solve problems better. Why?",
    type: "multiple-choice",
    options: ["Na coincidence", "Exercise dey increase blood flow to brain and release BDNF — brain fertilizer", "You dey imagine am", "Na adrenaline"],
    correctAnswer: "Exercise dey increase blood flow to brain and release BDNF — brain fertilizer",
    explanation: "Exercise na brain food! When you dey exercise, blood dey flow better to brain. E also dey release BDNF (Brain-Derived Neurotrophic Factor) — wey be like fertilizer for brain cells. Exercise dey help you think better, remember better, and create better!",
    xp: 20,
    coins: 8,
  },

  // ============================================================
  // EMOTIONAL INTELLIGENCE (ei-1 to ei-10)
  // ============================================================
  {
    id: "ei-1",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Your friend vex for you because you come late to her party. Wetin you suppose do first?",
    type: "multiple-choice",
    options: ["Vex back", "Say sorry and understand why she dey upset", "Ignore her", "Blame traffic"],
    correctAnswer: "Say sorry and understand why she dey upset",
    explanation: "Emotional intelligence start with empathy! Understand how your friend feel before you defend yourself. 'Sorry' no go kill you, but e go save the friendship!",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-2",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "You dey angry because your roommate chop your food. Wetin you suppose do?",
    type: "multiple-choice",
    options: ["Break her plate", "Calm down, then talk to her about am", "Go tell landlord", "Stop eating"],
    correctAnswer: "Calm down, then talk to her about am",
    explanation: "Angry no be excuse to do anyhow! Calm down first — count to 10, take deep breath. Then talk. When you dey calm, you go fit express yourself better. No let anger control you!",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-3",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "Your colleague dey always dey smile even when e dey struggle. Wetin you think?",
    type: "multiple-choice",
    options: ["E dey happy always", "E fit dey hiding true feelings — check on am", "E na mumu", "E perfect"],
    correctAnswer: "E fit dey hiding true feelings — check on am",
    explanation: "No be everything wey glitter na gold! Some people dey smile to hide pain. Emotional intelligence mean say you fit read beyond the surface. Check on your people — 'How you dey?' fit mean everything!",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-4",
    category: "emotional-intelligence",
    difficulty: "beginner",
    question: "You fail exam. You dey feel sad and frustrated. Wetin be the healthy way to handle am?",
    type: "multiple-choice",
    options: ["Cry forever", "Feel the emotion, learn from am, then move forward", "Pretend say nothing happen", "Blame everybody"],
    correctAnswer: "Feel the emotion, learn from am, then move forward",
    explanation: "Emotions na valid! No dey suppress am. Feel am, understand why you dey feel that way, then ask yourself: wetin I fit learn? Then move. Emotions na compass — e dey show you wetin matter to you.",
    xp: 10,
    coins: 3,
  },
  {
    id: "ei-5",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Your boss dey shout for you for office. You want shout back, but you pause. Wetin you dey do?",
    type: "multiple-choice",
    options: ["You dey fear am", "Self-regulation — managing your emotional response", "You weak", "You dey plan revenge"],
    correctAnswer: "Self-regulation — managing your emotional response",
    explanation: "Self-regulation na superpower! When you fit pause before you react, you dey choose your response instead of letting emotion choose for you. That pause — e fit save your job, your relationship, everything!",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-6",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Your friend dey quiet today. You no need to ask — you just notice say something dey wrong. Wetin this show?",
    type: "multiple-choice",
    options: ["You dey gbege", "Emotional awareness — you dey attuned to others' feelings", "You dey overthink", "You dey witch"],
    correctAnswer: "Emotional awareness — you dey attuned to others' feelings",
    explanation: "Emotional awareness na when you fit detect feelings of others — even when dem no talk. This na important skill for relationship. When you notice small changes, you fit help before problem dey big!",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-7",
    category: "emotional-intelligence",
    difficulty: "intermediate",
    question: "Text-input: What be the term for when you understand and share the feelings of another person?",
    type: "text-input",
    correctAnswer: "Empathy",
    explanation: "Empathy na emotional superpower! E mean say you fit put yourself for another person shoe. No be sympathy (feeling sorry for person) — na feeling WITH person. Empathy dey build connection and trust!",
    xp: 15,
    coins: 5,
  },
  {
    id: "ei-8",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "You dey manage a team. One member always dey argue. Instead of punish am, you understand say e dey passionate about the work. Wetin you dey show?",
    type: "multiple-choice",
    options: ["You weak for leader", "Emotional intelligence — reading motivation behind behavior", "You dey fear am", "You no serious"],
    correctAnswer: "Emotional intelligence — reading motivation behind behavior",
    explanation: "Advanced emotional intelligence! E no be about the behavior alone — na about understanding wetin dey drive the behavior. Your team member no dey fight you — e dey fight for the work. Channel that energy well!",
    xp: 20,
    coins: 8,
  },
  {
    id: "ei-9",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "You notice say when people dey around you, dem dey feel comfortable. Dem dey share their problems with you. Wetin you get?",
    type: "multiple-choice",
    options: ["You be gist partner", "High social skills and emotional intelligence — people trust your presence", "You be therapist", "You dey use people"],
    correctAnswer: "High social skills and emotional intelligence — people trust your presence",
    explanation: "When people feel comfortable around you, na sign say you get high emotional intelligence. You dey make people feel heard and understood. This na rare gift — use am well to help others!",
    xp: 20,
    coins: 8,
  },
  {
    id: "ei-10",
    category: "emotional-intelligence",
    difficulty: "advanced",
    question: "You dey argue with your partner. Instead of winning the argument, you try understand her perspective. Wetin be the goal?",
    type: "multiple-choice",
    options: ["Lose the argument", "Emotional connection — the relationship dey more important than the argument", "You dey manipulate her", "You dey weak"],
    correctAnswer: "Emotional connection — the relationship dey more important than the argument",
    explanation: "In relationships, no be about who win or lose. Emotional intelligence mean say you value the connection pass the argument. When you try understand your partner, you dey build trust and love. Winning argument but losing person — that na loss!",
    xp: 20,
    coins: 8,
  },
];
