import { BodyBrainChallenge } from "./types";

export const BODY_BRAIN_CHALLENGES: BodyBrainChallenge[] = [
  {
    id: "bb-mem-walk",
    title: "10-Minute Memory Walk",
    tagline: "Walk outdoors while actively memorizing 4 sequential visual anchors.",
    physicalAction: "Walk continuously at a brisk pace for 10 minutes.",
    cognitiveAction: "Spot and encode 4 distinct objects along your path: an Oak Tree, Red Vehicle, Blue Door, and Street Lamp in exact sequence.",
    durationMinutes: 10,
    verificationMethod: "cognitive_recall",
    verificationInstructions: "BrainGym will monitor your movement duration, followed by a 3-question post-walk recall test upon completion.",
    expectedOutcome: "Enhances hippocampal episodic memory encoding and cardiovascular cerebral perfusion.",
    xpReward: 120,
    coinReward: 30,
    momentumImpact: 5,
    difficulty: "intermediate",
    category: "Walk & Recall",
  },
  {
    id: "bb-obs-scan",
    title: "The Mindful Observation Walk",
    tagline: "Engage selective visual attention to catalog 4 distinct natural textures.",
    physicalAction: "Walk for 8 minutes through a park, street, or outdoor trail.",
    cognitiveAction: "Consciously identify and evaluate 4 distinct geometric textures and 1 architectural anomaly.",
    durationMinutes: 8,
    verificationMethod: "cognitive_recall",
    verificationInstructions: "Complete an 8-minute motion-timed walk, followed by an observation discrimination check.",
    expectedOutcome: "Strengthens parietal lobe attentional salience and top-down sensory filtering.",
    xpReward: 110,
    coinReward: 25,
    momentumImpact: 4,
    difficulty: "beginner",
    category: "Observation",
  },
  {
    id: "bb-bal-recall",
    title: "Single-Leg Balance & Mental Math",
    tagline: "Hold physical equilibrium while calculating 100 - 7 cadence arithmetic.",
    physicalAction: "Balance on your left foot for 60 seconds, then right foot for 60 seconds.",
    cognitiveAction: "Mentally subtract 7 from 100 continuously (100 → 93 → 86 → 79 → 72) without pausing your balance.",
    durationMinutes: 3,
    verificationMethod: "cognitive_recall",
    verificationInstructions: "Sensor motion stability verification + arithmetic recall check upon completion.",
    expectedOutcome: "Challenging dual-task cognitive interference between the cerebellum and dorsolateral prefrontal cortex.",
    xpReward: 95,
    coinReward: 20,
    momentumImpact: 4,
    difficulty: "advanced",
    category: "Balance & Memory",
  },
  {
    id: "bb-mov-count",
    title: "Movement + Backward Counting Sprint",
    tagline: "Perform 15 rhythmic bodyweight squats while reciting the alphabet backwards.",
    physicalAction: "Complete 15 controlled squats with full range of motion.",
    cognitiveAction: "Recite letters Z to L backwards in exact cadence with each repetition.",
    durationMinutes: 4,
    verificationMethod: "motion_sensor",
    verificationInstructions: "Device accelerometer counts rhythmic repetitions and tempo consistency.",
    expectedOutcome: "Accelerates motor-cognitive synchronization and working memory executive control.",
    xpReward: 100,
    coinReward: 25,
    momentumImpact: 4,
    difficulty: "intermediate",
    category: "Movement & Math",
  },
  {
    id: "bb-coord-reflex",
    title: "Cross-Body Tactile Reflex Drill",
    tagline: "Rapid opposite hand-to-knee touches with alternating color callouts.",
    physicalAction: "Alternate touching your right hand to left knee, then left hand to right knee at maximum tempo for 90 seconds.",
    cognitiveAction: "Call out contrasting color names (saying 'Blue' when touching left, 'Red' when touching right).",
    durationMinutes: 2,
    verificationMethod: "motion_sensor",
    verificationInstructions: "Motion sensor checks continuous cadence and cadence stability.",
    expectedOutcome: "Strengthens corpus callosum interhemispheric transfer and reflex inhibition.",
    xpReward: 85,
    coinReward: 20,
    momentumImpact: 3,
    difficulty: "beginner",
    category: "Coordination",
  },
];

export function getTodaysBodyBrainChallenge(): BodyBrainChallenge {
  const dayIndex = new Date().getDate();
  return BODY_BRAIN_CHALLENGES[dayIndex % BODY_BRAIN_CHALLENGES.length];
}
